### ISSUE TITLE
Several targeting issues

### ISSUE THREAD

**Issue by JBoughter** [Apostolique/Agar.io-bot#1]
For obvious reasons, the project being new doesn't mean the targeting system is absolutely 100% on point. Here are some obvious ones. Feel free to post other findings.

- The bot will be chased by a threat, then will corner itself into a wall and won't move.
- The bot will prioritize prey over large threats that are in the way (and just doesn't see them while chasing).
- The bot will shy away from the virus to collect food and immediately come back.

@Apostolique is planning on revamping the targeting system to combat this.

**Comment by AshleyDodd** [comment]
The last time i checked, the bots movement was based on food on the "safe" side of the red lines. If there is no food to select/on the "safe" side then the bot finds it hard to escape.

Although if you are watching the bot as it plays, press "t" to enable manual control to escape then "t" again to disable manual control and let the bot continue to run.

**Comment by Apostolique** [comment]
It will probably take me a few days before I can think of a better targeting system. Ideally, there shouldn't be a [safe] -> eat freely / [unsafe] -> run away mode that changes the targeting. Every decision should be made based on current visible game state. To make it better, it needs a positioning engine or something similar.

**Comment by Swaddle** [comment]
From observing the bot, trying to catch smaller players is somewhat hopeless, either they are faster and can escape or the bot doesn't notice other important threats ( like a player right on top of you ). Catching another player should be a lower priority than consuming food.   Usually the only time it is successful is when the player makes some misjudgement.

I would propose to change the geometry of what your bot determines is a viable area. Maybe add in some weighting, more dangerous adversaries that are moving towards you are a higher threat and so your bot "sees" them as closer, while something like a virus, it doesn't move, so your bot can get fairly close to collect food. Then the bot should try to distance itself from danger. Also getting stuck on the boundary wall isn't a good tactic, it allows you to be cornered. I would also add this as a factor to try and avoid getting too close. 

Also I notice that it ignores some food that gets respawned. Maybe more frequent checks? From observing players, even in free for all, there appear to be teams that work together to coral prey. How about having multiple bots that somehow passively work together if you want to hunt.

**Comment by b3ck** [comment]
I don't suppose there is a way to tap into the 'spectate mode' data to account for the entire map as whole is there?  Maybe there is a way we could use that data to give the bot an advance notice on incoming threats or maybe better escape routes?

**Comment by JBoughter** [comment]
It might require more than one connection I'd imagine, which makes it a bit more complex. Other than that, that's whether the server blocks the same connection using spectate and playing at the same time or not, but then again, I'd doubt because if there are two people on one connection doing this, then it's different. Would need tested if that's the case.

**Comment by Apostolique** [comment]
I'm trying to create a bot that can operate using the same data that a human player would have. I'd rather not have it "cheat" with spectator data.
