### ISSUE TITLE
Bot targets smaller blobs inside the split zone of larger blob

### ISSUE THREAD

**Issue by chris13524** [Apostolique/Agar.io-bot#101]
In this case, there was a big player with smaller versions of himself around him. The bot would target the smaller versions, then enter the split zone. It would immediately turn around and exit the zone, then turn around and target the smaller ones again.

**Comment by chris13524** [comment]
A similar problem is when it tracks food in the not-safe zone. I recommend adding a check when finding the destination whether or not the destination is in a not-safe zone, if so, go to the next best spot.

**Comment by Apostolique** [comment]
I remember that check for now, it used to be done though.
