### ISSUE TITLE
Teams Mode

### ISSUE THREAD

**Issue by Viliusx** [Apostolique/Agar.io-bot#102]
In Teams Mode it chases down smaller cells which are in the same team as you!

Also it runs away from bigger cells which are same team as you!

Please I really want you to fix this and I had this problem for a while now. Pretty please? :cake: :C

**Comment by Kosti1** [comment]
Bot is not for team mode.

**Comment by chris13524** [comment]
I would think team mode would be simple to implement right? Just ignore own team like you do big viruses and you should be fine.

**Comment by Viliusx** [comment]
Woah, I thought only the developer (Apostolique) can reply to issues? Kosti1, that's none of your business, why do you waste your time reading issues on a Agar.io bot's code in github?

**Comment by chris13524** [comment]
It is fun to read issues and help people!

**Comment by Viliusx** [comment]
Apostolique, please reply?? ;-;

**Comment by Apostolique** [comment]
Other people can respond, it doesn't matter as I had already responded to this exact same thing before. And no, team mode isn't easier to code as allies can block you and you can block them.

**Comment by chris13524** [comment]
What do you mean they can block you? Like you can't go through them?

**Comment by Apostolique** [comment]
No, you can't. When the mode first came out, people on the same team would hide inside their biggest team mate becoming "invincible".

**Comment by chris13524** [comment]
You were talking about making viruses an "obstacle" rather than an enemy, why not make people on your own team obstacles too?

**Comment by Apostolique** [comment]
It hasn't been coded yet. When it's done then yes it will be easy.
