### ISSUE TITLE
[enhancement] server selector

### ISSUE THREAD

**Issue by DarkN3ss61** [Apostolique/Agar.io-bot#11]
Is it possible to have a server selector implemented?
Since there a a few servers under each category, that would mean that you could play with your friends, without needing to keep refreshing until you are both on the save server

**Comment by Apostolique** [comment]
You can already connect to a specific server IP using the **window.connect("ws://45.79.196.51:443");** command in the console. In each servers though, there might be multiple rooms so you might have to send that command in a couple times.

**Comment by DarkN3ss61** [comment]
why not have this implemented into the bot? so it run the comment 5 or 10 times to log the IP's in a dropdown where you can select the one you want

**Comment by Apostolique** [comment]
I am pretty sure there already exists something like this, if you look through the Reddit forums, you might find people talking about it. http://www.reddit.com/r/Agario/
Unless you're planning on running an army of bots though, this feature is out of my scope.
