### ISSUE TITLE
Trapped

### ISSUE THREAD

**Issue by rockydog92** [Apostolique/Agar.io-bot#111]
When the bot gets trapped (by bigger blobs or by bigger blobs and the green safe zone thingys) it wont split to get away.

**Comment by chris13524** [comment]
The bot is not programmed to split yet.

**Comment by rockydog92** [comment]
"How To Make It Split By: A Noob Coder  (Not Me) (I code websites) (Using Jekyll)
VVVVVVVVVVVVVVVVVVVVVVVVV
| | | | | | | | | | | | | | | | | | | | | | | | | | | | 
lllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllll
1111111111111111111111111111
////////////////////////////////////////////////////////
\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii
if cornered display "Split or Die" 
      if click "Split" press key: spacebar
                  if click "Die" goto biggest blob

**Comment by chris13524** [comment]
Splinting is not the hard part, it's managing and moving multiple blobs at the same time.

**Comment by rockydog92** [comment]
Ooo, Ooo!!!!
Let's call on Sethbling!!!!!!!
He just made a bot that will play a Mario game!!!!!

**Comment by chris13524** [comment]
It's Sethbling's job to impress YouTube, I am sure he spent a large amount of time working on that. Now I don't know what Apostolique does for a living, or even if he is on summer vacation from school right now, but I am sure he is doing his best. He is planning to add splinting, in the future though.

**Comment by rockydog92** [comment]
Ok :]

**Comment by SuperSplite** [comment]
wtf

**Comment by chris13524** [comment]
What?

**Comment by Apostolique** [comment]
Right now, the bot is made to completely stop moving when surrounded. Also, unless someone can prove me wrong, I do not consider splitting to escape a viable strategy. I can easily reach #1 on Leaderboard without splitting to escape a single time.

**Comment by chris13524** [comment]
I have never been able to get number 1, I always go to another tab and when I come back, the blob is at 10 just starting out. Does the bot work when in another tab? I am using Firefox.

**Comment by Apostolique** [comment]
I was talking about when I play without the bot on.

**Comment by chris13524** [comment]
Oh, ok
