### ISSUE TITLE
Make new codes 

### ISSUE THREAD

**Issue by genetic007** [Apostolique/Agar.io-bot#113]
by having are bot be invisible to other players 
by making so you can start with a certain number of mass to begin with

**Comment by chris13524** [comment]
I am sorry to break it to you, but that is not how bots work. The only things the bot can do are move the blob. What you are talking about would be considered "hacking". The goal of a bot is not to hack, but instead to imitate a real player in playing the game.

**Comment by Apostolique** [comment]
lol

**Comment by chris13524** [comment]
It's not "Make new codes", it's "programming", or "coding"

**Comment by lukemagdalin** [comment]
its called coding becuase we are using a programe to open a coded website that you can code on
writen in java script thats why i have tampermonkey and tampermonkey beta
