### ISSUE TITLE
working

### ISSUE THREAD

**Issue by the133448** [Apostolique/Agar.io-bot#116]
Updated to lateest version on Opera, and just not working at all.

**Comment by abalabahaha** [comment]
Do you have an extension that emulates GreaseMonkey? You're supposed to use one of those to install this.

**Comment by the133448** [comment]
It was working in the previous versions though, Tampermonkey is what I was using 

Here is the log

Running Apos Bot!
VM2473:26 Apos Bot!
sdk.js:57 GET https://s-static.ak.facebook.com/connect/xd_arbiter/1ldYU13brY_.js?version=41 net::ERR_INSECURE_RESPONSEk @ sdk.js:57window.FB.r.create.whenReady @ sdk.js:91window.FB.t.register.init @ sdk.js:89window.FB.t.create @ sdk.js:89ra @ sdk.js:91(anonymous function) @ sdk.js:91(anonymous function) @ sdk.js:80w @ sdk.js:37window.FB.g.fire @ sdk.js:80r @ sdk.js:130(anonymous function) @ sdk.js:130w @ sdk.js:37(anonymous function) @ sdk.js:130
browser.js:42 Opera has modified script or content on static.ak.facebook.com (PATCH-1195, Facebook - block first character in the comment field from triggering a single key keyboard shortcut). See browser.js for details
(index):1 Resource interpreted as Image but transferred with MIME type text/html: "http://googleads4.g.doubleclick.net/pcs/view?xai=AKAOjstr0R504YDJSZcrJiEIjg…IxOzObK_xXizkqRszAo0TqoPGMrBys2cllhwjET&sig=Cg0ArKJSzB9iJKJfME5fEAE&adurl=".
getad?site=263059:17 Resource interpreted as Image but transferred with MIME type text/html: "http://ib.adnxs.com/getuid?http://ads.lfstmedia.com/mark/appnexus?user_id=$…me=%24%24timestamp%24%24&rurl=http%3A%2F%2Fcms.lfstmedia.com%2Fputmatch-an".q @ getad?site=263059:17O.showAd @ getad?site=263059:20window.LSM_Slot.window.LSM_Slot.e.show @ getad?site=263059:58window.LSM_Slot.window.LSM_Slot.e.onLoad @ getad?site=263059:57(anonymous function) @ slot121593?adkey=9a0&ad_size=728x90&jsonp=LSM_SlotObj_1.onLoad&__location=http%3A%2F%2Fagar.io%2F&_…:1
(index):1 Resource interpreted as Image but transferred with MIME type text/plain: "http://bidi-geo.mythings.com/bidi/rubicon".
(index):1 Resource interpreted as Image but transferred with MIME type text/html: "http://ib.adnxs.com/getuid?http://ads.lfstmedia.com/mark/appnexus?user_id=$…me=%24%24timestamp%24%24&rurl=http%3A%2F%2Fcms.lfstmedia.com%2Fputmatch-an".
main_out.js?542:2 Find SG-Singapore
main_out.js?542:2 Find SG-Singapore
main_out.js?542:2 Connecting to ws://139.162.1.34:443
main_out.js?542:2 WebSocket connection to 'ws://139.162.1.34:443/' failed: WebSocket is closed before the connection is established.
main_out.js?542:2 socket error
main_out.js?542:2 Connecting to ws://139.162.1.34:443
sdk.js:57 GET https://www.facebook.com/v2.3/plugins/like.php?action=like&app_id=677505792…playagar.io&layout=button&locale=en_US&sdk=joey&share=true&show_faces=true net::ERR_INSECURE_RESPONSEk @ sdk.js:57window.FB.p.extend.process @ sdk.js:136window.FB.ja @ sdk.js:134(anonymous function) @ sdk.js:134w @ sdk.js:37x @ sdk.js:134window.FB.ES.parse @ sdk.js:134i @ sdk.js:65
main_out.js?542:2 socket open
2fv1_5.html?domain=cdn.lfstmedia.com:11 Blocked a frame with origin "http://cdn.lfstmedia.com" from accessing a frame with origin "http://agar.io". Protocols, domains, and ports must match.(anonymous function) @ fv1_5.html?domain=cdn.lfstmedia.com:11
4fv1_5.html?domain=cdn.lfstmedia.com:11 Blocked a frame with origin "http://cdn.lfstmedia.com" from accessing a frame with origin "http://agar.io". Protocols, domains, and ports must match.

**Comment by abalabahaha** [comment]
Latest version of Opera, latest version of TamperMonkey, latest version of bot, no issues.

**Comment by the133448** [comment]
Fixed by reseeting TamperMonkey, must of not been the latest version
