### ISSUE TITLE
Ignore small balls abrove a certain score

### ISSUE THREAD

**Issue by Quasardian** [Apostolique/Agar.io-bot#119]
after a sertain score about 150 I think, you won't increase in size
after that score small balls should to be ignored

**Comment by Apostolique** [comment]
I'm pretty sure that's wrong and small balls always make you grow.

**Comment by Gjum** [comment]
You always grow from food. But as you get larger, you shrink faster than you can regain mass from food.

Also, when you get larger you see more cells, so efficient food collection can become more resource intensive. This means ignoring food completely when large could also take significantly less CPU cycles.

**Comment by Apostolique** [comment]
Right now, it's already setup to ignore small food when no one worthy is around.

**Comment by Quasardian** [comment]
yes you're right my bad, it should just be ignored a bit more when you grow larger
