### ISSUE TITLE
Chat system

### ISSUE THREAD

**Issue by DarkN3ss61** [Apostolique/Agar.io-bot#12]
I think it could be a good idea to implement a chat system. (I could also host the chat server if needed).
![image](https://cloud.githubusercontent.com/assets/4393979/7604718/0a0ae2e2-f99b-11e4-9a56-f2c7ba452551.png)
so bottom left there could be a chat box so users can chat to each other, and also be able to have this to be able to be toggled

**Comment by Apostolique** [comment]
For a chat system to work with the people playing with you, you would need to have enough people using the script at the same time. You would also need a way to identify which room you are currently connected to.

It could be an interesting idea, but it's out of the scope of this current project.
