### ISSUE TITLE
Running strait away from danger

### ISSUE THREAD

**Issue by Quasardian** [Apostolique/Agar.io-bot#120]
when the bot encounters danger it runs strait away from it.
it could be changed to run away in a circle towards the next objective
this should also stop some bouncing around

**Comment by Apostolique** [comment]
Sounds like a pretty neat idea. I'll have to think more about it. The old version did something very similar to that.

**Comment by Quasardian** [comment]
:D 
you're actualy pretty active on here, about your code, great.
hope you are able to write such a code

**Comment by Apostolique** [comment]
There are times in the day where I am more active.

**Comment by Apostolique** [comment]
If you check the beta, this has been implemented.
