### ISSUE TITLE
Green spikey death balls

### ISSUE THREAD

**Issue by Quasardian** [Apostolique/Agar.io-bot#121]
when you're small the green spikey death balls should be given less priority from running away

**Comment by Apostolique** [comment]
If you're big enough that a spikey death ball can pop you, it hurts you just the same as anyone else. For now it makes sense to run away from it.

Later, I'll change the code to make them an obstacle. This will allow the bot to maneuver around them without running into them. The same thing can be done for enemies that can't split on me.

**Comment by Quasardian** [comment]
sounds great.

it was only when you're small enough that it would not be worthy enough for big ones to should mass to kill you a "much smaller ball"

**Comment by SpenserJ** [comment]
@Apostolique I've started on some of the work on this, and think I have it most of the way to requiring less distance between a blob and a virus. Do you mind if I refactor some of the `findDestination()` and `getAllThreats()` functions to differentiate between viruses and players more easily?

**Comment by Apostolique** [comment]
I used to have a function that was called getAllViruses() then I merged it in getAllThreats().

You can separate them again if you want.

interNodes[element].d is the property that will tell you if something is a virus. d is a boolean value.

**Comment by SpenserJ** [comment]
Ah, I had noticed that `interNodes[element].W` was only set to `1` if it was a virus. I'll take a look at everything for `.d` and see if that simplifies my code.

**Comment by Apostolique** [comment]
.w is just the last time it was drawn.

**Comment by SpenserJ** [comment]
`.W` (uppercase) is `0` or `1`, and seems to only be `1` for viruses. The timestamp was pretty obvious on (lower) `.w`

**Comment by Apostolique** [comment]
Latest version handles this.
