### ISSUE TITLE
Fleeing

### ISSUE THREAD

**Issue by Quasardian** [Apostolique/Agar.io-bot#123]
when you're surrounded the bot should try to flee CLOSER(not into) to the lowest treat and to the next objective.
even if splitting of the smallest treat will kill you or not(better than being surrounded and killed)

**Comment by Apostolique** [comment]
When completely surrounded, in some cases, you want to be perfectly in the middle of them, in other cases, you can escape by going right in between. There different things that can be done depending on what is going on.

**Comment by lilezek** [comment]
@Quasardian In some other cases it would be useful to hid inside a virus. There are so many cases to reduce them to a one unique solution.

**Comment by Quasardian** [comment]
@lilezek fun idea but it's would only be if your very small, and being surrounded by ones that can explode by the size of the virus
if not and can be eaten inside the virus you would need to flee

**Comment by lilezek** [comment]
@Quasardian I just was pointing that there is too many options to reduce them to one quick and fast solution.
