### ISSUE TITLE
Bot does not work in Google Chrome using TamperMonkey

### ISSUE THREAD

**Issue by azhang66** [Apostolique/Agar.io-bot#13]
It seems like the script does not work with Google Chrome using TamperMonkey. The script is loaded, but it does not appear to do anything.

**Comment by JBoughter** [comment]
@Apostolique is aware of this, he has noted that there is something Chrome blocks that doesn't make it work, but the bot needs it to work. This is why it says to install in Firefox.

**Comment by Apostolique** [comment]
It's because for the bot to work, the script needs to be started before the page actually loads. This doesn't get done in Chrome.

**Comment by azhang66** [comment]
@Apostolique Would this be possible via an extension? Firefox does not support hardware acceleration on Linux and it lags like crazy when I use Firefox (it runs silky smooth on Chrome)

**Comment by Apostolique** [comment]
I saw other bots working on Chrome. My loader is specifically made for Greasemonkey, that's why it doesn't work in Tampermonkey.

**Comment by azhang66** [comment]
@Apostolique thank you for your prompt response. Do you know that names of the bots?

Thanks

**Comment by Apostolique** [comment]
One would be https://www.youtube.com/channel/UCiDacU_-2-YKzQUzr2ExlHw

**Comment by DarkN3ss61** [comment]
@Apostolique your welcome :P

**Comment by Apostolique** [comment]
New version now works in Chrome.

**Comment by azhang66** [comment]
@Apostolique Thanks!!

**Comment by adamfire** [comment]
Does it work with extension agario extension 2?

I installed tamper monkey and I can't run that on chrome.

2015-05-20 7:12 GMT+02:00 A. Zhang <notifications@github.com>:

**Comment by GusToughSon** [comment]
It does now!

**Comment by adamfire** [comment]
absynt@yandex.com sent you an invitation to join MEGA.\n\n";

--- Message from user: ---
Hello, join me on MEGA and get access to encrypted storage and
communication. Get 50 GB free!
---

Please create your free MEGA account by clicking on the following
link:\n\n";
https://mega.nz/#newsignupcmVwbHkrMDBiZTVkOGRmNjQ5MWJmYzZiYzU2NGU4NDBlZWMzOWJmYTRjMTRhNDQ4MWIxNjg5OTJjZjAwMDAwMDAxMTE3M2Q5YzA5MmExNjljZTA0ODliZGNkQHJlcGx5LmdpdGh1Yi5jb20f9PnpCUMgqw

Best regards,

Team MEGA
