### ISSUE TITLE
Connection issues when using Chrome, blocking launcher?

### ISSUE THREAD

**Issue by wvanbreukelen** [Apostolique/Agar.io-bot#132]
Hi there, I tried to run the bot in Chrome with Tampermonkey, but when I load agario a server connectivity error rises. I did try to reinstall Chrome, but it is not working.

**Comment by Sanjo** [comment]
There was a new game update. So the code is broken right now I think,

**Comment by wvanbreukelen** [comment]
@Sanjo Did the developers did some detection when connecting to the socket?

**Comment by Apostolique** [comment]
I'll fix that later. Too tired right now.

**Comment by wvanbreukelen** [comment]
@Apostolique Ok tnx, that will be great :)

**Comment by Apostolique** [comment]
Gjum made a fix.
