### ISSUE TITLE
Bug with Chrome 

### ISSUE THREAD

**Issue by xHalley** [Apostolique/Agar.io-bot#133]
Hello, when I go on Agar.io the screen remains white with squares and appear only the information of the bots, but removing the bot agar.io works. How to solve?

**Comment by Apostolique** [comment]
You'll need to wait until I update the bot for the new Agar version.

**Comment by microDX** [comment]
Ok just try to make it work ;)

**Comment by xHalley** [comment]
Ok, thanks.

**Comment by microDX** [comment]
No problem just keep up the good work m8 XD

**Comment by Apostolique** [comment]
Gjum made a fix.

**Comment by microDX** [comment]
NICE MAN!
