### ISSUE TITLE
agar.io was updated, bot broke

### ISSUE THREAD

**Issue by DarkN3ss61** [Apostolique/Agar.io-bot#135]
The bot needs to be updated now since agar,io was and now it is broken

**Comment by Gjum** [comment]
Does #134 work?

**Comment by DarkN3ss61** [comment]
Nope

**Comment by DarkN3ss61** [comment]
YES I will update the page http://jlynx.net/bot/

**Comment by DarkN3ss61** [comment]
Still leaving this open so the original can be updated

**Comment by abalabahaha** [comment]
Shouldn't you give credit to the author?

**Comment by DarkN3ss61** [comment]
What do you mean?
![image](https://cloud.githubusercontent.com/assets/4393979/8269604/2147291a-1805-11e5-9901-a5e9a5eb19f8.png)

**Comment by Apostolique** [comment]
Gjum made a fix.
