### ISSUE TITLE
Bot only takes into account one blob when split

### ISSUE THREAD

**Issue by yayes2** [Apostolique/Agar.io-bot#137]
When the bot is split, it only focuses on pathfinding one blob to safety. I'm not sure how this would work but the bot could possibly do pathfinding for every blob then average the results to find where it should go. It could also treat the entire collection of blobs as one blob and perform the pathfinding on that large mass.

**Comment by Apostolique** [comment]
I will indeed be handling each blob separately. How I use the data after will need to be figured out. You can't simply merge the data.

If you threat the entire collection as a single blob, you'll end up with very weird results as blobs can be very far apart from each others.

**Comment by ErmiyaEskandary** [comment]
https://github.com/Apostolique/Agar.io-bot/blob/master/bot.user.js#L894 It's easier to track a single one.
