### ISSUE TITLE
Console to show bot's status

### ISSUE THREAD

**Issue by JBoughter** [Apostolique/Agar.io-bot#14]
**Enhancement**

I thought there should maybe be a toggle showing what the bot's current tasks are, such as "Currently finding food" "Chasing prey" "Escaping threat" "In manual control", that kinda thing.

Since the bot is a little simplistic regarding what it has to do, there shouldn't be too many things required for the console other than to actually make a box showing the console.

**Comment by Apostolique** [comment]
I can make a toggle for all the debugging strings.

**Comment by phadeb** [comment]
Yes that would be great. I concurr.
