### ISSUE TITLE
Doesn't connect

### ISSUE THREAD

**Issue by ajh103** [Apostolique/Agar.io-bot#142]
Loops on attempting to connect...

**Comment by Apostolique** [comment]
After a while it should connect, I didn't check yet why it doesn't connect on first try.

**Comment by ajh103** [comment]
Five minutes and still looping strong. Have updated scripts, tried on both firefox/chrome, same results... Just connecting loop.

**Comment by Apostolique** [comment]
I think I fixed it? Update Launcher.

**Comment by voviks21** [comment]
looping angain (

**Comment by Apostolique** [comment]
I didn't change the version number, but if you update the launcher, it should be fixed.

**Comment by voviks21** [comment]
Thanks a lot for so fast supporting!
What is ver num and how do you get it?

**Comment by Apostolique** [comment]
The version number is just a number I write in the source file. When I work on the code, I increment that number. It's a way to quickly know if you have the latest version.

Since I didn't increment the number after fixing this, you can't really know if you have latest version or not.
