### ISSUE TITLE
Snip To Add

### ISSUE THREAD

**Issue by DarkN3ss61** [Apostolique/Agar.io-bot#143]
To Add
* Usernames
* Top Score (Ignoring if bot was turned off)
* Average Score (Ignoring if bot was turned off)
* Top Time (Ignoring if bot was turned off)
* Average Time (Ignoring if bot was turned off)
* Server
* Bot Version

**Comment by DarkN3ss61** [comment]
Updated List

**Comment by ErmiyaEskandary** [comment]
Most added. Some might be implemented later.
