### ISSUE TITLE
More Stats + Save stats between sessions

### ISSUE THREAD

**Issue by Parakoopa** [Apostolique/Agar.io-bot#145]
It would be useful to see the number of attempt/live the bot is currently running. 

Also it would be great if the bot could store bestTime and sessionScore and load them again if it get's reloaded.
The best thing would be if the bot could write all statistics to a file or something like that, so they could be evaluated.

**Comment by Gjum** [comment]
Writing to a file in JS cross-browser is hard. Something like this would better be done in [Local Storage](https://en.wikipedia.org/wiki/Web_storage).

**Comment by Apostolique** [comment]
Right now, you can go in the console and write: **best(500, 60)** where 500 is sessionScore and 60 is bestTime.

It sounds nice to save that, but as soon as you take manual controls, those stats become useless. Also if you get a really good run, everything else becomes ignored as it will be worst than that good run. So it's a kind of compromise between seeing the best score, and seeing to current "local" best score if that makes sense.

**Comment by DarkN3ss61** [comment]
Added the death feature so it counts the deaths you have had
