### ISSUE TITLE
Avoidance Oversize

### ISSUE THREAD

**Issue by wes2000** [Apostolique/Agar.io-bot#15]
There seems to be a point where an enemies red avoidance triangle becomes the entire size of the screen (happens a lot when you are near a large enemy and around 150 in size) and it will get stuck in avoiding these triangles even though there might not be a large enemy even close. This might be to account for split distance, but it is way way to far in a lot of cases and really can mess up the bot when you get in the middle of 2-3 of these.

**Comment by phadeb** [comment]
Yes, I think it's possible to  avoid that by creating a "threat model" that determines based on different factors, the treat  that different cells are having towards  us, and thus reproportioning their triangles.

Maybe having  a database of how agressive they have been in the past, etc.

**Comment by Apostolique** [comment]
New version will fix that.

**Comment by phadeb** [comment]
Trying to wonder why you bulk it and won't  implement small frequent changes so that we could test as soon as each feature goes out ?

**Comment by Apostolique** [comment]
You can check the beta branch for that. https://github.com/Apostolique/Agar.io-bot/tree/beta
