### ISSUE TITLE
Minimizing the window

### ISSUE THREAD

**Issue by Jackster35** [Apostolique/Agar.io-bot#154]
Do you think there will ever be a fix for tabbed windows or minimizing the window? I'm sure you know Javascript stops running when the tab is switched or window is minimized. I'm not sure if this is chrome or tamper monkey but do you think there will ever be a fix to such issue?

Kind regards,
Jack

**Comment by AlphaT3ch** [comment]
Hello Jack,
      I'm not a developer of the bot, but just a fellow user like you. I'm on Windows 8.1 running Chrome and it says running in the background perfectly fine for me. I am using the default settings so I'm not really sure though...

King (maybe kind, lol) regards,
Jeff

**Comment by Jackster35** [comment]
Hi Jeff,
Have you tried running multiple instances in different tabs? Give that a try and let me know if it still works :)

Kind regards,
Mr. Incorrect

**Comment by SpenserJ** [comment]
Last night I was running four copies of the bot, and had each taking up a quarter of the screen, and they all ran quite well. However it does seem to reduce the responsiveness of the bot when the window is covered by something else (or minimized), and a quick search pulls up a change [limiting background tab's timers to one per second](https://codereview.chromium.org/6577021). As long as some of the game is visible on the screen, it should allow the bot to continue working normally.

**Comment by Apostolique** [comment]
I'm pretty sure the only way I could fix this would be by porting the bot to the other Agar clients. I could rewrite the code to be run in Python instead. It's not likely that I'll do this though.
