### ISSUE TITLE
Bot Goes into Larger cells

### ISSUE THREAD

**Issue by meamme** [Apostolique/Agar.io-bot#157]
Sometimes when it is easily able to get out of a situation, the bot makes the cell go into a larger one, even though it makes no sense and should be able to get out no problem, but it just goes straight into the larger cell.

**Comment by Apostolique** [comment]
It's not that it goes into the enemy cells, it's that when it can't find anywhere to go, it simply freezes in place, or goes to the last location where it tried to go to.

**Comment by meamme** [comment]
Thank you for clearing it up for me :)

Thanks for being so active on this project by the way
