### ISSUE TITLE
Idea for me to implement 

### ISSUE THREAD

**Issue by DarkN3ss61** [Apostolique/Agar.io-bot#164]
Donators
- Change font
- Change color
- Change text size (With max and min)

Accounts controlled with a control panel on jLynx or something

**Comment by Driftyknight** [comment]
Can you make it so that it dosent just start automatically so you can change pregame settings?

**Comment by Driftyknight** [comment]
I can understand if you don't want to do this one but could you maby make it compatible with the evergreen mod
