### ISSUE TITLE
Bot Doesn't do Anything

### ISSUE THREAD

**Issue by Viliusx** [Apostolique/Agar.io-bot#166]
The Bot doesn't do anything - just stands in one spot, nor runs away from enemies, nor eats food, nor eats smaller blobs, nothing - just standing when I don't have the tab open on my Chrome browser. If it's not viewable on my Chrome browser (on another Chrome window or the tab open) it just doesn't do anything. However, when I open the window the bot instantly starts working.

Only @Apostolique can reply.

**Comment by Apostolique** [comment]
I believe I found a way to fix that. I'll update the script with the change today or tomorrow as I don't have time right now.

**Comment by Apostolique** [comment]
For now the solution to this is to keep Agar in it's own window so that you don't have to switch tab when you do your other stuff.
