### ISSUE TITLE
Can i stream this on twitch

### ISSUE THREAD

**Issue by aler360** [Apostolique/Agar.io-bot#175]
This is NOT an issue I was just wondering if i can stream your bot on http://twitch.tv . i want to see if people would watch a bot play http://agar.io and if it will be like the twitchplayspokemon thing. I would like this GitHub repository in the stream and give you credit for the bot. Sorry for posting this in the issue section but i couldn't find another place to contact you.

**Comment by Apostolique** [comment]
Other people are already doing so. Feel free to stream it but I don't know what is the stance that Twitch has towards bot streaming.

**Comment by aler360** [comment]
Thanks just wanted to make sure with the maker.
