### ISSUE TITLE
So this happened... 

### ISSUE THREAD

**Issue by DarkN3ss61** [Apostolique/Agar.io-bot#179]
Yeah... 
![Image of bot](http://i.imgur.com/6tnORZX.png)
The bot running on Android

**Comment by DarkN3ss61** [comment]
https://www.youtube.com/watch?v=x2-DFRnEFBU

**Comment by Apostolique** [comment]
That's pretty amazing!

**Comment by DarkN3ss61** [comment]
I made a video on it just because it amused me haha and I added another section to the website for Android

**Comment by nickrul** [comment]
well my wont wrok it wont do nothing i cant see the lines or my cell

**Comment by alcoholithm** [comment]
awesome!!

**Comment by DarkN3ss61** [comment]
@nickrul Once you load up agar.io tap the tamper monkey incon, then go back and refresh thae apge and it should work :)
