### ISSUE TITLE
Team Mode

### ISSUE THREAD

**Issue by phadeb** [Apostolique/Agar.io-bot#18]
Implement team  mode : 

- Don't try to eat teammates
- Feed teammates if they are followed by an enemy that has a slightly larger size to counter effect
- Gang up strategy to minimize the enemies escape

**Comment by Apostolique** [comment]
I want to add that, but didn't have much time to look into it. So far, it doesn't seem like there is any 'real' way to know who is a teammate from the code. Looks like I'll have to use the color directly to find who is with who. Kinda of annoying that the same color can have different shades though.

**Comment by phadeb** [comment]
What function does the game use to generate the shade colors ? Maybe you could use it their function directly to compute a range of hexadecimal colors, there are only 3 ranges possible?

Also maybe you could add a manual picking of the color  in case auto detecting is too difficult.

**Comment by GhostGuy283** [comment]
the bot cant see boarders.. i hope you can fix that!
