### ISSUE TITLE
Cannot Connect [Important]

### ISSUE THREAD

**Issue by DarkN3ss61** [Apostolique/Agar.io-bot#184]
All users are complaining that it isnt working (although it is for me)
This is a comment from one of them.
"i do the exact same steps as showing in the vid but "Connecting
If you cannot connect to the servers, check if you have some anti virus or firewall blocking the connection." 
Is still showing up and i can't play"

I have lots of users with the same problem and i'm not sure what it is

**Comment by Apostolique** [comment]
It's likely that the launcher is outdated.

**Comment by DarkN3ss61** [comment]
Shouldn't be, they I got all the messages last night, and also the old launcher still works so that shouldn't make a difference

**Comment by ctrlaltchris** [comment]
Yeah, not working,

**Comment by Apostolique** [comment]
This should be fixed.
