### ISSUE TITLE
Code Obfuscation?

### ISSUE THREAD

**Issue by AnnanFay** [Apostolique/Agar.io-bot#186]
Why are large parts of the code obfuscated or needlessly complicated? Take for example this code:

    var a;
    if (ua()) {
      a = T - p / 2;
      var b = U - q / 2;
      64 > a * a + b * b || 0.01 > Math.abs(La - X) && 0.01 > Math.abs(Ma - Y) || (La = X, Ma = Y, a = N(21), a.setUint8(0, 16), a.setFloat64(1, X, !0), a.setFloat64(9, Y, !0), a.setUint32(17, 0, !0), O(a))
    }

It is seriously painful to comprehend or edit the code.

**Comment by Apostolique** [comment]
Obfuscated code means that it's not code that I've written. To make the launcher, I start with the following base code: http://pastebin.com/V2cfU4VY

**Comment by AnnanFay** [comment]
Okay, that makes sense. Where did that code come from? Is it just a copy of the official game's code or something the uploader created?

**Comment by Apostolique** [comment]
It's the official client code.
