### ISSUE TITLE
Not an issue but

### ISSUE THREAD

**Issue by KickingRG** [Apostolique/Agar.io-bot#189]
http://ragegaming.net/Screenshots/Screenshot12-06-13-2015.png

Not bad at all.

**Comment by Apostolique** [comment]
Quite nice! Did you have to help it? Or it got that big on it's own?

**Comment by KickingRG** [comment]
I went to make some food and came back and it was like that. No help needed

**Comment by KickingRG** [comment]
http://ragegaming.net/Screenshots/Screenshot18-14-20-2015.png

**Comment by KickingRG** [comment]
http://ragegaming.net/Screenshots/Screenshot10-22-08-2015.png

**Comment by Apostolique** [comment]
I think that's the highest score that bot has ever reached..

**Comment by KickingRG** [comment]
It happened while I was asleep.

**Comment by KickingRG** [comment]
http://ragegaming.net/Screenshots/2015-07-11_12-38-27.mp4
