### ISSUE TITLE
Play a sound

### ISSUE THREAD

**Issue by phadeb** [Apostolique/Agar.io-bot#19]
Play a sound when something very important happens, example : the prediction system detects that the probability of death is growing too fast (escapes routes and possibilities diminishing, losing mass too fast, surrounded by enemies / cornered)

**Comment by JBoughter** [comment]
Also maybe a notification to inform you that you've placed a spot on the leaderboard/changed rank on the leaderboard/lost placing on the leaderboard.

**Comment by Apostolique** [comment]
Could be done with a sound toggle. I'll put that on my TODO list.

**Comment by Apostolique** [comment]
Actually, I'd rather not add sounds after giving this more thoughts.

**Comment by phadeb** [comment]
why is that ?
if it's a toggle default off though

**Comment by Apostolique** [comment]
I can probably keep it as a low priority thing to add later, but it's a bit more work than it would seem as you don't want the sound to be spammed.
