### ISSUE TITLE
Level points (facebook) not adding 

### ISSUE THREAD

**Issue by coolemiel** [Apostolique/Agar.io-bot#190]
When connected to facebook there is a level system. When using the bot there aren't any points added.

Maybe this is because there is no respawn delay so it can't count it up?

Would like to see this fixed. Thank you.

**Comment by Apostolique** [comment]
It's because the Launcher is outdated. I didn't have much time to work on the bot in the past week. I believe I'll be able to update everything tomorrow. I also want to add splitting in.

**Comment by coolemiel** [comment]
Yeah splitting would be nice but i think fb is cooler ;-) 

But nothing to complain! You are doing GREAT! 

ps. Where is the donate button?

**Comment by Apostolique** [comment]
It's hidden on my stream page: https://www.twitchalerts.com/donate/apostolique

**Comment by coolemiel** [comment]
Will you do a live stream on making the update? :D

**Comment by Apostolique** [comment]
I usually always stream when I work on the bot. Unless what I'm doing only takes a few minutes and I don't have much time to stream.

**Comment by coolemiel** [comment]
Did you fix the point system?

**Comment by Apostolique** [comment]
Yep :) Not sure if I pushed the changes from the stream yet, but I'll be pushing them soon enough.
