### ISSUE TITLE
I dont get xp when the bot got killed

### ISSUE THREAD

**Issue by dave90dave** [Apostolique/Agar.io-bot#191]
can you please add a feature so the xp is added to your account too?
- i cant get the xp when the bot is killed by a other...
i hope you can add this!!!
- i am also missing a chunk of code, this problem is that in team mode the bot is trying to attack other teammates...
Thank you very much :D
- and maybe, can you add a auto split function so the bot is splitting the globes if needed?
i hope to hear from you soon! 
Fantastic bot :D

**Comment by Apostolique** [comment]
I've been really busy during the past week. Tomorrow I should have more time to catch up on everything I've been planning to do.

**Comment by dave90dave** [comment]
that's okay, its already a fantastic bot... :D :+1:

**Comment by Apostolique** [comment]
If you haven't already, get latest Launcher.
