### ISSUE TITLE
Buggy connection with the latest FaceBook update

### ISSUE THREAD

**Issue by DarkN3ss61** [Apostolique/Agar.io-bot#195]
it seems to be a bit buggy because of the facebook update to agar.io, sometimes it just wont work at all and you need to refresh about 20 times

**Comment by coolemiel** [comment]
I am playing with facebook too but i am not having this problem. Have you tried to re-install the scripts?

and I always first log in to fb and then start the scripts then refresh.

**Comment by DarkN3ss61** [comment]
@coolemiel  Like I said, its buggy, sometimes it works and sometimes it doesn't

**Comment by coolemiel** [comment]
Well that is just weird but there is coming a update in these days so i think this will be fixed.
