### ISSUE TITLE
not a issue but a idea - speed hack

### ISSUE THREAD

**Issue by dave90dave** [Apostolique/Agar.io-bot#197]
hello!

is there a possibility to add a speed hack in the bot?
it seems to me really cool if it possible to add this addition too

i am waiting for a reply

regards

Dave

**Comment by FliegendeWurst** [comment]
this is a bot, not a speed hack

**Comment by dave90dave** [comment]
it was just a suggestion, i only wanted to know: "is it possible", but never mind...

**Comment by Apostolique** [comment]
It's not possible as the game is running on a server which we don't have access to.
