### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by ShayBox** [Apostolique/Agar.io-bot#198]
After the latest update of scripts, the launcher seems to work, but the bots themself dont load, the default bot is human and there are no others in the list, i have both beta and stable installed but are not working.

**Comment by Apostolique** [comment]
You'll need to make sure that the scripts are enabled in your Violentmonkey. Also check for which version is currently installed.

**Comment by ShayBox** [comment]
Latest version, and they are running 
![image](https://cloud.githubusercontent.com/assets/9505196/8636828/8537bb1c-2843-11e5-8912-557c09048e76.png)

**Comment by Apostolique** [comment]
In Agar.io, can you press F12, go to console, and show my what is written at the top? It should show that the launcher gets loaded. (And perhaps the bots too.)

**Comment by ShayBox** [comment]
![image](https://cloud.githubusercontent.com/assets/9505196/8636839/41c305f2-2844-11e5-8d72-6fbf28501639.png)

**Comment by Apostolique** [comment]
It appears that Violentmonkey doesn't support the current version of the bot. You'll need to get Tampermonkey instead for now.

**Comment by ShayBox** [comment]
tampermonkey doesnt support Maxthon browser, and chrome, firefox, and opera run slower than maxthon

**Comment by Apostolique** [comment]
In that case, get the bot here: https://gist.github.com/Apostolique/6a4fa9c3d6bef5c0eefb

**Comment by ShayBox** [comment]
the reason they dont load is you need to define GM_info, 
![image](https://cloud.githubusercontent.com/assets/9505196/8636882/0a7c806c-2846-11e5-8d45-02b19696478e.png)

**Comment by Apostolique** [comment]
Yep. Also, from that link I gave you above, make sure to get both files.
