### ISSUE TITLE
Experimental

### ISSUE THREAD

**Issue by ShayBox** [Apostolique/Agar.io-bot#199]
Every time i get big, i just get eaten by a red virus, you need to make it repel them like green ones

**Comment by KickingRG** [comment]
http://ragegaming.net/Screenshots/Screenshot10-22-08-2015.png

**Comment by ShayBox** [comment]
whats that?

**Comment by KickingRG** [comment]
It works for me

**Comment by Apostolique** [comment]
I can do something about it today.

**Comment by ShayBox** [comment]
im using violent monkey on maxthon, i had to use 2 weeks ago scripts for it to work

**Comment by Apostolique** [comment]
Did you try the beta? https://github.com/Apostolique/Agar.io-bot/blob/master/beta.user.js

**Comment by ShayBox** [comment]
yep, i have both installed, and the launcher

**Comment by Apostolique** [comment]
What's your problem then?

**Comment by ShayBox** [comment]
i cant use any version past a few weeks ago, im stuck with an outdated version forever

**Comment by ShayBox** [comment]
Ohh, sorry this is the wrong chat for this, i have 2 issues open and got them confused, whenever i go in experimental mode and use beta or stable it doesnt repel me from red viruses, just goes right into them like they dont exist, then i get eaten

**Comment by Apostolique** [comment]
I just tested and with beta version 3.46, the bot doesn't go into the red viruses.
