### ISSUE TITLE
Glitchy Bot

### ISSUE THREAD

**Issue by arvoim** [Apostolique/Agar.io-bot#20]
Yesterday the bot was running extremely smooth, even running the bot in 10 tabs on Firefox. Today, even just 1 tab running the bot (with no apps open) and the bot is very jittery. The bot will pause for several seconds before making a move. Going in manual mode and trying to move around, same issue. Seems like a huge lag. Not sure if its the bot or me or the connection. Any ideas?

**Comment by Apostolique** [comment]
I didn't change anything in the past week. It's probably you since I don't get any lag.

**Comment by OverlordQ** [comment]
It's the game itself. Even w/o bot occasionally it locks up.
