### ISSUE TITLE
Mass viewer for other cells

### ISSUE THREAD

**Issue by Nitrogen-Dioxide** [Apostolique/Agar.io-bot#201]
Enable mass view all the time, making us know if we can split to eat the other cell.

**Comment by Gjum** [comment]
An interesting way to do this is to show the mass percentage of other blobs relative to your own blob, like [@RealDebugMonkey](https://github.com/RealDebugMonkey/ZeachCobbler) does it.

For example: you have 200 mass, blob A has 300 mass and blob C has 100 mass.
Blob A would then be labeled with `150%` and blob C with `50%`.

This works great when you control a single blob, but I am not sure how this could be applied when you control multiple blobs (after splitting).

**Comment by Nitrogen-Dioxide** [comment]
Yea use % is better. Well, the best way is to do a average, if you have 3 blobs with average 100, and the other blob have 220 well... you must run xD.

**Comment by Gjum** [comment]
Average becomes misleading very quickly. Max/Min is better in most cases.

**Comment by Apostolique** [comment]
Percentage is useless and doesn't scale when you are split. Showing the real mass value is fine, but is useless for the bot. The only reason I activate that once in a while is to help with debugging otherwise I find that to give unfair advantage for a human player and the goal of the bot isn't to give unfair advantage.

**Comment by Nitrogen-Dioxide** [comment]
@Apostolique Oh now I understand your point.

**Comment by Creeperman8362** [comment]
@Apostolique why cant we just display their mass number on their cell? simple as that

**Comment by Gjum** [comment]
@Creeperman8362 because Apostolique finds it unfair.
Feel free to fork the project and change it for yourself. ;)
