### ISSUE TITLE
Display danger via color

### ISSUE THREAD

**Issue by Nitrogen-Dioxide** [Apostolique/Agar.io-bot#202]
Display blob danger/edibility via color
Red - it can split and eat you
Orange - it can eat you, but not if it splits
Yellow - Same size as you
Green - you can eat it, but not if you split
Purple - you can split and still eat it

**Comment by Apostolique** [comment]
Yellow is useless, otherwise I'll get around to green and purple when I start working on the actual splitting.

**Comment by Gjum** [comment]
Duplicate of #247
