### ISSUE TITLE
Bot gets too close too viruses

### ISSUE THREAD

**Issue by chris13524** [Apostolique/Agar.io-bot#204]
In my experience, there are two reasons that the bot dies. It gets too close to a player. And the other one, it gets too close to viruses. It gets so close that if it moved a pixel closer it would explode. Sometimes it is so close that something happens, I don't know, but it explodes. There needs to be a little higher distance allowed for viruses.

**Comment by Apostolique** [comment]
If you try the beta, it won't do that.
