### ISSUE TITLE
WTF is loader

### ISSUE THREAD

**Issue by DarkN3ss61** [Apostolique/Agar.io-bot#207]
wtf is the loader scrip and also the updater wont work as its checking for updates with the launcher file

**Comment by Piehthyte** [comment]
The loader script by the looks of the code seems to just be an auto updater.

**Comment by DarkN3ss61** [comment]
Yeah I realized that, since I closed this issue

**Comment by Apostolique** [comment]
If you have the loader, you don't need anything else.
