### ISSUE TITLE
Loader Script

### ISSUE THREAD

**Issue by DarkN3ss61** [Apostolique/Agar.io-bot#208]
@Apostolique should I add the Loader Script to the site?

**Comment by Piehthyte** [comment]
The loader script by the looks of the code seems to just be an auto updater.
It also says that it is an autoupdater :p ex: @description Grabs latest versions of the bot scripts automatically.

function update(prefix, name, url) {
    window.jQuery(document.body).prepend("<div id='" + prefix + "Dialog' style='position: absolute; left: 0px; right: 0px; top: 0px; bottom: 0px; z-index: 100; display: none;'>");
    window.jQuery('#' + prefix + 'Dialog').append("<div id='" + prefix + "Message' style='width: 350px; background-color: #FFFFFF; margin: 100px auto; border-radius: 15px; padding: 5px 15px 5px 15px;'>");
    window.jQuery('#' + prefix + 'Message').append("<h2>UPDATE TIME!!!</h2>");
    window.jQuery('#' + prefix + 'Message').append("<p>Grab the update for: <a id='" + prefix + "Link' href='" + url + "' target=\"_blank\">" + name + "</a></p>");
    window.jQuery('#' + prefix + 'Link').on('click', function() {
        window.jQuery("#" + prefix + "Dialog").hide();
        window.jQuery("#" + prefix + "Dialog").remove();
    });
    window.jQuery("#" + prefix + "Dialog").show();
}

window.jQuery.get('https://raw.githubusercontent.com/Apostolique/Agar.io-bot/master/loader.user.js?' + Math.floor((Math.random() * 1000000) + 1), function(data) {
    var latestVersion = data.replace(/(\r\n|\n|\r)/gm, "");
    latestVersion = latestVersion.substring(latestVersion.indexOf("// @version") + 11, latestVersion.indexOf("// @grant"));

    latestVersion = parseFloat(latestVersion + 0.0000);
    var myVersion = parseFloat(aposLoaderVersion + 0.0000);

    if (latestVersion > myVersion) {
        update("aposLoader", "loader.user.js", "https://github.com/Apostolique/Agar.io-bot/blob/master/loader.user.js/");
    }
    console.log('Current loader.user.js Version: ' + myVersion + " on Github: " + latestVersion);
});

**Comment by Apostolique** [comment]
If you don't want to always manually grab the latest versions after an update, you can get the loader instead. It loads the latest versions of both the launcher and the beta bot.

**Comment by DarkN3ss61** [comment]
Yeah, but the question was do you want me to add it to the site?

**Comment by DarkN3ss61** [comment]
Dont worry, I added it because i was board

**Comment by Apostolique** [comment]
That was fast, also looks pretty good.

**Comment by DarkN3ss61** [comment]
@Apostolique  SKYPE NOW!!!!!!
