### ISSUE TITLE
Impressive

### ISSUE THREAD

**Issue by marcocc** [Apostolique/Agar.io-bot#209]
Your bot is so impressive!!  It really helped me get to the leader place!!!

![game no 1](https://cloud.githubusercontent.com/assets/13269592/8664775/525ef684-2a0e-11e5-81a7-15a8f0227fac.PNG)

**Comment by Apostolique** [comment]
That's pretty nice. I guess Terminators aren't so bad after all.

**Comment by marcocc** [comment]
I hope you will add the auto-split feature/ option. It will be a lot better.

**Comment by laxika** [comment]
I had one hit 6k score. Got no screen sadly. :(

**Comment by Apostolique** [comment]
Little sneak peak of what I'll be working on today: ![http://i.imgur.com/x9crfEF.png]

**Comment by KickingRG** [comment]
ragegaming.net/Screenshots/2015-07-11_12-38-27.mp4

**Comment by Apostolique** [comment]
18k eh

**Comment by KickingRG** [comment]
I've showed this numerous amount of times. But it's pretty sweet. 5 hours. Did it while I was asleep.

**Comment by Apostolique** [comment]
If I've seen this before, I probably wasn't looking at those numbers. :D

**Comment by KickingRG** [comment]
xD

**Comment by laxika** [comment]
![Not really? :D](http://s15.postimg.org/b8rfyarwb/notreallyabot.png)
