### ISSUE TITLE
Bot for Opera

### ISSUE THREAD

**Issue by the133448** [Apostolique/Agar.io-bot#21]
Is it possible to create a version to work for ViolentMonkey for Opera broswer?

**Comment by Apostolique** [comment]
I don't use ViolentMonkey myself, but all you need is a way to load the bot's script before the page loads.

**Comment by the133448** [comment]
Sorry I dont know how to do this

**Comment by Apostolique** [comment]
It's likely it doesn't have that option.

**Comment by the133448** [comment]
Hello, here is where the option is. http://i.imgur.com/OxVy3UK.png would you know any bots which would work on opera then?

**Comment by Apostolique** [comment]
I'd want to help more, but as I don't use Opera myself, I can't really support it. Other people have reported they couldn't get it to work in anything else than Firefox. Anyway, Firefox is free, you can even download the portable version if you don't want to install it permanently.

**Comment by the133448** [comment]
I wish I could use Firefox, but my network provider blocks that website, and I use Oper Turbo, to skip through the checks.

**Comment by Apostolique** [comment]
This site works for you? http://portableapps.com/apps/internet/firefox_portable

**Comment by the133448** [comment]
I do have Firefox installed. Just my network doesnt allow me to access the agari.io so ineed to use Operas Turbo mode, which routs all traffic through their server. Thats the reason

**Comment by Apostolique** [comment]
Okay, this new version should work in Opera. It will also work in Chrome and everything else.

**Comment by the133448** [comment]
Thankyou
