### ISSUE TITLE
Click/Scroll bug

### ISSUE THREAD

**Issue by TheCrazyBoy1** [Apostolique/Agar.io-bot#218]
If you click or scroll your mouse, the bot will stop moving and won't respond anymore. It also crash Chrome. it takes around 5 seconds before agar.io close.

**Comment by laxika** [comment]
I have the same problem on all PCs I try the bot. I'm using 43.0.2357.132 m on Win7 on all of the PC's I tired this.

**Comment by dlnetworks** [comment]
fyi: i do not have that issue at all...  on osx using safari or firefox or chrome or opera.

**Comment by Apostolique** [comment]
I'm pretty sure it's only an issue on Chrome and maybe on Opera. I believe I know how to fix this, but don't have the time to work on this yet.
