### ISSUE TITLE
Bot does not merge after splitting and has non-human behaviour

### ISSUE THREAD

**Issue by Buntstift1337** [Apostolique/Agar.io-bot#220]
After Splitting, the multiple blobs should not move independently from each other, as this is not possible to do by a human player and should be considered cheating.
At least, the blobs should always go for the same target, so they can merge again. Otherwise, the bot ends up just splitting into separate bots, kinda like beeing seperate players, and the reason why they split should be to catch another blob, then merge again.

**Comment by laxika** [comment]
Well, this is not a bug but a feature. The bot is written directly to be  able to controll each split cell individually.

**Comment by marcocc** [comment]
I like this when somebody shoots a virus to me. My "NOTREALLYABOT" cells go all over the map.

**Comment by Buntstift1337** [comment]
i like the bot for (hopefully) being better than others. Not by cheating :) if some people like it make an option with cheats or something like that. What about putting a speed hack or invincibility there also? :)

**Comment by Apostolique** [comment]
The creator of the game added the option to control each cells separately so that bots can do that. I wouldn't be surprised if he added a way for human players to be able to control each cell too.
