### ISSUE TITLE
Remember name

### ISSUE THREAD

**Issue by Buntstift1337** [Apostolique/Agar.io-bot#221]
It would be nice if you would store the bots name in a cookie or sth so it remembers the last name set.

At the moment, you have to change it every time you start it, then kill the bot manually cause its autostarting.

**Comment by Apostolique** [comment]
You can also edit the name manually direction in the source code. Search for "NotReallyABot" in launcher.user.js

You can specify any amount of names with a comma separated list:
"name1", "name2", "name3"
