### ISSUE TITLE
Avoiding beeing eaten by split

### ISSUE THREAD

**Issue by Buntstift1337** [Apostolique/Agar.io-bot#222]
Bot should take the size difference betwenn it and other, bigger players into account. Players that are alot bigger usually dont chase smaller ones cause theyre too slow. They also dont waste a split. the bot often gets chased by others only a little bigger, and is so afraid of the super-big ones that he dies, allthough he could most likely touch them safely cause they dont care and wont split.

**Comment by marcocc** [comment]
I believe the bot has already considered this problem. If the other player is much bigger than yours, the run-away-area's radius should not be large.

**Comment by Buntstift1337** [comment]
Is that so? hmm...
maybe the other players direction and speed should be calculated in? For example make the "prohibited area" around others eliptic or in the form of a tear of some sort, pointing in the direction it is moving? Ok too many ideas. :D

**Comment by NPWR** [comment]
You can implement it man ;)
As you said an elliptic zone around big cells is smart, but personnally I don't know the maths behind ellipses

**Comment by marcocc** [comment]
Maybe other players suddenly change its direction towards you and then you suddenly die?

**Comment by Apostolique** [comment]
Right now, if someone's mass is 10 times more, the bot assumes that that person won't be splitting to catch it. Maybe later I'll tune the 10 down and see if more people try to go for a split.

**Comment by Timtech** [comment]
Ah nice, that really helps out. I do think plain distance should be taken into account though, if you're about to be eaten and must travel into that danger zone of an 8x larger blob to escape.
