### ISSUE TITLE
The bot errors out and "crashes"

### ISSUE THREAD

**Issue by jaw20** [Apostolique/Agar.io-bot#224]
When i try to run the bot in chrome, the bot starts and instead of playing, agar.io stays dimmed, like it was on the name menu, and in console it mentions that it can't call 0 from an undefined variable. the error also calls line 230 of the launcher code.

**Comment by Apostolique** [comment]
Removed all the scripts you have installed, and get those two files:
https://github.com/Apostolique/Agar.io-bot/blob/3c2cf4ebdc71e4b758c5f9244706903f537df831/launcher.user.js
https://github.com/Apostolique/Agar.io-bot/blob/2b07ba5ef69a74799881cb950f02ccbed475a1e6/bot.user.js

**Comment by jaw20** [comment]
It still happened again after uninstalling all scripts and reinstalling yours. This is what the screen looks like when the bot "crashes". 
![image](https://cloud.githubusercontent.com/assets/5055347/8732166/c72c6c14-2bc9-11e5-806f-350e076c290e.png)

This is what the console says when it "crashes".

![image](https://cloud.githubusercontent.com/assets/5055347/8732251/4f111148-2bca-11e5-93ef-8b4717660b15.png)

**Comment by Apostolique** [comment]
If you look at the top of the console. Can you see if the bot is getting loaded? It's hard to solve this without playing with it myself.

**Comment by tescit** [comment]
I had the same problem. Happens with Tampermonkey in Chrome, when the Launcher loads before the bot loads. Go to Tampermonkey and edit the Bot Script and change "Position" in the Settings tab to a number before the launcher.

**Comment by Apostolique** [comment]
I thought I handled that specific case, guess not.

**Comment by jaw20** [comment]
Doing what tescit said above worked. Thank you.

**Comment by Apostolique** [comment]
I found why the order is important, I'll fix it as soon as I have time.

**Comment by ErmiyaEskandary** [comment]
Fixed with the latest commit.
