### ISSUE TITLE
Bot trying to eat blobs it cant

### ISSUE THREAD

**Issue by bluemonster122** [Apostolique/Agar.io-bot#227]
The bot died trying to eat a blob that was too big for it to eat.   It may be fixable?

**Comment by Apostolique** [comment]
I didn't tune the value for what can be eaten perfectly yet. Right now I use 130% as that is the amount that is used for viruses but it's not quite right for eating.

**Comment by bluemonster122** [comment]
ok cool, well its a little high i think... but not by much

**Comment by bluemonster122** [comment]
going to sleep may be a while b4 i respond next if you reply XD

**Comment by Timtech** [comment]
I've noticed rare cases where the bot hovers over a cell it barely can't eat. It seems much more common when at minimal mass.

**Comment by ErmiyaEskandary** [comment]
Since the bot doesn't split, it doesn't have any means to catch up to smaller faster players so it doesn't split anymore. In previous versions, it used to split and be more aggressive but in overall, the current version grows much bigger and lasts much longer.

**Comment by ErmiyaEskandary** [comment]
So it doesn't pursue players anymore. It only eats non moving targets.
