### ISSUE TITLE
Code is obfuscated

### ISSUE THREAD

**Issue by marouanopen** [Apostolique/Agar.io-bot#23]
Please make the code more human readable.

**Comment by Apostolique** [comment]
You can look at the first version that was committed. While the code has changed quite a lot, it can give you a good understanding of what is going on. I can't deobfuscate after every update as it takes too much time. It takes a long time to go through everything and rename stuff without breaking anything.

**Comment by jsumrall** [comment]
Why not write the code in a human readable way, and then obfuscate it at the end, and push both to git.

**Comment by i9w** [comment]
Hey is their any branch or fork or whatever you call it guys, with the zoom out feature working?

**Comment by Apostolique** [comment]
The zoom out thing is pretty easy to do, just look for the line h = (9 * h + a) / 10 and make a hold a bigger value.

**Comment by i9w** [comment]
Here' what I have 

" function Ka() {
    if (0 != l.length) {
      for (var a = 0, b = 0; b < l.length; b++) a += l[b].size;
      a = Math.pow(Math.min(64 / a, 1), 0.4) * Math.max(r / 1080, q / 1920);
      h = (9 * h + a) / 10
    }"

Should I make for(var a=10) ? is that what you meant?

**Comment by Apostolique** [comment]
Right above line h = (9 * h + a) / 10 do something like a += 1000. Play with the numbers to see how it reacts.
