### ISSUE TITLE
Can't Change The Name

### ISSUE THREAD

**Issue by CCTrollz** [Apostolique/Agar.io-bot#230]
I am unable to change the name of the bot.

**Comment by Apostolique** [comment]
Do change the name, you need to press ESC, then type the name you want in the text box and die.

**Comment by CCTrollz** [comment]
Yes, I do that but it still remains the default. 

-CCTrollz

**Comment by Apostolique** [comment]
In that case, can you try opening the terminal and inputting:
```
setNick("Name");
```

**Comment by Code-Bear** [comment]
> Yes, I do that but it still remains the default.

You have to set the name and click "Play" for it to take effect. At which point your name will change on your next game. Or after clicking play you can switch game types to reset your game and change the name faster.
