### ISSUE TITLE
Cell Hunting Suggestion

### ISSUE THREAD

**Issue by Code-Bear** [Apostolique/Agar.io-bot#232]
You could greatly increase the chances of absorbing enemy cells if you would set the attack priority high for cells small enough to absorb with your split mass and make the cell split if the cell is within range of your split travel distance.

*The success rate of catching a cell of nearly equal mass is pretty rare and the bot wastes a lot of resource gathering time. If instead it would chase smaller cells (I believe 30% smaller) and split attack them I think that would greatly increase your chances of of growth and survivability.*

**Comment by ErmiyaEskandary** [comment]
In previous versions, it would split aggressively but in overall, the current one grows much bigger and lasts longer.
