### ISSUE TITLE
Independent Cell AI

### ISSUE THREAD

**Issue by Code-Bear** [Apostolique/Agar.io-bot#233]
As of the latest update it appears you are able to control each cell mass independently, which is great, yet more than half the time the masses end up splitting up and eventually get absorbed or go out of range making you loose the mass. Can you set a proximity range for the cells so they stay grouped better? Also a way to turn on/off the independent cell AI would be great.

**Comment by Linkaan** [comment]
can't you just use follow mouse to regroup the cells?

**Comment by Code-Bear** [comment]
@Linkaan You can but that would highly defeat the purpose of a bot. Currently the disadvantages of independent cell AI greatly outweigh the advantages because every time you get split, either to attack an enemy cell or by a virus, you will more often than not loose a lot of your mass because the individual cells will get absorbed by an enemy; which chances are wouldn't have happened had you been at your full mass.

**Comment by Apostolique** [comment]
The formula for how much time in seconds two cells will take to regroup is as follow:
30 + Combined_Mass * 0.2
I didn't implement this yet. I'll have to experiment with how a cell life time works.

**Comment by Gjum** [comment]
This formula is not accurate for the official servers.

**Comment by Apostolique** [comment]
Do you have the right formula? I got it from http://agar.gcommer.com/index.php?title=Formulas#Time_To_Remerge

**Comment by Gjum** [comment]
I am contributing there regularly and know who found that formula. He said it is correct if you have only 2 cells within a tolerance of +-4 seconds.

**Comment by Apostolique** [comment]
What I'm thinking is that each cell has a birth time. When you split, you are creating a new cell. That cell has a birth time. You can merge back when that cell has been old enough. I was thinking that the formula could tell you when any two cells could merge back.

One way to test if what I'm saying is true is to split. When you can merge back again, split right before you do. You now have 4 cells. The two parent cells should still be able to merge back while the two child cells won't be able to merge back.

**Comment by Gjum** [comment]
Oh, that's interesting.

Did you record test data or just try it out? I'd like to analyze some more data to get exact results, as the formula is not precise enough for my purposes.

btw, missed your edit, Github only notifies on new posts :/

**Comment by Apostolique** [comment]
I simply tried it out. I have an idea about how the formula should look like. I'll try to write it when I have more time.
