### ISSUE TITLE
Doesn't spawn in when on firefox and also ESC doesnt work

### ISSUE THREAD

**Issue by ghost** [Apostolique/Agar.io-bot#238]
As title says.

**Comment by ErmiyaEskandary** [comment]
Could you give us more information please ? Download the scripts again as there have been updates to fix the connection issue and other bugs.

**Comment by Apostolique** [comment]
This is a dead topic.

**Comment by ErmiyaEskandary** [comment]
Then why was it open ? Half of these issues are invalid and outdated.
