### ISSUE TITLE
Buggy wont spawn

### ISSUE THREAD

**Issue by DarkN3ss61** [Apostolique/Agar.io-bot#239]
sometimes it wont spawn and I need to refresh the page a few times before it works, I am having lots of other people reporting the same issue too.

**Comment by Apostolique** [comment]
It's likely the launcher is outdated.

**Comment by DarkN3ss61** [comment]
I'm using the loader

**Comment by Apostolique** [comment]
The loader loads the launcher and the bot for you. That's why you only require the loader alone.

**Comment by DarkN3ss61** [comment]
I know mate, I only have the loader

**Comment by ErmiyaEskandary** [comment]
Download the scripts again. Has it been fixed ?
