### ISSUE TITLE
Bad connecting

### ISSUE THREAD

**Issue by A-T0M** [Apostolique/Agar.io-bot#241]
Once connected, the cell stops moving. It just stays there, even if a bigger cell runs over it.

**Comment by rakibim007** [comment]
guys please help me i dont want this mails -_-

2015-07-20 1:16 GMT+03:00 Anthony Thomas <notifications@github.com>:

**Comment by laxika** [comment]
Unsubscribe. There is a button on the right panel on this page.

**Comment by upspostal** [comment]
I also have this issue. it will be fine one moment then super laggy the next. often the cell will stop, and when i press 'T' to control the bot, it will not let me. i have tested my internet connection that seems fine.

**Comment by A-T0M** [comment]
yea, there's nothing wrong with my internet either, its completely the script. either this script or the launcher is causing it.

**Comment by laxika** [comment]
This happens with me when I try to zoom.

**Comment by coolemiel** [comment]
Hey guys in the next days apostolique will work on a newer version and will try to fix this bugg.

**Comment by A-T0M** [comment]
awesome, thanks!!

**Comment by Apostolique** [comment]
I'm currently moving to a new house and I be able to work on this project until I'm fully settled. My computer and desk stuff aren't setup yet.
