### ISSUE TITLE
Enhancement: Automatic cell splitting and group travel.

### ISSUE THREAD

**Issue by Crayder** [Apostolique/Agar.io-bot#244]
# *Auto cell split*

This would automatically split the cells when they reach 80 or a specified number. There should also be a maximum amount of parts it can be split into. I like this because my cells split up and gather more apart.

# *Group travel*

This would let the groups travel together instead of each cell taking their own path. Sometimes when they span out too much I lag and get glitchy.

**Comment by team12354** [comment]
de best

**Comment by Timtech** [comment]
Auto cell split really shouldn't be that hard to code yourself, and for group travel I recommend just using "follow mouse" to group your squad back together.

**Comment by Drflash55** [comment]
I've heard of the bot having the ability to have each cell take their own path, but for some reason when I split and I leave it on bot, the cells don't take their own path, but instead, cling together so that they can recombine...

Did an update cause the 'group travel' to become a reality?

**Comment by Crayder** [comment]
An agar.io update removed the seperate path ability (and I'm devastated, I loved that ability).

**Comment by Timtech** [comment]
Yeah, I'm also disappointed about that.

**Comment by Drflash55** [comment]
Darn...

**Comment by ErmiyaEskandary** [comment]
It's easier to track a single one - https://github.com/Apostolique/Agar.io-bot/blob/master/bot.user.js#L894. Independent cell control got removed as well.
