### ISSUE TITLE
Start with 10 mass and no XP

### ISSUE THREAD

**Issue by Creeperman8362** [Apostolique/Agar.io-bot#248]
I was using the bot as an XP generator and it stopped spawning me with 37 mass and no longer gives XP

**Comment by laxika** [comment]
Try to refresh? Are you logged in with facebook?

**Comment by Creeperman8362** [comment]
yea i am, and it works without the bot

**Comment by Crayder** [comment]
This is my exact problem is in #249. I would've come here if I seen this issue here.

The XP just froze, won't even budge. When I disable the user script I start earning XP naturally again.

**Comment by laxika** [comment]
Hmm interresting. It works for me. :S

**Comment by Crayder** [comment]
@laxika: What version are you using? I'm using the auto-update userscript.

**Comment by Code-Bear** [comment]
I am having the same issue. Start at size 10, and no exp gains. I am using bot version 3.551 and have attempted to logout and back in with no change. Turn off the bot and I start at the correct size and can get EXP again.

**Comment by laxika** [comment]
This happened to me too. Try to give your bot an unique name then suicide. That helped me every time. The server hate the default bot name.

**Comment by Piehthyte** [comment]
The reason it happens, for me that is, is because the bot starts the game up quite fast and doesn't give the server time to sync your facebook stats.

**Comment by Creeperman8362** [comment]
renaming myself worked

**Comment by Code-Bear** [comment]
Didnt work for me. Renamed, like I do every time I start it, and died. Name changed, still small at start, still no exp.

**Comment by Crayder** [comment]
Renaming has never worked for me. I've tried it only about every time I died.

**Comment by makanenzo10** [comment]
Whenever mine does that the facebook thing usually pops up when I reload the page. I fix this everytime by clicking switch user if I am logged into another facebook account and login with the account and it starts working fine.

**Comment by MrMaDCaT** [comment]
i have that issue no xp gain anymore stopped at lv56 , trying that right now makanenzo10

**Comment by Apostolique** [comment]
Does it work now? I believe I fixed this with my latest version.

**Comment by MrMaDCaT** [comment]
Works now , but does not continue on dead .

**Comment by Apostolique** [comment]
I'll push a fix right now.
