### ISSUE TITLE
Detected?

### ISSUE THREAD

**Issue by Crayder** [Apostolique/Agar.io-bot#249]
Since yesterday morning, I stopped earning XP when the bot is enabled. When I disable the bot, my score goes up as normal. When I enable the bot, my score is frozen! Please fix...

Also, I suggest saving the last typed name. I have to change the name everytime I connect!

**Comment by laxika** [comment]
Don't think so. I just got lvl 35 around 5 minutes ago. Every time naming change is anoyying as hell I aggree.

**Comment by Code-Bear** [comment]
I am having the same issue with the latest release. Start at size 10 and dont get exp while the bot is active. If I turn off the script and play normal it starts me at the correct size and give EXP.

**Comment by MrMaDCaT** [comment]
@Crayder you can easy change that in the script.
First you need to get the script to your pc , DONT use autoloader for this doesnt work
you will need bot.user.js and loader.user.js 
And here in loader.user.js - So open op loader.user.js with any notepad and use ctrl+f and type in the search field " NotReallyABot " when you found it change the name to anything and save the file ctrl+s now insert the scripts in your tampermonkey , violentmonkey or any other script runner you use and done , the bot wil use the name you just picked when you start it up !

**Comment by Apostolique** [comment]
Can other people confirm that it's the loader.user.js that breaks the exp gains? I'm using a really shitty internet right now so I can't test.

**Comment by Crayder** [comment]
@MrMaDCaT The problem here isn't the name.

**Comment by MrMaDCaT** [comment]
@Crayder  no i know it wasnt the main question :) , but i have the exact same problem as you have with xp gain #289

**Comment by coolemiel** [comment]
@Apostolique Yes i am having the same issue on level 35.

**Comment by Apostolique** [comment]
With the latest update, is the xp gain fixed?

**Comment by Crayder** [comment]
Unfortunately, no, it's still not working...

**Comment by MrMaDCaT** [comment]
it works for me , but the only thing, now it does not continue when dead .
