### ISSUE TITLE
Size Priority

### ISSUE THREAD

**Issue by OverlordQ** [Apostolique/Agar.io-bot#25]
Would be nice if there's an option to ignore the split danger zone if a blob is X% bigger than you. Pretty much most of the time, unless you're close to the same size, they'll ignore you, so it's relatively safe to zip around the massive blobs.

**Comment by Apostolique** [comment]
The current version is currently that way, but some numbers are probably wrong. The problem though is that it can't be a static number since the mass is actually the radius of their circle. So AFAIK, the size ratio of those who want to split on you will change the bigger you get.
