### ISSUE TITLE
not detecting cells smilar size

### ISSUE THREAD

**Issue by dsiugzda** [Apostolique/Agar.io-bot#250]
whenever there is a cell similarly sized to the bot it ignores it sort of and thats how it gets eaten most of the time because either the cell is just a little bigger and the bot wont stay away it'll just eat food, or it wont even notice that the cell is slightly smaller and wont try to eat it.

**Comment by Crayder** [comment]
It's meant to be like that. Cells of "similar" size are to be ignored because they can not harm you (and you can't harm them). Why chase a cell that the bot can't benefit from?

**Comment by dsiugzda** [comment]
Oh I didn't know that sorry I'm new to the game
