### ISSUE TITLE
Organize code into a more accessible API

### ISSUE THREAD

**Issue by zsck** [Apostolique/Agar.io-bot#252]
There's a lot of stuff I'd like to be able to contribute to the bot- I have some really good ideas about how to improve decision making, but the code is frankly a mess.

Could you spend a bit of time on refactoring the bot codebase and providing thorough documentation for the functionality present?  There should be a lot you can do to reduce coupling and provide a clear interface to functions that supply data about the bot's environment.

**Comment by laxika** [comment]
+1!!!

**Comment by dainiusb** [comment]
+2

**Comment by Apostolique** [comment]
There's already an API. I just didn't write any documentation for it.

**Comment by redwire** [comment]
The code could still be a lot better organized.

**Comment by ErmiyaEskandary** [comment]
There's an API - no documentation yet. Possible duplicate of #99.

**Comment by zsck** [comment]
@ErmiyaEskandary Having an API != having source code that's clear enough to grok and contribute to with sufficient ease.

**Comment by ErmiyaEskandary** [comment]
Never said it was. Just said there **is** an API but no documentation* That's why I didn't close #99 as it's valid.

**Comment by ErmiyaEskandary** [comment]
@zsck open an issue for the suggestions and ideas you have. We will surely take them into  account.
