### ISSUE TITLE
Twitter

### ISSUE THREAD

**Issue by DarkN3ss61** [Apostolique/Agar.io-bot#253]
@Apostolique do you have a twitter account that I can put on the website?

**Comment by laxika** [comment]
http://www.twitch.tv/apostolique

**Comment by samfun123** [comment]
I looked for him on twitter and found an account that had a matching profile picture so it might be him, but it looks like it hasn't been used in 2 years and doesn't have many tweets.

**Comment by Apostolique** [comment]
I had completely forgotten about that account. Looking at the old Tweets, it seems like mostly spam. I'll probably make a new account.

It took me a while, but I'm starting to understand how useful Twitter is.

**Comment by ErmiyaEskandary** [comment]
https://twitter.com/JeanDavidMoisan
