### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by Timmitei** [Apostolique/Agar.io-bot#256]
I had a couple of ideas that you might be able to implement in your next release. First, I noticed that you already have a way of indicating your location, but a good idea might be to have a gradient scale that your cell avoids, as a way to keep your cell from getting trapped in the corners/against the edges. The other idea was perhaps to do a similar thing as your cells get farther apart, so that they don't get pushed too far away from each other. I'm not very proficient in many programming languages so I can't help you out very much, but I figured you'd at least appreciate the ideas.

**Comment by Crayder** [comment]
+1 with the not spreading so far apart.

**Comment by FliiFe** [comment]
Everything here have been fixed/implemented now. Closing the issue. Feel free to reopen the issue if you have other suggestions :smiley:
