### ISSUE TITLE
Support for Agar Server Selector

### ISSUE THREAD

**Issue by bohl3r** [Apostolique/Agar.io-bot#26]
Agar Server Selector allows you to join a specific ip address in order to play with your friends.

I'd like to see you make it so that you can run both plugins simultaneously, which currently doesn't work.

Source for Agar Server Selector: https://github.com/electronoob/agarmods

**Comment by Apostolique** [comment]
It would be a lot of work to allow multiple plugins to run at the same time and stay nice with each other. I would have to merge that code into mine, but server selection is outside of my scope for this project. I would rather not add superfluous stuff.
