### ISSUE TITLE
Correction last update

### ISSUE THREAD

**Issue by Endromede** [Apostolique/Agar.io-bot#260]
https://github.com/Apostolique/Agar.io-bot/blob/master/launcher.user.js#L518
https://github.com/Apostolique/Agar.io-bot/blob/master/launcher.user.js#L520
2 to 4.

longtime it's changed. I don't know why it's a problem only now...

**Comment by Apostolique** [comment]
Can you push a commit with the changes?

**Comment by henopied** [comment]
I have posted [a fix](https://github.com/Apostolique/Agar.io-bot/pull/263)
