### ISSUE TITLE
Totally rips up the game???

### ISSUE THREAD

**Issue by TheCodingTomBoy** [Apostolique/Agar.io-bot#261]
I start agar.io, and i am greeted with some grey lines down in the bottom left, a white line down the middle of these, and no signs of any life or viruses. Please help!!!

I am running:
Mac OSX Yosemite v. 10.10.4
Chrome browser

**Comment by makanenzo10** [comment]
I have the same issue:

Windows 8.1 Pro
Chrome and Firefox Latest Build (not beta)

**Comment by Apostolique** [comment]
Fixed in latest update?

**Comment by FlareHAX0R** [comment]
Fixed. Should be closed?
