### ISSUE TITLE
bot is wrecked

### ISSUE THREAD

**Issue by bobdebouwer2015** [Apostolique/Agar.io-bot#262]
not working anymore, i guess they changed something that doesn't agree with the bot :)

**Comment by makanenzo10** [comment]
Yes I am not the only one. I get the exact same issue. The whole game glitches out and breaks.

**Comment by bobdebouwer2015** [comment]
yh same thing here :package:

**Comment by DarkN3ss61** [comment]
Yep, I can conferm this

**Comment by DarkN3ss61** [comment]
Updated the website to say that is isnt working

**Comment by Apostolique** [comment]
Anyone can confirm that it is fixed with latest update?

**Comment by DarkN3ss61** [comment]
@Apostolique Yes

**Comment by Apostolique** [comment]
Cool
