### ISSUE TITLE
Blobs can't travel independently

### ISSUE THREAD

**Issue by yszvrcvf** [Apostolique/Agar.io-bot#266]
As of today, has the ability for multiple blobs to travel independently by the bot been patched or is it a problem with the bot?

**Comment by Apostolique** [comment]
It looks like individual cell control was removed.

**Comment by yszvrcvf** [comment]
:(

**Comment by redwire** [comment]
Why was it removed?

**Comment by Apostolique** [comment]
I assume it was only an experimental feature in the first place? At least I'm glad that the new protocol is backward compatible because it would take a little while to remove the individual cell control from the bot.

**Comment by redwire** [comment]
Did you not implement the functionality yourself?

**Comment by Apostolique** [comment]
Cell movement is validated server side, not client side. It's no longer possible to send each cell in it's own separate direction.

**Comment by Crayder** [comment]
Damn, this sucks. Now I can't jack as much score...

**Comment by dlnetworks** [comment]
still works (mostly) on Ogar servers though...
