### ISSUE TITLE
Merge timer!

### ISSUE THREAD

**Issue by MarkoIvanetic** [Apostolique/Agar.io-bot#267]
I had an idea for a contribution. Putting an option to show the merge timer on each splitted cell.

The merge time is calculated as 30 seconds plus 2.33333% of the cell's mass (ex. Mass is 50, cooldown time is 31 seconds.)

I've been through your code and cannot seem find where do you get cell size from.

**Comment by Apostolique** [comment]
You can get the player's cells using getPlayer(). This returns an array. On each element of that array, you can use element.size. To convert a size into a mass, you do: (size * size / 100).

**Comment by MarkoIvanetic** [comment]
This is the only information I got. If you split on a virus, each of your cells will have timer. After the cooldown it is eligable to merge.

Does the other cell has to go over the cooldown also? I dont know, lemme test.

**Comment by Xodetaetl** [comment]
Why would you add a cheat?

**Comment by MarkoIvanetic** [comment]
A merge timer on a bot that plays the game itself is hardly a cheat my friend.

**Comment by MarkoIvanetic** [comment]
I tested it and I dont think the formula is correct. This is where I got it from
http://agario.wikia.com/wiki/Splitting

**Comment by Timtech** [comment]
Oh well, any merge timer is better than none. As long as it doesn't try to merge too early we should be okay.

**Comment by MarkoIvanetic** [comment]
ok buddy, leave this open for a while!

**Comment by Apostolique** [comment]
When I'm back at home, I'll have the time to compute the real formula.

**Comment by ErmiyaEskandary** [comment]
Added with latest commit.
