### ISSUE TITLE
Modify code to make bot recognize "un-edible" players

### ISSUE THREAD

**Issue by jimmy-changa** [Apostolique/Agar.io-bot#275]
I'm trying to figure out how agar.io sends the names of the other players to the client, so the bot can be set to not eat me or any other player I choose on the same server..  I've had some hilarious yet infuriating experiences in regards to this..  

I have some (programming concepts course taught on visual studio, I made a tic-tac-toe game :D  ) code experience and am currently messing with the bot.user code and the agar.io html source code, but it makes no mention to player names, so I'm at a loss.

I suppose all I'm asking for is a crash course on how call the server and get the info I need.  If anyone with the knowledge can email me some info it would be much appreciated!  If I can ever figure out how to make the bot do what I want, I can try to get the code to Apostolique so he can decide what to do with it, if interested.

**Comment by Apostolique** [comment]
https://github.com/Apostolique/Agar.io-bot/blob/master/launcher.user.js#L1852

Every cell has a name property.

https://github.com/Apostolique/Agar.io-bot/blob/master/bot.user.js#L187

This is the function that tells you if someone is eatable. Make yourself a new list with the names you don't want to eat. Now before returning true for food in isFood(), make sure the name is also not in your list.
