### ISSUE TITLE
cant change name

### ISSUE THREAD

**Issue by Mouroct** [Apostolique/Agar.io-bot#276]

**Comment by Mouroct** [comment]
s

**Comment by jimmy-changa** [comment]
Not sure why it's set up like that, but I think I know the answer.  I was messing around with the launcher.user java script, and I noticed that for whatever reason, the name is stored in there.  Just open it in whatever text editor can support it, and do a search for the current name of your bot.  Edit that and update the script and it should work. I will comment again when I try this myself in a moment.

**Comment by jimmy-changa** [comment]
yup, it works.  email me if you have any issues with the fix.  And for whatever reason, it removes the roomba skin, lol.

**Comment by Apostolique** [comment]
You can also simply press ESC to manually change the name. Then die to validate the name change.
