### ISSUE TITLE
Doesn't work anymore when splitting

### ISSUE THREAD

**Issue by coldpumpkin** [Apostolique/Agar.io-bot#277]
I just noticed that when split, the balls won't independently search for food anymore. They'll just stay still and don't move. What happened?

**Comment by samfun123** [comment]
Independent movement of cells was remove and so this feature isn't available anymore.

**Comment by FliiFe** [comment]
This feature was removed to support remerge after splitting. If you want to split, please disable the bot after split for now. I am working on this issue (apostolique is probably too), but independant cell moving will not be a feature anymore. (Apostolique, correct me if i'm wrong).

**Comment by dlnetworks** [comment]
pretty sure it will still work on Ogar servers.. as it still works on mine =]

**Comment by Apostolique** [comment]
Since I don't have any real internet access right now, I'm not really working on this actively. You're pretty much the core developer now !(Kappa)[https://static-cdn.jtvnw.net/emoticons/v1/25/1.0].
