### ISSUE TITLE
Comments please

### ISSUE THREAD

**Issue by Gilgamesh22** [Apostolique/Agar.io-bot#28]
can we please get more comments in this code. I understand why we cant deobfuscate this but can we just get comments explaining what the variables are and what the functions do. that would be very helpful.

PS Thank you for starting this project.

**Comment by Apostolique** [comment]
You want comments for the game code, or for the bot code? I can do comments for the bot code, but I'd rather not comment the game code as that would be hard to maintain between each updates.

**Comment by Gilgamesh22** [comment]
bot code would be fine

**Comment by Apostolique** [comment]
https://github.com/Apostolique/Agar.io-bot/wiki/Algoritms

You can read the wiki page. It's the high level thinking behind the algorithm.
