### ISSUE TITLE
spectate / simple line mode / virus shot counter / rejoin timer

### ISSUE THREAD

**Issue by dlnetworks** [Apostolique/Agar.io-bot#281]
cant get into spectator mode....

can there be a line mode that only shows the single circle for your own split distance? sometimes thats all i really need to know... when it gets busy and the lines are turned on there is a noticable performance impact as well... just trying to limit the amount of drawing if possible.

oh and virus shots remaining until split, and a rejoin timer would be handy =]

cheers

**Comment by MarkoIvanetic** [comment]
Feel free to provide some formulas.
I believe they randomized merge time between 30s+2.333%(mass) and  30s+2.666%(mass) so that part can only be approx.

**Comment by ErmiyaEskandary** [comment]
Duplicate of #267
