### ISSUE TITLE
Blob too small to eat other players.

### ISSUE THREAD

**Issue by Atrain111** [Apostolique/Agar.io-bot#282]
I have noticed that sometimes the bot targets other players even though that they cannot be eaten. Maybe you need to up the ratio a little?

**Comment by Apostolique** [comment]
You're right, the current ratio is set to 130% it will probably need to be adjusted.

**Comment by henopied** [comment]
I think its around 133% but I could be wrong

**Comment by ErmiyaEskandary** [comment]
Since the bot doesn't split, it doesn't have any means to catch up to smaller faster players. It differentiates between a moving target and a non moving target and it only goes for non moving ones.
