### ISSUE TITLE
How do I stop the auto respawn thing...

### ISSUE THREAD

**Issue by Waitt** [Apostolique/Agar.io-bot#283]
I can't change my game mode and name (coz I love skins :/) so can you do it so you can toggle if you want it to not auto respawn?

**Comment by heros2030** [comment]
Or you just press ESC and change the name and gamemode
Op 2 aug. 2015 10:24 schreef "Waitt" <notifications@github.com>:

**Comment by Apostolique** [comment]
Also make sure to die after you change your name with ESC.
