### ISSUE TITLE
Circles are not big enough, own blob runs into circles

### ISSUE THREAD

**Issue by jjc12** [Apostolique/Agar.io-bot#288]
The issue issue_one is that drawn circles for cells that are over twice as big are so small that my own cell (call it John) runs into the split zone for these cells. The screenshot screenshot_one demonstrates this. 
![screenshot_one](https://cloud.githubusercontent.com/assets/5194299/9076071/9b4bd5d6-3aeb-11e5-99ec-af049b88a69c.png)

The other issue that contributes to issue_one is the destination/path_to_destination runs over the larger cells. This should not happen and it should re-locate the destination if it does. The screenshot screenshot_two demonstrates this.
![screenshot_two](https://cloud.githubusercontent.com/assets/5194299/9076137/740fca76-3aec-11e5-9879-e5de09dac4d7.png)

I would love to work (collaborate) with you on these issues, so if you tell me how to fix these, I'll happily contribute to this open-source project.

-jjc12

**Comment by Apostolique** [comment]
If I understand issue your one correctly, that is the intended behavior. It's usually safe to assume that really big people will not try to split on your if the size difference is really big.

Issue two is a two part problem. In your screenshot, you can notice that you are outside of the danger zone of the big green cell. This means that to avoid the current danger zones right above, you can get closer to the green cell first before having to handle it too. When you do get closer to the green threat, the bot will start orbiting around it.

I'm not sure if those are problems that need solving.

**Comment by jjc12** [comment]
"It's usually safe to assume that really big people will not try to split on your if the size difference is really big."

After running your bot for 50 games with no modifications, the top score was 66, due to eating one cell and a lot of food. 
After modifying the JS code so that all cells were avoided, even the small ones, I was able to run 5 games with a top score of 320.

Consider the long-term implications of your bot. If I somehow miraculously got to a score of 800, maybe after 1,500 or so games, if ever - then got eaten by a cell with a size of 3,000, no one is going to be happy about it.

As for issue_two, you didn't answer my question. Although I am outside of the danger zone, the cell is still heading toward the much bigger cell.

**Comment by Apostolique** [comment]
I see what you mean for #1 now. I'll write a better response tomorrow. Never getting into bad situations isn't always possible, but I had a bunch of stuff planned for handing every bad situation. It's just not coded in yet.

For #2, I did answer, it won't actually end up running into the cell. Sure the white line could be made shorter so that it doesn't go past any enemies, but it isn't required as when you get inside the danger zone, the enemy will be handled correctly by the obstacle code.

In previous version, the white line was much shorter, the problem was that in some cases, the bot would end up getting stuck between it's own cells when it was split. Making the line longer was a fine fix at the time.

**Comment by jjc12** [comment]
After looking over the relevant parts of your code, this can be fixed in 30 minutes. Tell me what I have to do in regards to these issues. How do I make the circles larger for these cells? How do I fix the path so it doesn't go over large cells? Any more?

**Comment by Apostolique** [comment]
Search for where the function "canSplit" and "compareSize" is used. That's where I make the distinction for sizes.

**Comment by jjc12** [comment]
Thanks, Apos!

**Comment by Apostolique** [comment]
When I'm back, I really need to get around to documenting everything. I need to make it easier to make unique bots.
