### ISSUE TITLE
Xp gain

### ISSUE THREAD

**Issue by MrMaDCaT** [Apostolique/Agar.io-bot#289]
Since fuw days i get no more xp when i use the bot . Just me ?

**Comment by dlnetworks** [comment]
still working for me

**Comment by MrMaDCaT** [comment]
strange xp gain stopped on lv 56 also spawning as a 10mass cell , when i play manual without script it works just fine

**Comment by Apostolique** [comment]
If you press ESC when the bot is running, are you connected to Facebook?

**Comment by MrMaDCaT** [comment]
yes

**Comment by Apostolique** [comment]
Is it fixed with the latest update?

**Comment by dlnetworks** [comment]
its been fixed for a while... mines been gaining xp since the last update i think

**Comment by MrMaDCaT** [comment]
checking now !

**Comment by Apostolique** [comment]
Any news?

**Comment by MrMaDCaT** [comment]
yea works , but doesnt restart when dead or even autostart
