### ISSUE TITLE
Bot not spawning/moving w/console

### ISSUE THREAD

**Issue by Thunder33345** [Apostolique/Agar.io-bot#292]
http://prntscr.com/8137qf
http://prntscr.com/8138cv
i have adblock and i just edit the name noltreallyabot to itzthunder now it did that
i tried to esc but it do nothing

**Comment by Apostolique** [comment]
Are you using loader.user.js along with bot.user.js + launcher.user.js? Disable the loader then.

**Comment by AdvertiserM** [comment]
I'm having similar issues, but for some reason my post was deleted.

**Comment by AdvertiserM** [comment]
http://i.imgur.com/rDfExza.jpg

**Comment by vovd** [comment]
Same for me, It's because I was blocking Google Ads and things with Ghostery.

**Comment by demung** [comment]
mine is not working

**Comment by ErmiyaEskandary** [comment]
Connection issue fixed. Phantom visual bug fix in progress.
