### ISSUE TITLE
When I use the bot I can't play at all, any idea why? 

### ISSUE THREAD

**Issue by AdvertiserM** [Apostolique/Agar.io-bot#295]
I removed Adblock Plus and it still didn't work... So I don't know why.. It just stays at this empty screen 

http://i.imgur.com/GAP3Jq4.jpg

using latest version of chrome

**Comment by Apostolique** [comment]
Did you see any errors in the console? Right Click -> Inspect Element -> Console.

**Comment by AdvertiserM** [comment]
http://i.imgur.com/MVgf0Be.jpg

**Comment by Apostolique** [comment]
Disable the loader if you're gonna use the other two.

**Comment by AdvertiserM** [comment]
I did and now I get this 
http://i.imgur.com/P8yRE10.jpg
