### ISSUE TITLE
how do you show the mass of everyone in the game?

### ISSUE THREAD

**Issue by the-casle** [Apostolique/Agar.io-bot#307]

**Comment by Drflash55** [comment]
You could use preview on a separate webpage and view something that's closest to your location (preferbly #1).

**Comment by the-casle** [comment]
How would you get to the separate webpage, is it like a userscript or something? I see people on the same server not in party, but I can't figure out how.

**Comment by ErmiyaEskandary** [comment]
Unclear question. To reopen, make a new issue with a clear topic.
