### ISSUE TITLE
Broken?

### ISSUE THREAD

**Issue by MrMaDCaT** [Apostolique/Agar.io-bot#308]
Is it broken ? 
Agar.io update ?
My bot does not move anymore , and still no xp gained plus starting as 10 mass .

**Comment by Gjum** [comment]
See also https://github.com/RealDebugMonkey/ZeachCobbler/issues/51

**Comment by kkprince1998** [comment]
I think perhaps agario is pushing updates to the servers slowly (so some are updated, but not all), and this update breaks the bots, because occasionally/rarely it will work

**Comment by Apostolique** [comment]
I believe I fixed it earlier.
