### ISSUE TITLE
Need info on Level / Mass - Break Down

### ISSUE THREAD

**Issue by jasikanicolepi** [Apostolique/Agar.io-bot#309]
Sorry that I am piggybacking on the Apostolique's page. I am trying to gather data in regards to level/starting mass. Can people who has been running the bot share your level, EXP until the next level and starting mass with me, It will be much appreciated.  This is an independent research for Agar.io since they are no available data.

**Comment by Apostolique** [comment]
You'll probably have more luck asking on https://www.reddit.com/r/agario
