### ISSUE TITLE
Score does not get reset when the server is restarting

### ISSUE THREAD

**Issue by BigSeeProduction** [Apostolique/Agar.io-bot#31]
The server I was on just restarted (i think :o) and the shown score is still 702 from before!

**Comment by Apostolique** [comment]
I would assume that's a bug in the original code as I didn't change the way the score is computed.

**Comment by DarkN3ss61** [comment]
This is in the normal agar.io code.  This is not a bug with the bot

**Comment by DarkN3ss61** [comment]
Also, it's not oftern the servers restart they only restart if there is an issues, so there is no need to do anything about this

**Comment by BigSeeProduction** [comment]
But it would be awesome too if the score shown in the left bottom corner was the current score and not the highest score in this lifespan :)

**Comment by Apostolique** [comment]
You can already activate mass in options for that.
