### ISSUE TITLE
Starts game as a guest, even if logged in (probably fix from agar.io team)

### ISSUE THREAD

**Issue by kirillbunin** [Apostolique/Agar.io-bot#310]
Self explanatory, i tried commenting out ´setNick()´ and starting manualy through console, and it did get me in the game with mass bonus.
Tried delaying loading of the scripts, didn't help.

**Comment by Apostolique** [comment]
I'll look into it tomorrow.

**Comment by Apostolique** [comment]
If you update, does Facebook work now?

**Comment by kirillbunin** [comment]
No. In fact its worse, game doesn't autostart, upon death it loops with
`
Skipping draw
Dead: 27
Wait!
Skipping draw
Skipping draw
`
in console, and does not revive.

**Comment by Apostolique** [comment]
In your console, it never says "Facebook?".

**Comment by kirillbunin** [comment]
Nope. Yea it's okay, I don't want to rush you :)

**Comment by Apostolique** [comment]
I made a special version for you:
https://gist.github.com/Apostolique/a12658de9b955653f505

It's not going to fix your issue, but at least it will tell a bit more about what's going on. You should at least see Facebook related messages in your console.

**Comment by CCTrollz** [comment]
I have always had this problem, I just thought you disabled Facebook login.

**Comment by CCTrollz** [comment]
I tried out the custom version and all it does it say "WAIT!" in the console.

**Comment by kirillbunin** [comment]
Both special version and master is working.. -ish.
Sometimes it takes few reloads to get game going (meaning that it doesn't start automaticly, and restart on deaths). So I would say resolved.
