### ISSUE TITLE
how can i start game from experiment ?

### ISSUE THREAD

**Issue by JesWhite** [Apostolique/Agar.io-bot#315]
yes i chanced some options but not working only for experiment 
direct ffa option but i want to play directly experiment...
please say me where i change from autolauncher

**Comment by Apostolique** [comment]
You'll have to call the function:
````
setGameMode(":experimental");
````
Put that right on line 200:
https://github.com/Apostolique/Agar.io-bot/blob/master/launcher.user.js#L199

**Comment by JesWhite** [comment]
thanks for your supports..
