### ISSUE TITLE
facebook

### ISSUE THREAD

**Issue by Titaniumtown** [Apostolique/Agar.io-bot#316]
facebook points dont add and u dont get ur extra mass from facebook

**Comment by Drflash55** [comment]
There could be some likely explanations...
One, you may be playing on a private server and facebook points don't get added unless you play on official agar.io servers...
Another could be that the bot you have is outdated... If you haven't already, try updating to the newest version and see if it fixes it.

If not, consult Apostolique about the issue.

**Comment by Apostolique** [comment]
It sounds like you need to log out of your facebook account, then log back in.

**Comment by Titaniumtown** [comment]
thx again

**Comment by Titaniumtown** [comment]
nvm i tried that it doesn't work :(
