### ISSUE TITLE
[Fix] Correctly chasing other blobs

### ISSUE THREAD

**Issue by phroggyy** [Apostolique/Agar.io-bot#323]
Currently, other players are evaluated just like food, and the bot will follow a smaller blob until it's too far away. However, it would be better if the chase would not be pursued from the very beginning. I see two ways to do this; one is to follow the following rules:
1. Do not follow a blob which is not in splitting range
2. If the blob is in range, only aim at the blob if the player is more than twice the size (I don't know exactly how large one needs to be to consume another blob)
3. Only split if you are aimed at the blob and within range (account for a minor error margin too)

The second way, which is a lot more complicated and resource intensive, is tracking the direction, size and velocity of a blob to determine whether to chase (and potentially being able to predict the trajectory of the blob as to split in the right direction).

**Comment by Apostolique** [comment]
Maybe I'll make a separate system for non moving food and moving food (other players).

**Comment by ErmiyaEskandary** [comment]
#331

**Comment by ErmiyaEskandary** [comment]
Since the bot doesn't split, it doesn't have any means to catch up with smaller faster players. It differentiates between a moving target and a non moving one. It only goes for non moving ones.
