### ISSUE TITLE
no facebook fix!!!

### ISSUE THREAD

**Issue by Titaniumtown** [Apostolique/Agar.io-bot#324]
i saw advice and none of it helped, there is a bug pls fix it

**Comment by Apostolique** [comment]
Try to die right after spawning, do you revive with the correct Facebook size?

**Comment by Titaniumtown** [comment]
no

**Comment by Titaniumtown** [comment]
nothing facebook works

**Comment by Apostolique** [comment]
I'm on the case.

**Comment by Titaniumtown** [comment]
thx

**Comment by Titaniumtown** [comment]
oh btw how long will it take?

**Comment by Apostolique** [comment]
Don't know.

**Comment by DarkTanner** [comment]
What is this update ? beside bugging facebook ?
