### ISSUE TITLE
getMode()

### ISSUE THREAD

**Issue by stefnotch** [Apostolique/Agar.io-bot#327]
Importance (10 = very important, 0 = who cares): 1
Browser: FireFox
Issue: window.getMode() returns nothing when playing in FFA, in all the other modes it returns what it is supposed to return

**Comment by Apostolique** [comment]
That's good to know. At least it returns a string, I could probably make it return ":ffa", but it's probably not needed since you can just check for an empty string when you want to specifically target the ffa mode?

**Comment by stefnotch** [comment]
Yes, though you might want to change the comment above it! :D Afterwards, close this issue!

**Comment by Apostolique** [comment]
Nothing like a wrong comment to help people double check everything. :D
