### ISSUE TITLE
possible ai improvments

### ISSUE THREAD

**Issue by henopied** [Apostolique/Agar.io-bot#328]
This is not necessary but i am wondering if you if you could improve your bot's ai with [ogar's bot ai](https://github.com/OgarProject/Ogar/tree/master/src/ai) especially when it comes to the virus shooting I think this could help you.

**Comment by Apostolique** [comment]
It's possible. I'll have to go through their code and see how it does it. I suspect their bot has more power than mine though since I don't know all the specific formula used by the official servers.

**Comment by henopied** [comment]
I have an idea i was working on it right now what if we used your launcher to power their botPlayer.js

**Comment by Apostolique** [comment]
In theory it should work.

**Comment by henopied** [comment]
I was looking at their code a bit and it doesn't seem overly difficult to be honest do you want to make a branch called ogar x apos or just keep it private until it works well?

**Comment by henopied** [comment]
As I don't know all of the things that the launcher does I will need help in order to make this work. If there could be a public branch made for starting to do this I would be glad. :)

**Comment by Apostolique** [comment]
I created one. https://github.com/Apostolique/Agar.io-bot/tree/ogar-bot

It looks like that bot is usually ran server side?

**Comment by henopied** [comment]
That is where we need to do some work (remove all the stuff that has to do with communicating to the server directly and replace it with things that communicate with your launcher)

**Comment by Apostolique** [comment]
I see. Hopefully it doesn't require variables that are hidden server side.

**Comment by henopied** [comment]
Ogar is an open source agar.io server implementation so you can always look through the whole server code to figure it out what their ai does

**Comment by Apostolique** [comment]
Yeah, and anyway, we'll end up figuring out all the formulas eventually.

**Comment by henopied** [comment]
So will we keep part of the bot or scrap it completely and only leave the launcher?

**Comment by henopied** [comment]
I was thinking we might want to keep the basic functions from apos bot but scrap find destination and other functions that would be replaced by the ogar bot

**Comment by Apostolique** [comment]
That could work.

For the other thing you said above, the goal for this project is to have a single launcher but many bot algorithms to choose from. (I might have miss understood what you said though.)

**Comment by henopied** [comment]
Alright I guess this will be our second bot for it then :D

**Comment by henopied** [comment]
I have been doing some work on this and there is still a lot to go but I need your help on how I would lisense this properly judging as I have to include the ogar license (apache) and yours (mit). Once I have the licensing sorted out I will pull request what I have so far.

**Comment by Apostolique** [comment]
You don't need my license. AFAIK it doesn't effect other bots that are made using the launcher. My license should only apply to AposBot, AposLauncher, AposLoader.

Since you're using the Ogar bot, you only their's.

Both licenses are rather permissive though.

https://tldrlegal.com/license/apache-license-2.0-%28apache-2.0%29
https://tldrlegal.com/license/mit-license

**Comment by henopied** [comment]
I have looked at those but I did kinda take parts of your bot rather small ones at that but I still did so it would be considered a derivative.

**Comment by henopied** [comment]
I just thought of something awesome using phantom.js with node it would be so easy to make a program that would launch say 100 bots with custom names using your launcher (a few tweaks required) and ogar's bot for experements like finding out what the real eating ratio is etc. and many more statistics. :open_mouth:

**Comment by Gjum** [comment]
> using phantom.js 
There are also a lot of headless clients out there, no need for `phantom.js`.

**Comment by henopied** [comment]
true but phantom is a good one

**Comment by Gjum** [comment]
Phantom emulates a full web browser. It would be less overhead to just use a websocket client.

**Comment by henopied** [comment]
what headless client would you recommend for this application

**Comment by Gjum** [comment]
some I quickly found on github:
https://github.com/pulviscriptor/agario-client
https://github.com/ibash/agar
more: https://github.com/search?l=JavaScript&langOverride=&q=agar+client&repo=&start_value=1&type=Repositories

**Comment by henopied** [comment]
pulviscriptor's client looks pretty awesome for this while ibash's hasn't had an update in months.

**Comment by henopied** [comment]
Ok so I have vps with node an I ran pulviscriptor's test script and I am truly amazed that he made something so awesome. Thank you very much for pointing me in this direction I can see the future in porting bots to use pulviscriptor's client.
