### ISSUE TITLE
Pursue players and dont get food/people in viruses

### ISSUE THREAD

**Issue by tenten8401** [Apostolique/Agar.io-bot#331]
Title says it all.
You should pursue players and not treat them like food.
You should NOT collect food or people in the viruses

**Comment by Apostolique** [comment]
Oh, that's a good way to see it.

**Comment by ErmiyaEskandary** [comment]
#323

**Comment by ErmiyaEskandary** [comment]
@Drflash55 Can you confirm this ?

**Comment by Drflash55** [comment]
@ErmiyaEskandary I don't think it would make a difference if I tried out previous versions, as Agar.io itself has been updated quite a lot lately.

Pretty sure that if the newer version is bugging out, trying to go back to a legacy version won't fix the issue, as the bot needs to be updated to remove the bug in the first place.

**Comment by ErmiyaEskandary** [comment]
I was talking about if the bot pursued player in an older version where the bot was playable. At the moment, the phantom bug is being worked on. ;)
