### ISSUE TITLE
screenDistance

### ISSUE THREAD

**Issue by stefnotch** [Apostolique/Agar.io-bot#333]
Importance: 0
Issue: Isn't this code rather inefficient? And, what does it do?
function screenDistance() {
        var temp = f.getScreenDistance();
        return temp;
}

**Comment by Apostolique** [comment]
That function isn't used anymore. It looks like that for debug purposed. What it did was figure out the distance from the middle of the screen to the closest edge. Then it would know if a cell was off the screen. The problem is that it would break when zooming in or out.

**Comment by stefnotch** [comment]
Ok, then you could close it.

**Comment by Gjum** [comment]
When you open an issue, you can also close it yourself. ;)

**Comment by stefnotch** [comment]
Ok, there is a button at the bottom... Thanks! :D

**Comment by Apostolique** [comment]
:D
