### ISSUE TITLE
isItMe and getTeam inefficient

### ISSUE THREAD

**Issue by stefnotch** [Apostolique/Agar.io-bot#334]
Importance: 5
Issue: Those 2 functions get called quite often so it might be a good idea to make them more efficient.
Instead of:
var currentRed = parseInt(currentColor.substring(1,3), 16);
var currentGreen = parseInt(currentColor.substring(3,5), 16);
var currentBlue = parseInt(currentColor.substring(5,7), 16);
I suggest this:
var currentRed = currentColor.substring(1,3); 
var currentGreen = currentColor.substring(3,5);
var currentBlue = currentColor.substring(5,7);
Then, you only have to check if it is equal to "ff". Why bother with casting them to integers? (Also, in my tests, the colors were always like this: Red team: 255, random number, random number)

Here is my "improved" code:
function isItMe(player, cell) {
        if (getMode() == ":teams") {
            var currentColor = player[0].color;
            var currentRed = currentColor.substring(1,3);
            var currentGreen = currentColor.substring(3,5);
            var currentBlue = currentColor.substring(5,7);
            
            var currentTeam = getTeam(currentRed, currentGreen, currentBlue);

            var cellColor = cell.color;

            var cellRed = cellColor.substring(1,3);
            var cellGreen = cellColor.substring(3,5);
            var cellBlue = cellColor.substring(5,7);

            var cellTeam = getTeam(cellRed, cellGreen, cellBlue);

            if (currentTeam == cellTeam && !cell.isVirus()) {
                return true;
            }

            //console.log("COLOR: " + color);

        } else {
            for (var i = 0; i < player.length; i++) {
                if (cell.id == player[i].id) {
                    return true;
                }
            }
        }
        return false;
    }

    function getTeam(red, green, blue) {
        if (red == "ff") {
            return 0;
        } else if (green == "ff") {
            return 1;
        }
        return 2;
    }

Oh, I think you know this already but when the blob get's split, he doesn't behave very well....

**Comment by Apostolique** [comment]
Thanks! If you want the credit, feel free to commit those changes.

**Comment by stefnotch** [comment]
Just wondering, how do I commit stuff? (I am not using Github a lot...) (I only know how to commit crimes but that's illegal! XD)

**Comment by Gjum** [comment]
If you want to learn Git, maybe start here: https://git-scm.com/book/en/v2/Getting-Started-About-Version-Control

**Comment by stefnotch** [comment]
Yeah, that seems like a useful link but I don't feel like learning all of that stuff. A simple explanation of how to use the website (the command line is quite a lot of work..) to commit things would be nice. Do you first have to fork the project?

**Comment by henopied** [comment]
Go to the bot.js and hit edit and then paste in the modified bot click commit and then in your own fork hit compare & pull. Though at some point you should learn git it will help you if you ever need a job :P

**Comment by stefnotch** [comment]
Ok, thanks! Just what I was looking for. And, I guess you are right! Good that I am still young and don't need a job! (Muwhahaha! Living off my parents like an evil parasite!)

**Comment by Apostolique** [comment]
Git is really simple, but for this project, I only use the web interface. :^)
