### ISSUE TITLE
Color coding blobs that can be splitkilled

### ISSUE THREAD

**Issue by Drflash55** [Apostolique/Agar.io-bot#335]
Usually, because of how blobs look, they look small enough for you to split them, but in reality you aren't big enough to eat them...

Color-coding the blobs purple, for instance, can signify if you are good enough to split them (minor errors can occur), just so that you don't need to risk losing your cells while trying to re-combine after a miscalculated attempt at trying to splitkill.

**Comment by henopied** [comment]
This is mainly useful only for follow mouse mode correct?

**Comment by Gjum** [comment]
Duplicate of #247

**Comment by individuell** [comment]
correct, but like many others, I like to play without the bot, but with lines enabled. Like OP, I would also like to know if I am big enough to splitkill a nearby cell or not, because often its hard to tell. iirc your splitted half needs to be 33% bigger than the target cell.

**Comment by Gjum** [comment]
I totally agree with OP, I just want the discussion to be in one place. There are currently 4 open issues discussing the exact same thing.

**Comment by henopied** [comment]
(guys don't worry)[https://github.com/Apostolique/Agar.io-bot/blob/master/bot.user.js#L235] it is more visible in dark mode so do that and then uncomment those few lines.

**Comment by individuell** [comment]
@henopied ohh nice, thank you for the hint! I just tried it out and it worked fine, but it's not very precisely. Needs a bit more value tweaking. Wish I'd have the time to read into the maths.

**Comment by Drflash55** [comment]
@individuell Thanks alot for the code change, now I don't have to worry so much as to whether or not I'm able to split someone...

**Comment by henopied** [comment]
did you get rid of both the comment /* and */ (a few lines later) if you didn't and just got rid of the first one you just commented of the top bit of the code and thats what registers the bot. and some other vital functions.

**Comment by Drflash55** [comment]
@henopied I have, but it still says Human mode...

```
function isSplitTarget(blob, cell) {
        *if (canSplit(cell, blob)) {
            return true;
        }*
        return false;
```

This is what I have it right now... When I remove both the /* and */, when I test it out, it still says Human...

**Comment by Apostolique** [comment]
The right code should be:

````
if (canSplit(cell, blob)) {
    return true;
}
return false;
````

**Comment by individuell** [comment]
after some further testing I've came to say that even with 2.4 as the ratio value it sometimes fails. Increase the value to be more sure.

**Comment by Drflash55** [comment]
I'm guessing 2.6 or 2.7, this requires testing...

**Comment by Apostolique** [comment]
2.66 would make sense. The value for eating normal non split-able targets is probably around 1.33 in that case.

**Comment by Drflash55** [comment]
@Apostolique I have tested 2.65 so far... It hasn't messed up, but, 2.66 could be a perfect value for it...

**Comment by Apostolique** [comment]
I committed the changes.

**Comment by Drflash55** [comment]
I just did another test with the value 1.33, and this time, I was able to get myself into someone while they collected a pellet, and just that single one, eat me...

The value 1.33 for isFood and isThreat is perfected, same with 2.66 for canSplit.
Hurray!

**Comment by Apostolique** [comment]
Yay! You're awesome btw for testing that. I expected the value was something like that after building a bit of an intuition in my mind. I got the 1.30 value from the viruses. It used to be the same for eating back when the game came out but I guess he changed it at some point. (Actually viruses used to be 1.35.)

**Comment by Drflash55** [comment]
Thanks for the compliment, and I was glad to help... I think I can finally close this issue, since @henopied found out how to get a reticle for the blobs that can be splitkilled, and @individuell for getting an approx. amount of the value for split killing...

Thank you all for your help...

**Comment by Drflash55** [comment]
Hmm... I just got into a situation, where I was bigger than someone, but I didn't eat them, even though the thing said so...

1.33 is a good value, but if you want to be super precise, you can put in 1.325 or something like that...
Nothing worth another update, unless you want a precise value...

**Comment by henopied** [comment]
ogar uses 1.25 so 2.5 for splitkill

**Comment by individuell** [comment]
Just had a situation where I could splitkill someone who was not marked as a splitTarget, just slightly bigger. My cell was about 400 big and he was half my size, so I decided to give it a try. It was a pretty snappy kill and he was close but it worked, so just letting you know. Might require some precision though. 

I was using the newly commited values, 2.66 in canSplit and 1.33 in isFood. Will report further.

**Comment by Drflash55** [comment]
Hold on...

I just acquired this number recently...

1.3465

It might be the actual ratio in order to eat a cell?
