### ISSUE TITLE
getBlobCount()

### ISSUE THREAD

**Issue by stefnotch** [Apostolique/Agar.io-bot#338]
What does getBlobCount() do? Does it get the number of players? If yes, here is a quicker way:
window.getPlayer().length; 

(Yes, I do know that currently the function isn't being used.)

**Comment by Apostolique** [comment]
I saw that too yesterday, I didn't code that in, I guess it was in one of the commit that I accepted.

**Comment by stefnotch** [comment]
Ok, then you could get rid of it, right? (Or change it.)

**Comment by Apostolique** [comment]
Yeah

**Comment by stefnotch** [comment]
Since you apparently got rid of it, I will close this issue.
