### ISSUE TITLE
Facebook Starting Mass broke (edit: has nothing to do with the bot I think)

### ISSUE THREAD

**Issue by individuell** [Apostolique/Agar.io-bot#341]
EDIT: sorry, nevermind, just tried it in a browser without any extensions/scripts, it doesn't seem to work at all.

Used to work a couple hours ago with the latest commit. Suddenly stopped spawning with FB-mass. 

What I have tried: 
- Deleting Facebook and Agar.io Cookies (re-logging and connecting agar with FB)
- die after spawning and/or hit ESC as it usually works
- restarting browser

Using Chrome/Tampermonkey - AposBot 3.565

**Comment by Drflash55** [comment]
The Facebook Starting Mass thing might be broken once again...
Zeach will have to look into this in order to fix this problem...

**Comment by individuell** [comment]
Yes it is an agar issue. People on Reddit are complaining aswell.

https://www.reddit.com/r/Agario/comments/3hyeoq/no_more_starting_mass_bonuses/
