### ISSUE TITLE
LAG!

### ISSUE THREAD

**Issue by ALEEF02** [Apostolique/Agar.io-bot#344]
ever since today's update, the bot has run as smooth as ever on my laptop (6 gigs of ram). Now the game is getting as low as 0.05 fps (1 frame evry 20 seconds) Please fix

**Comment by Apostolique** [comment]
If I understand correctly, when the update first came out, it was running super smooth, but now, even though there weren't any updates it doesn't run smooth anymore?

**Comment by ALEEF02** [comment]
No, in the past update it was amazing, but yesterday's update made it lag SUPER hard

**Comment by ALEEF02** [comment]
Oops

**Comment by tech4david** [comment]
Do you know which commit(ss caused it?
