### ISSUE TITLE
Agar.io-Bot breaks during gameplay...

### ISSUE THREAD

**Issue by Drflash55** [Apostolique/Agar.io-bot#346]
For some reason when you play with the AposBot for about 10 - 20 seconds, the game just freezes and nothing happens... You can still access the menu, but you can't do anything else, and the whole interface is gone, acting like if you got eaten...

![Why the hell is this?](http://puu.sh/jMIGz/0243341acb.png)

This is all I see, and I can't do anything else... If you try connecting to another server, then you can't open the menu at all...

Because this thing is game-breaking now somehow, I'm sticking to the old version of Agar.io-bot until this is fixed...

EDIT: Actually, I can't... The in-game mouse get's stuck at the top-left...
This thing just became unplayable until this is fixed...

**Comment by Drflash55** [comment]
I actually found out the reason why...
The u.isSplitTarget script is broken...

Whenever the bot finds a target that is splittable, it can't read a certain code in the script, so it crashes the screen.
If this is fixable, please do, I loved the canSplit script.

**Comment by individuell** [comment]
I'm confirming issues with the isSplitTarget function. Make sure to use the updated version where it uses u.canSplit(cell, blob) instead of just canSplit(cell, blob).

Although it still causes freezes with the current commit.

**Comment by Drflash55** [comment]
@individuell I have used the u.canSplit code instead of canSplit, but it freezes...
I have no idea what's wrong with the coding, except for the fact that it crashes whenever a splittable target enters the screen, most likely can't read the radius that's supposed to appear around them...

**Comment by individuell** [comment]
@Drflash55 what I did for now, is just reverting back to the commit before apos started the refactoring. Found here: https://github.com/Apostolique/Agar.io-bot/tree/43ee61134c49c572720041d7bb727ec7b45f897c

**Comment by Drflash55** [comment]
@individuell Only thing is, the mouse get's stuck in the top left, and it doesn't move at all...

**Comment by Apostolique** [comment]
I'll look into it.

**Comment by Apostolique** [comment]
I fixed both the team mode and the isSplitTarget

**Comment by individuell** [comment]
confirming that isSplitTarget works again within the current commit, thank you Apos!

**Comment by Apostolique** [comment]
I had an extra "u." in front of something that didn't need it.

**Comment by Drflash55** [comment]
By the way, I'm curious @Apostolique, about the little numbers under the cell...
I really have no idea what purpose they serve at all...

**Comment by individuell** [comment]
I'm curious aswell. 

Also I would be **very** interested in a variable that holds the real cell value. I'd like to implement a notification once I reach a certain amount of cell mass.

**Comment by Apostolique** [comment]
The first number is the current time alive of the cell.

The second number is once again the current time alive, but from the estimated time it will take to be able to merge again. (If two cells are negative, they should be able to merge back together.) This current formula is wrong, but works relatively well for smaller cells.

The third number is the cell's size at birth time. If you split and you were size 100, the new cell will have a birth size of 50.

**Comment by Apostolique** [comment]
@individuell You could do that in https://github.com/Apostolique/Agar.io-bot/blob/ef10e7ce6f0b548c3745d7779a93b042889e9d9a/bot.user.js#L788

The size would be at:
````
var mass = (player[k].size * player[k].size / 100)
````

**Comment by individuell** [comment]
Thank you so much! :+1: :-)
