### ISSUE TITLE
Button to disable spliting

### ISSUE THREAD

**Issue by tiagovit** [Apostolique/Agar.io-bot#35]
The only issue i have with this script is the splinting. Because of it i can't get big :c and i want to get biggg :C Cool script tho :D

**Comment by Apostolique** [comment]
You should try the current beta branch.

**Comment by dombeef** [comment]
Ive disabled splitting in my fork for the master branch, although the beta branch has splitting mostly disabled(quickly glanced over at the code, looks really promising as an alternative method of searching and avoidance)

**Comment by Apostolique** [comment]
I merged the beta branch back in master, no more splitting.

**Comment by i9w** [comment]
Hey dombeef, could you update you're version so that it works with latest agar.io? I'd like to use the zoom out feature.

**Comment by dombeef** [comment]
Oh hey, apostolique's bot now works again! Thats odd, it didnt work earlier when the update to block certain custom scripts came out.

Ill try to see what is causing my fork to be blocked, im a bit busy at the moment, with finals and all, but i should be able to try a few hours here and there, ill be mostly free for the end of this week to try to get it working.

You could always try to edit in the zoom out feature into the new master branch, it shouldnt be too hard to do.

**Comment by Apostolique** [comment]
There was an update to block scripts? I didn't get the memo.

**Comment by i9w** [comment]
dombeef, actually Apostolique updated his script, I think you can just copy paste the zoom out feature into Apos version?

**Comment by dombeef** [comment]
Apostolique, it was more about them trying to block scripts that were cheating(technically our bots would fall under that name since it gives us unhuman like reflexes as well as seeing other masses, scaling, and seeing the wall borders(maybe more like the forks had those extras thrown in), but more specifically, there were plugins that would change the adspace in the game to their own ads(so the creators of agario wouldnt get any money from clicked ads, only the script developers would) which the creators of agario really wanted to stop, so they did something(still have no idea what they did to block certain scripts)

**Comment by dombeef** [comment]
Apostolique, it was mainly to block scripts that overlayed their own ads over the sites ads, as well as some scripts that added features like zooming out and showing all mass(the scripts that replaced ads all seemed to be used to unfairly play the game, so it may show why the old bot was blocked(as well as yours, yet somehow it randomly started working again :P)

And i9w, why cant you just do it if you think its easy? I'm busy trying to get the old bot code working(just for the heck of it, as well as trying to keep the code still running, both it and the new code are great methods of avoidance, although the newer one starts to lag on my computer after a few minutes of playing/many people on the screen/ high ping from the server)  in my free time, which ive been busy lately.

**Comment by jordsmi** [comment]
@Apostolique they made some sort of change so that scripts like agario.org don't work anymore. If you try to play it either won't connect to a server or it just shows a white screen.

**Comment by Apostolique** [comment]
I see. Still,l I'm pretty sure if they updated their code, it would work again.

**Comment by i9w** [comment]
dombeef, I'm just using a chrome extension currently to zoom out, as it's the only one working. Without it the game is pretty much bugged, where you can't see cells split killing you only after they do.
