### ISSUE TITLE
Number.prototype.mod and Array.prototype.peek

### ISSUE THREAD

**Issue by stefnotch** [Apostolique/Agar.io-bot#353]
What are those functions good for? (launcher.user.js) They don't seem to get used anywhere.
Number.prototype.mod = function(n) {
    return ((this % n) + n) % n;
};

Array.prototype.peek = function() {
    return this[this.length - 1];
}

**Comment by Apostolique** [comment]
mod gets used everywhere. peek is just because I'm lazy.

I need mod because the Javascript implementation of % is wrong. It doesn't work for negative numbers.

**Comment by stefnotch** [comment]
Yeah, but they aren't used in the AposLauncher, hence the question.

**Comment by Apostolique** [comment]
They are just there in case they are ever needed.

**Comment by stefnotch** [comment]
Ok! (Can I add a billion of useless functions that also are there just in case...)
