### ISSUE TITLE
how can i uninstall?

### ISSUE THREAD

**Issue by filipp25** [Apostolique/Agar.io-bot#354]

**Comment by filipp25** [comment]
how can i uninstall agario bot?

**Comment by Apostolique** [comment]
Just remove the script from Greasemonkey / Tampermonkey.

**Comment by filipp25** [comment]
thanks Apos

**Comment by xxnagxx51** [comment]
I dunno I can't Evan install

**Comment by stefnotch** [comment]
@xxnagxx51 What is your problem?

**Comment by xxnagxx51** [comment]
My problem is that I have a tablet I install everything but I still can
evan upload or install

**Comment by stefnotch** [comment]
So, let me try to understand that:
You installed everything including:
-A browser with Greasemonkey/Tampermonkey
-Ok, making a list with only one item is silly! :P

And, you are having issues with installing the bot.
