### ISSUE TITLE
Not possible to use the bot on private servers?

### ISSUE THREAD

**Issue by Lbniese** [Apostolique/Agar.io-bot#356]
Hello,

It seems like the bot can't run on private servers even though they are using the FFA mode.

An address for a private server could look like this:
http://agar.io/?ip=46.101.28.170:443

Any ideas what to change in the source code to allow "custom" or "private" servers?

Regards

**Comment by Apostolique** [comment]
I'll look into it later.

**Comment by stefnotch** [comment]
//Server hotfix! (Add this somewhere in the launcher.user.js)
if(window.location.search.split("?ip=")[1]){
    setTimeout(()=>{connect("ws://"+window.location.search.split("?ip=")[1]);},4000);
}

Also, my browser is complaining about line 360: q = new WebSocket(a); //Apparently your script and agar.io interfere with each other. How about making your script run after the entire page has loaded and everything is done? (Would prevent some future problems...)

**Comment by Lbniese** [comment]
When saying "my script" i assume you meant the server i linked to, right?
I guess it could cause errors atm, due to not being online.

Although if you make a pull request or something like that, I can apply it to my fork and test it on private servers.

**Comment by stefnotch** [comment]
"//Apparently your script and agar.io interfere with each other. How about making your script run after the entire page has loaded and everything is done? (Would prevent some future problems...)" That was directed at Apostolique..

And, should I make a pull request with the cheap server hotfix?

**Comment by Lbniese** [comment]
Doesn't seem to work. I applied your hotfix to the Launcher.user.js

**Comment by stefnotch** [comment]
What was the server IP? (I currently don't have any IP that I could use to try it out.) You might want to try increasing the delay.. (The number 4000)

**Comment by Lbniese** [comment]
http://agar.io/?ip=46.101.42.52:443

**Comment by stefnotch** [comment]
It seems to work perfectly for me.
```
if(window.location.search.split("?ip=")[1]){
setTimeout(()=>{connect("ws://"+window.location.search.split("?ip=")[1]);},4000);
}
```
^^I added that code at the very top of the launcher...

Here is one that waits 14 seconds before connecting.
```
if(window.location.search.split("?ip=")[1]){
setTimeout(()=>{connect("ws://"+window.location.search.split("?ip=")[1]);},14000);
}
```

**Comment by makanenzo10** [comment]
That works for me! Amazing! You should make this a pull request for the official bot :+1:

**Comment by Apostolique** [comment]
If you didn't update to the latest launcher, please do, I pushed a fix.
