### ISSUE TITLE
Cant play with new update

### ISSUE THREAD

**Issue by DarkTanner** [Apostolique/Agar.io-bot#359]
The screen just freeze...  Is this possible to skip the update when everything is fine ?

**Comment by Apostolique** [comment]
What browser are you using?

**Comment by Apostolique** [comment]
Get the latest version and it should say:
````
Bot: AposBot 3.61
Launcher: AposLauncher 4.1
````

**Comment by xxnagxx51** [comment]
Nether can I I can't install it

**Comment by Apostolique** [comment]
Follow this: http://bot.jlynx.net/

**Comment by DarkTanner** [comment]
firefox 40

anyone have the  previous update ?

**Comment by DarkTanner** [comment]
I dont knoiw if this is the problem but i desactivated my facebook account yesterday...

**Comment by Apostolique** [comment]
If you disable the bot and you can play, then the facebook thing is not the problem.

**Comment by DarkTanner** [comment]
The version on the left corner ?

do you hava  a link with the previous version ? thanks

**Comment by Apostolique** [comment]
Perfect!

**Comment by xxnagxx51** [comment]
Ok
