### ISSUE TITLE
Not compatible with the Agar Extended Chrome extension.

### ISSUE THREAD

**Issue by harelSH** [Apostolique/Agar.io-bot#36]
Can you make them be able to work together?

**Comment by dombeef** [comment]
I dont think you can easily run two different scripts at the same time, right?

You would have to manually add into this script the things you want, it shouldnt be too hard to find the different add ons(Im assuming showing mass and different color depending on size?) in different mods elsewhere.

**Comment by Apostolique** [comment]
Doing something like that is beyond the scope of the project.
