### ISSUE TITLE
No XP generated

### ISSUE THREAD

**Issue by Hamsterman** [Apostolique/Agar.io-bot#361]
It seems that when you die the game refreshed so fast that no xp is generated.

Browser: Chrome
Bot version: Auto updater
Cell name: Changed from default
Facebook: Connected

**Comment by Apostolique** [comment]
For me Facebook still works, and I believe it works because my computer is really fast.

**Comment by Hamsterman** [comment]
Not sure what you mean with that respond - the thing is, that when you die the game loads too fast. I never passes the "gain xp" step.

**Comment by Apostolique** [comment]
That's not actually the reason for the xp not updating since the xp is done server side. The error happens when the script is first loaded into the page.

Try using the bot.user.js and launcher.user.js instead it might fix the problem.

**Comment by Hamsterman** [comment]
Same problem with the bot and launcher scripts.

**Comment by Hamsterman** [comment]
Hm - it might work after all. I will return later.

**Comment by Hamsterman** [comment]
I can confirm it works with the bot.user.js and launcher.user.js.

**Comment by Apostolique** [comment]
Oh sweet! I'll have to figure out how to fix it for the loader.
