### ISSUE TITLE
Bot not working, last update

### ISSUE THREAD

**Issue by CorentinGC** [Apostolique/Agar.io-bot#362]
Hi !
I'm on Chrome + OSX

The bot isn't working anymore, there are all the texts, and when I press the keys, it updates on the screen, but no effects (bot and lines, but mass option and darktheme are working). The ball is following my mouse.
I first updated when prompted. And then tried to uninstall and reinstall clean, same effect.

Thanks

**Comment by Apostolique** [comment]
If you look on the top left, does it say:
````
Bot: AposBot 3.61
````

**Comment by ItzExcalibur** [comment]
I'm having the same problem, and yes/no. The Bot: ApostBot isn't their. But the AsposLauncher 4.1 is except mine say AsposLauncher4.147

**Comment by Apostolique** [comment]
Can you go in your Greasemonkey / Tampermoney dashboard and remove AposBot from there?

**Comment by ItzExcalibur** [comment]
I didn't install it but I can, I put the script into Ctrl+Shitft+J.

**Comment by Apostolique** [comment]
I'm not sure what that means, but if you didn't install it, then it's normal that it doesn't show up.
