### ISSUE TITLE
just wondering if splitting is fully implemented.

### ISSUE THREAD

**Issue by xXtheguy52Xx** [Apostolique/Agar.io-bot#368]
I see that there is a grey circle on split targets but the bot refuses to split onto them, so i was wondering if this was a mistake or just the first step into implimentation

**Comment by henopied** [comment]
There is no current automatic splitting functionality this is mainly for people that use the bot in follow the mouse mode or just as a tool to graze for food and then actually do the harder work.

**Comment by xXtheguy52Xx** [comment]
thanks
