### ISSUE TITLE
Disable Autoplay?

### ISSUE THREAD

**Issue by MastaCoder** [Apostolique/Agar.io-bot#372]
I was just wondering what lines of code I would have to change to stop the program from automatically clicking the play button? It just gets really annoying how it always restarts without me telling it to. Or if there is an option to have it stop?

**Comment by Drflash55** [comment]
This feature is so that, IMO, people can farm Facebook EXP without the need of having to sit there watching the screen so that they can restart the game when the bot dies...

I'm not sure if there's a way to turn it off. You'd be better off asking @Apostolique, or someone who has shut off this feature before...

**Comment by makanenzo10** [comment]
@Apostolique Do you know what code I have to remove so that I can stop it from autoplaying? I attempted a couple code at the top of the page but it just messes up the whole bot completely. :/

**Comment by Apostolique** [comment]
https://github.com/Apostolique/Agar.io-bot/blob/b6bd1d2c6c7b48d734e181e67c31606d4ed230c7/launcher.user.js#L652

Comment that line out.

**Comment by makanenzo10** [comment]
It worked! Thanks!

**Comment by makanenzo10** [comment]
One more question, do you know how to make it so that it doesn't quite a server? I want to use this on a private server: http://agar.io/?ip=70.35.202.119:443 but whenever I load it up, it changes the server. Do you know how I can stop that?

**Comment by Apostolique** [comment]
The launcher doesn't have that.

**Comment by Drflash55** [comment]
@Apostolique, do you think it's possible that you can implement a way so you can change servers, via IP? Agariomods, and other js scripts have found out a way to change the ip you're connecting to, so that you're able to go to a different server.

**Comment by makanenzo10** [comment]
Well is there anyway to stop it from changing servers or no? It must always be on the public Agar.io servers?

**Comment by Apostolique** [comment]
You guys seem to want the opposite thing. One wants the server to change and the other doesn't want it to change? I'm not sure I understand what you want.

**Comment by Drflash55** [comment]
@Apostolique, it's for changing servers via IP, which can be done by other scripts, but @makanenzo10 is asking how to stop the server from changing, because it always heads back to the Official Agar.io servers for him when he tries to connect to his private server.

**Comment by makanenzo10** [comment]
Exactly what Drflash55 is saying. There has to be some way to get rid of it?

**Comment by Apostolique** [comment]
I didn't have time to fix this yet, but I should be able to later this week.

**Comment by stefnotch** [comment]
You might want to change the title of the issue. Also, here is a relevant issue: https://github.com/Apostolique/Agar.io-bot/issues/356

**Comment by makanenzo10** [comment]
Alright @Apostolique

**Comment by ErmiyaEskandary** [comment]
Fixed.
