### ISSUE TITLE
follow mouse working?

### ISSUE THREAD

**Issue by eric-m** [Apostolique/Agar.io-bot#373]
Does "q" still work for you to follow the mouse?  For me, I think it stopped working when you made AgarBot into an object.

I'm not sure what the issue is.  The main reason I bring this up is that I want to add a key to toggle features on/off in the bot, and I was hoping to emulate your working version of the mouse toggle.  :)

I want to be able to collect different stats doing a/b testing.  Run a couple browsers with a feature toggled on, and then run a couple more with it toggled off, and see if my improvements are truly improvements or not.  I've figured out how to intercept key strokes in the launcher.  I just don't know how to do it from the bot code.

Thanks for any help!

**Comment by Apostolique** [comment]
Q does still work.

Just follow this to add your own key actions:
https://github.com/Apostolique/Agar.io-bot/blob/f5ec4ac6552871290981fb49b7b997e8ff433da8/bot.user.js#L116

**Comment by eric-m** [comment]
Thanks!  Somehow when I merged your latest changes into mine, I messed up and was missing this key line:

https://github.com/Apostolique/Agar.io-bot/blob/master/launcher.user.js#L107

That makes sense.  :)
