### ISSUE TITLE
Cornering

### ISSUE THREAD

**Issue by CruaverVoidDrake** [Apostolique/Agar.io-bot#38]
Often I notice myself getting cornered in the red zone. The bot then has no idea how to get out.

**Comment by Apostolique** [comment]
The process of getting away from enemies is not an easy one to solve.

**Comment by Piehthyte** [comment]
You could have the bot create some kind of algorithm for each direction the enemy goes therefor calculating its next step and circumventing the cornering. Just a thought :P

**Comment by Apostolique** [comment]
You can post however many times that you want, I closed it just so it doesn't show in the "issues" list as it's not a concrete issue. I am open for brainstorming though and will likely reply to everything.

**Comment by Piehthyte** [comment]
Alright! So if they were to go left the bot would calculate your blobs movement direction vs. the following blob and attempt to find any way to get away may that be using the virus things to explode your enemy or simply using it as cover while they pass. Or using an ally that is larger than you as cover so long as he is bigger than the pursuing blob.

**Comment by Apostolique** [comment]
I'm planning on adding cover later on where you can use both a virus or other players as shields.

**Comment by CruaverVoidDrake** [comment]
You could also perhaps add a program that attempts to split it as a last course of action to survive.
