### ISSUE TITLE
Evasion Logic

### ISSUE THREAD

**Issue by Code-Bear** [Apostolique/Agar.io-bot#383]
I have noticed for some time now that the bot does not react well when more than one cell is near by. I also notice there isn't much in the way of reasoning in the direction it chooses to go when it is evading a cell. If I might make a suggestion... why not have the bot track the center point of the nearby cells and travel the exact opposite of that point in relation to the bot. This would not only solve the problem of cells catching you do to slow choppy movements from the bot as it attempt to move along the warning zone of the enemy cell but as additional cells come near it can simply find the central point of each of the cells and travel along the opposite midpoint of all the surrounding cells. At that point if 3 or even 4 cells are around instead of stopping it would forcefully ignore the warning zone and follow the safest path out of the middle of the group.

**Comment by henopied** [comment]
I am not following what you are saying it has a lot of logic behind it.

**Comment by Code-Bear** [comment]
I agree most of the time the bot evades correctly from a single cell, the black directional line with face opposite of the single cell but when more than one cell is near and even worse when your cell is in the danger zone of multiple cells instead of simply finding the safest route out with would be the midpoint opposite of all the cells it freaks out and jitters back and forth. This is probably do to some calculation error when their are to many overlapping radials to evade. Hence why I said track them from the central point and use that single point to calculate the direction to take.

**Comment by henopied** [comment]
The "freaking out" part is when it has no good angles and it choses the farthest enemy to go towards but then there is a farther enemy so it goes back and forth when stuck

**Comment by Code-Bear** [comment]
No matter how many radials overlap there is a point where the overlapping breaks, that would be the safest exit point, and instead of following a direct path to that point it simply goes back and forth. I dont know if you know it travels toward the nearest enemy at that point of that is just speculation but it would be, in my opinion, a bad way to calculate an exit path vs simply traveling toward the closest point the warning radials stop overlapping. Either way we both agree when there are multiple cells near by the bot is unable to correctly follow a path to the safest exit.
