### ISSUE TITLE
Bot only tracks one of the split cells

### ISSUE THREAD

**Issue by Code-Bear** [Apostolique/Agar.io-bot#384]
At one point the bot was able to independently manage many split cells, admittedly they would all split off in different directions and eventually get eaten but now I have noticed that only a single cell is tracked by the both. So if you are playing while the bot is running "Follow Mouse Mode" and you split the bot will only track one of the cells. This causes the bot to move the other cell into viruses, other cells, and into walls which all slow down or worse cause your split cells to get consumed by other players. Can you put back the ability for the bot to track and evade based on both cells instead of just the one? Without that it makes it very problematic to split a cell.

**Comment by henopied** [comment]
the thing is agar doesn't let you control the cells independently anymore.

**Comment by Code-Bear** [comment]
That is fine, the bot doesnt need to control the split cell, it simply needs to account for the additional cell while avoiding cells, walls, and viruses. I am assuming the bot can still measure a warning radial for the split cells.

**Comment by henopied** [comment]
I agree and I tried before to do this but it was being strange anyways I am already working on my own bot to be released soon that does the average point thing you described.

**Comment by Apostolique** [comment]
I wrote a little bit of code to do that a month ago. I could dig it back up and add it back in.

**Comment by henopied** [comment]
So does agar let you do that? And I was also working on something that would control from the center of all cells and offset getdist by the furthest cell out but I kept on getting Nan this was designed for applezbot I could send you what I have so far once I am not on mobile be warned that the code for applezbot is still messy and I think what you are looking for is beta 3.5

**Comment by Apostolique** [comment]
Agar sends all the cells towards one direction. I just need to base that direction on all my cells instead of only one.

**Comment by henopied** [comment]
alright so far I have [this](https://gist.github.com/henopied/0a2664ffe0a39e77cf6c)

**Comment by henopied** [comment]
@Apostolique how would you do distance weights I am trying to add weights to my midpoint code because atm it could go straight into an enemy.

**Comment by Apostolique** [comment]
Are you able to draw what you are trying to do? I can explain better if I understand your algorithm.

**Comment by henopied** [comment]
![untitled drawing](https://cloud.githubusercontent.com/assets/13500516/9838374/e278a736-5a21-11e5-856a-a32c77a409d9.png)

**Comment by Apostolique** [comment]
Let's say you have two objects located on a one dimensional line with a size associated to them:
**Object 1: Location: 10 Size: 1**
**Object 2: Location: 20 Size: 1**

The mid point for those objects, since they have the same size would be "**15**", or **((Location1 + location2) / 2)**.

If we have those next values instead:
**Object 1: Location: 10 Size: 2**
**Object 2: Location: 20 Size: 1**

We want to make the mid point closer to Object 1. The simplest way I can think of to make Object 1 have a bigger weight in the formula is to add it twice: **((Location1 + Location1  + location2) / 3)**.

Doing that, I start to notice a pattern. Perhaps, the formula can work with decimal numbers.
**Object 1: Location: 10 Size: 1.5**
**Object 2: Location: 20 Size: 1**

**((Location1 * Size1 + location2 * Size2) / (Size1 + Size2))**

**Comment by henopied** [comment]
How would I scale that for more than 2 cells though and I already have midpoint code its in the combinevectors function.

**Comment by Apostolique** [comment]
Oh, I forgot the write about that!

What I wrote above scales. To simplify the function, I'll use a, b, c objects. a1 is location and a2 is the size.
**(a1 * a2 + b1 * b2 + c1 * c2 + etc) / (a2 + b2 + c2 + etc)**

I see that in your function, you're looping through a list with all your cells. Here is the code that I would write:
````
OgarBot.prototype.combineVectors = function(list) { // TODO add distance weights
  // Gets the angles of all enemies approaching the cell
  var pos = {
    x: 0,
    y: 0
  };
  var elementWeights;
  for (var i = 0; i < list.length; i++) {
    elementWeights += list[i].size;
    pos.x += list[i].x * list[i].size;
    pos.y += list[i].y * list[i].size;
  }

  // Get avg
  pos.x = pos.x / elementWeights;
  pos.y = pos.y / elementWeights;

  drawPoint(pos.x, pos.y, 1, 'Midpoint');
  return pos;
};
````

**Comment by henopied** [comment]
Thank you for that. Might you also have a way of adding dist to the weights? And I also noticed you didn't divide the positions by how many elements there were.

**Comment by Apostolique** [comment]
Essentially, when you divide your points by how many elements there are, you are giving all your points a weight of **1**.

If you want to add a distance to the weight, you can simply add it to the weight directly.

As long as all your weights are on the same scale, and they are properly factored in when adding the point's coordinates, you'll end up with a valid result.

**Comment by henopied** [comment]
the weight that you have from my understanding is the bigger the number the more important so a smaller number (closest enemy) would be less important if I directly put the dist in the weight.

**Comment by Apostolique** [comment]
Exactly. smaller weight means less important value. If you use the enemy as the location to calculate the distances from, the furthest points will become more significant.

**Comment by henopied** [comment]
Would you find the farthest enemy and then subtract dist from the farthest dist to determine weights?

**Comment by Apostolique** [comment]
I am not quite sure I understand.

If you want to calculate a distance value, you'll need two points. If I understand correctly, you want to get the distance from the furthest enemy towards each of your cells?

**Comment by henopied** [comment]
So far the multi cell code is only being used to determine if the other players are in fact dangerous and the distance is the distance between the center-point and the threat and because the center-point code makes the cells very close to each other by default I only use the offset to determine if the threats are dangerous or not

**Comment by Apostolique** [comment]
That code doesn't work?

**Comment by henopied** [comment]
It does work and in my new code the closest enemy weight gets multiplied by 2 I just wanted to share what I had so far.

**Comment by Apostolique** [comment]
Nice!

**Comment by henopied** [comment]
Oh btw it reverses the vector to find the destination.

**Comment by henopied** [comment]
This actually may not be the best but it was just a thought I had also I was trying to remove my current bulky slow inefficient and whatever other way you would like to describe it so I will just copy some of the code that you had for removing bad food that way I get to remove the split threat list too.

**Comment by Apostolique** [comment]
Just to be sure, you want to remove the food the would make you go towards an enemy. (In that triangular zone.)

**Comment by henopied** [comment]
Yes that is correct.

**Comment by Apostolique** [comment]
The easiest way that you can do that is by checking on which side of your line the food is. Since you have two lines, you check for both lines.

[How to tell whether a point is to the right or left side of a line](http://stackoverflow.com/questions/1560492/how-to-tell-whether-a-point-is-to-the-right-or-left-side-of-a-line)

**Comment by henopied** [comment]
The other thing is how would I get the lines in the first place I think you have something that does this in your anglestuff or atleast it finds the points but I am on mobile so I can't check for sure

**Comment by Apostolique** [comment]
You can use the code there:
http://stackoverflow.com/a/3461533/1710293

You only need two points that you know are on your line, and the point with the location of your food.

**Comment by henopied** [comment]
Thank you very much for that!
