### ISSUE TITLE
Alternate Bot - Agar.io-pop-bot

### ISSUE THREAD

**Issue by caiosm1005** [Apostolique/Agar.io-bot#385]
A troll Agar.io bot that likes exploding foes.

It starts just like Agar.io-bot. After obtaining some mass, it stands still on top of the nearest virus, hiding it. When an attacker comes close enough, the bot moves away in the last second, leaving the virus to be eaten and to explode the bigger cell.

![Bot in action](https://github.com/caiosm1005/Agar.io-pop-bot/raw/master/preview-images/bot-in-action-1.gif)

Fork URL: https://github.com/caiosm1005/Agar.io-pop-bot

**Comment by henopied** [comment]
I have been testing it for a while and I have noticed on occasion the cell is actually too big to go into the virus so it pops itself.

**Comment by Linkaan** [comment]
Hilarious, it works quite well. However, if a cell is big enough to split and eat the bot, it will move away from the virus thus making the disguise useless. I think it would be better if the bot stays no matter what happens.

**Comment by caiosm1005** [comment]
@Linkaan Hmm... when the cell is on top of a virus, all danger zones are tuned down to a small radius, just enough to move away when the bigger cell gets too close. I've noticed sometimes the danger zone is not tuned down. That's a bug.

@henopied That is true and happens not often. Guess I need to re-balance some calculations.

**Comment by Apostolique** [comment]
That's awesome! I'll add it to the list!

**Comment by caiosm1005** [comment]
@Apostolique Thanks! Renamed it to `ExplosiveBot 1.1`

I've improved the bot today - re-balanced some numbers and made it more cautious. I think the aforementioned issues were reduced quite a bit.

**Comment by henopied** [comment]
You may want to change the user script version and maybe add auto update code

**Comment by caiosm1005** [comment]
@henopied I'm not familiar with userscript. Do you mean changing the version in this comment block?

    // ==UserScript==
    // @name        ExplosiveBot
    // @namespace   ExplosiveBot
    // @include     http://agar.io/*
    // @version     1.0
    // @grant       none
    // @author      https://github.com/caiosm1005
    // ==/UserScript==

**Comment by Apostolique** [comment]
The two versions need to be the same:
https://github.com/caiosm1005/Agar.io-bot-explosive/blob/775668b48ce86066f28a85c99dddb55f1e10e81e/bot.user.js#L27
https://github.com/caiosm1005/Agar.io-bot-explosive/blob/775668b48ce86066f28a85c99dddb55f1e10e81e/bot.user.js#L32

The second one is to remove the dependency on Greasemonkey.

**Comment by caiosm1005** [comment]
@Apostolique Done. Is that all?

    // ==UserScript==
    // @name        ExplosiveBot
    // @namespace   ExplosiveBot
    // @include     http://agar.io/*
    // @version     1.1
    // @grant       none
    // @author      https://github.com/caiosm1005
    // ==/UserScript==

https://github.com/caiosm1005/Agar.io-bot-explosive/blob/master/bot.user.js#L27

**Comment by henopied** [comment]
Yea that's what I meant just as not to confuse users.

**Comment by Apostolique** [comment]
Yeah, it's better now, but really it was never required :)

**Comment by caiosm1005** [comment]
@Apostolique If you do, keep in mind I've used cooldown values specific to ExplosiveBot. Maybe there shouldn't be any cooldown at all for Agar.io-bot.

**Comment by Apostolique** [comment]
Not sure if you feel like it, but perhaps you can add a cool feature. When the bot is too big, make it shoot into the viruses to create more of them.

**Comment by henopied** [comment]
That would be cool if it could shoot fast enough as to not be too big while it is focused on the virus. And also if it is almost too big whilst hiding maybe it should shoot like it normally does (to avoid people feeding it to make it pop on the virus also maybe the cooldown should be removed or reduced on this one just in case.)

**Comment by caiosm1005** [comment]
@Apostolique [Could you rename it](https://github.com/Apostolique/Agar.io-bot/wiki/Alternate-Bots) to Agar.io-pop-bot?

That name sounds better.

**Comment by henopied** [comment]
also you should probs add the remove food from shift distance to your pop bot

**Comment by Apostolique** [comment]
I changed it.
