### ISSUE TITLE
Right wall misplaced causing AI to get stuck.

### ISSUE THREAD

**Issue by powback** [Apostolique/Agar.io-bot#39]
When eating at the very edge of the world and then seeing an enemy, the AI will ignore the wall and try to escape through it, causing it to get stuck and eventually eaten.

This happens in the latest builds. Haven't checked the other walls yet.

**Comment by Apostolique** [comment]
I'll check that later. Thanks for the report!

**Comment by powback** [comment]
No problem!
It just occurred again on the left wall, so I'm assuming it's the same issue on all walls. The green ring disappears and there are no valid escape routes.

**Comment by powback** [comment]
Upon further investigation, it appears like I'm wrong. The location isn't misplaced at all. It's something weird that's going on.

How to replicate the issue:
Turn the bot off, but leave the HUD on.

Got to the bottom left corner and move along the bottom to the bottom right corner. The wall indicator should be correctly positioned.

Move away until the wall indicator no longer is within your radius (not showing as a threat).

Go back into the corner.

The wall indicator is now misplaced and you'll be able to pass through it, rendering the bot unusable as there are no escape routes.

**Comment by Apostolique** [comment]
That's an issue with the way I implemented the algorithm. Will fix it later.
