### ISSUE TITLE
Bot loads empty

### ISSUE THREAD

**Issue by pyeman70** [Apostolique/Agar.io-bot#392]
![image](https://cloud.githubusercontent.com/assets/14281848/9860427/07446048-5b24-11e5-8523-1b5ccfd0ef38.png)
Doesn't show my cell or name? Tried installing and uninstalling...

**Comment by Drflash55** [comment]
Huh...
Never encountered this...

This seems like it's a new issue, but consult this with @Apostolique

**Comment by Apostolique** [comment]
It looks like your code is crashing. If you're on google Chrome, are there any errors that you see in your console?

**Comment by pyeman70** [comment]
Thanks for the help I figured out it was something to do with my adblocker the bot is now fully functional :)

**Comment by Apostolique** [comment]
I see.

**Comment by henopied** [comment]
Might you want to add something that says this in the readme

**Comment by Apostolique** [comment]
Good idea.
