### ISSUE TITLE
Control the largest cell instead of cell at index 0

### ISSUE THREAD

**Issue by caiosm1005** [Apostolique/Agar.io-bot#397]
It's possible the bot is split into numerous cells due to a virus.

I understand that only 1 cell can be controlled currently. While this isn't improved, probably would be smarter to control the largest cell [instead of the first cell in the array](https://github.com/Apostolique/Agar.io-bot/blob/master/bot.user.js#L803).

If you agree, I can make a PR with this feature.

**Comment by henopied** [comment]
That would be nice but the problem would be If somebody eats your smaller parts then splits for your largest bit but I guess this handling would be much much better than just controlling index 0.
I can show you what I have in my ogar bot for this:
'''
OgarBot.prototype.getHighestCell = function() { // Gets the cell with the highest mass
  var myCells = getPlayer();
  if (myCells.length <= 0) {
    return null; // Error!
  }

  // Starting cell
  var highest = myCells[0];
  for (var i = 1; i < myCells.length; i++) {
    if (this.getMass(highest) < this.getMass(myCells[i])) {
      highest = myCells[i];
    }
  }
  return highest;
};
```

**Comment by Apostolique** [comment]
The code for that was written a month ago, I just didn't bother putting it back in yet.
