### ISSUE TITLE
(not really an issue) How do I change the custom skin?

### ISSUE THREAD

**Issue by an-OK-squirrel** [Apostolique/Agar.io-bot#399]

**Comment by an-OK-squirrel** [comment]
It seems to be in the bot.user.js, I can't find where though.

**Comment by Apostolique** [comment]
It's on this line:
https://github.com/Apostolique/Agar.io-bot/blob/f9fffd32c124e6b1f6b67f8d6255b6f033e512c1/launcher.user.js#L2101

If you want to add your own name, don't forget to add to the the name list above:
https://github.com/Apostolique/Agar.io-bot/blob/f9fffd32c124e6b1f6b67f8d6255b6f033e512c1/launcher.user.js#L1931

I'm sure you know that already, but only you will see the skin that you add.

**Comment by an-OK-squirrel** [comment]
Thanks.
