### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by adamdabadboy** [Apostolique/Agar.io-bot#4]
When script is enabled, no option to change name or server. Stuck on screen showing blobs moving in the background, there is no user blob.
http://i.gyazo.com/45d5c4fcf0a49ba7c8162f52bed82a2a.png

**Comment by AshleyDodd** [comment]
The team update seems to have broken the script. Check back every know and then for an updated version.

**Comment by Apostolique** [comment]
Updated :)
