### ISSUE TITLE
[bug] recent agar.io changes renders any bot unusable ?

### ISSUE THREAD

**Issue by i9w** [Apostolique/Agar.io-bot#40]
I'm spawning in the corner everytime and the script is lagging also the game isn't working with the bot. It appears to be something on line 1404. (gustoughson version), tried this version too and didn't work.

Can someone confirm? Firefox latest with greasemonkey latest version.

**Comment by betrisey** [comment]
Same problem
![capture d ecran 2015-05-31 a 16 18 28](https://cloud.githubusercontent.com/assets/1939395/7902191/b0cf520c-07b0-11e5-913b-5c61725c2d87.png)

**Comment by i9w** [comment]
I've heard they limited your view distance to combat the hacks that let you see farther out.

**Comment by ConcernedHobbit** [comment]
Same here, it seems that the bot is broken and in need of a fix.

**Comment by Apostolique** [comment]
Update to the latest version.

**Comment by i9w** [comment]
Thanks Apostolique, very great coder. Could you add the field view other old bots had it? (gus tough son)

**Comment by Apostolique** [comment]
I don't know what that was.

**Comment by i9w** [comment]
When you press "Y" the field view turns on, in that you could press "y" and zoom out of the map.
