### ISSUE TITLE
Gitter chat?

### ISSUE THREAD

**Issue by an-OK-squirrel** [Apostolique/Agar.io-bot#401]
I feel alot of the "issues" on here aren't issues (stuff like my question earlier) I think a gitter chat would be great for that

**Comment by henopied** [comment]
That would be great actually ill tag @Apostolique so he will see this too.

**Comment by an-OK-squirrel** [comment]
argh, getMemoryCells isn't helpful at all

**Comment by henopied** [comment]
it isn't?

**Comment by an-OK-squirrel** [comment]
Yeah, so I'm copying getAll :P

**Comment by henopied** [comment]
memory cells remembers cells that go off the screen for a bit thats all.

**Comment by an-OK-squirrel** [comment]
yeah I know

It's actually the obfuscation that bothers me

**Comment by an-OK-squirrel** [comment]
*you see, this is why we need a chatroom xD*

**Comment by Gjum** [comment]
:+1:

**Comment by an-OK-squirrel** [comment]
If you want, I can create a temporary one

**Comment by henopied** [comment]
What obfuscation?

**Comment by an-OK-squirrel** [comment]
Oh just the objects have weird values

**Comment by henopied** [comment]
Also I think we should wait for apos to make one.

**Comment by an-OK-squirrel** [comment]
e.g. "x, y, ux, vy, G, etc"

**Comment by an-OK-squirrel** [comment]
Okay then

**Comment by henopied** [comment]
lol yea the var names are weird

**Comment by an-OK-squirrel** [comment]
It's mainly that some people get emails for this

**Comment by Apostolique** [comment]
SPAM THEIR INBOXES!

Okay, if we get a chat room, it can't be IRC since we need to be logged in to receive the messages. The best would be a shoutbox such as: http://www.staredit.net/shoutbox/

As you can see, every single message is saved forever.

**Comment by Apostolique** [comment]
Or I could create a separate repo just for chatting.

**Comment by Apostolique** [comment]
https://github.com/Apostolique/AposChatRooms

Okay done. Not sure how many people will come but it's there. Now I can look at this in a few years and feel the **shame, shame, shame**.

**Comment by an-OK-squirrel** [comment]
We mean gitter.im

**Comment by Apostolique** [comment]
Oh, that's cool never heard of it. I thought you had a typo :^)

https://gitter.im/Apostolique/ACS?utm_source=share-link&utm_medium=link&utm_campaign=share-link

**Comment by an-OK-squirrel** [comment]
K thx

**Comment by furkankucukuysal** [comment]
yes :)

**Comment by Apostolique** [comment]
btw, I have a Twitter too.

**Comment by Drflash55** [comment]
Neato.

**Comment by caiosm1005** [comment]
@Apostolique Just wondering, are you from SEN? I loved that community.

**Comment by Apostolique** [comment]
I am from Sen indeed.

**Comment by ErmiyaEskandary** [comment]
https://gitter.im/Apostolique/ACS - refer here
