### ISSUE TITLE
Only skin?

### ISSUE THREAD

**Issue by makanenzo10** [Apostolique/Agar.io-bot#413]
Can anyone show the section for only the skin. It seems like whenever I copy the skin section and import it into another user.js it doesn't work. Is their any other code then the skin fuction that I have to copy?

**Comment by PMasta** [comment]
This is not an issue. This is request!

**Comment by Apostolique** [comment]
Don't forget to add your name to the name list.

**Comment by makanenzo10** [comment]
Aha Thanks :D
