### ISSUE TITLE
Show menu after death

### ISSUE THREAD

**Issue by MastaCoder** [Apostolique/Agar.io-bot#415]
What code will I have to put in the death function for the menu to show up? Because it is just really annoying when it doesn't pop up when I removed the revive code.

**Comment by Drflash55** [comment]
Haven't figured this out yet...
But, you should get some assistance from @Apostolique 

He knows how to do things with his JS scripts.

**Comment by Apostolique** [comment]
I think I never did include the code for that menu.

**Comment by makanenzo10** [comment]
Is there any way to simulate the press of escape when a user dies?

**Comment by ErmiyaEskandary** [comment]
Dead Topic
