### ISSUE TITLE
Multiple Skins?

### ISSUE THREAD

**Issue by makandz** [Apostolique/Agar.io-bot#419]
Any chance for Agar.io-Bot to support multiple custom skins? The current one looks good, is it possible to have multiple skins without having to always go back to the code?

**Comment by Apostolique** [comment]
It's possible. I didn't code anything specifically to do that though.

**Comment by makanenzo10** [comment]
Do you know if there is a way to simulate a press of ESC or to show the menu when a user dies?

**Comment by makanenzo10** [comment]
Alright. I'll see if I can *try* to get it working :p
