### ISSUE TITLE
Detecting if cells are merging

### ISSUE THREAD

**Issue by SJMakin** [Apostolique/Agar.io-bot#421]
First off, great project.  it has given me hours of fun.

I am struggling to understand the launcher and wondered if you knew which property on the player's cell(s) indicates when the player is able to merge.   This would be great, as I currently have a modified version of your bot which splits to eat targets, but it rarely merges back when it can and so becomes prey for other players.  

I have checked in my changes under my fork.  Feel free to steal them.

**Comment by Drflash55** [comment]
@SJMakin You should rename your bot so it doesn't overwrite the original one, as it seems to replace both the bot.user.js and launcher.user.js

Example: Instead of AposBot, rename it to SJBot, or something like that.

**Comment by Drflash55** [comment]
Just noticed an issue with your bot.
The bot seems to split even when the bot is not on...

You should make a setting for it so that it doesn't split when the bot is currently turned off, because that causes the cell to split in the direction that your mouse is pointing in, which makes you more of a target for larger cells.
Because, this makes it so that you need to have the bot on all the time in order the splitting function to be successful, which is bad.

What's also bad is that it splits without taking into account the dangers around it. If there's a big cell that can eat you in your current state, the bot splits to eat the other little cell, while the big cell can just simply split to eat you.

Just things for you to consider.

**Comment by Apostolique** [comment]
He used the function split, that function shouldn't split when the bot is turned off already. Were you in follow mouse mode?

**Comment by SJMakin** [comment]
I removed the toggle check during some debugging and forgot to put it back in. The splitting stuff isn't really ready yet, but I appreciate the feedback.  Any ideas about the original question?

**Comment by Apostolique** [comment]
There isn't anything that will tell you that you can merge back. There are two ways that that you could use to know if you can merge back:
1) Know the right formula.
2) Indirectly figure it out by checking if the cells are overlapping. (Side effect of merging.)

**Comment by henopied** [comment]
```
this.isMerging(cell1, cell2) {
    var dist = this.computeDistance(cell1, cell2) - (cell1.size + cell2.size);
    return dist <= -40;
}
```
I have not tested this but it should work.

**Comment by SJMakin** [comment]
Looks pretty good - thanks.  I will test and let you know how it goes.

**Comment by henopied** [comment]
BTW, my patch is now in the code

**Comment by SJMakin** [comment]
By re-enabling the loop on players it works a lot better.  Not great but it will do.  I have added some checks on when to split and I am quite happy with the results.  Thx.

**Comment by Drflash55** [comment]
@SJMakin, there is still more work to be done...

If you can implement a cooldown feature on it, that would be nice.
When it detects a nearby cell that it can split, it splits more than once, completely eliminating the chances of being able to eat the cell it chased after.
Having a cooldown that lasts about a second will make sure that the key presses don't get sent out too quickly.

Just little features you can add! ;)

**Comment by SJMakin** [comment]
@Drflash55 You can configure the split (and shoot) 'cooldown' in the launcher around lines 1300.  
@henopied I implemented the code, but had to change -150 to -50 to get decent detection

I still have a small bug where viruses are included in the merging calculation but I can see it working.

**Comment by henopied** [comment]
do something like
 ```
if(check.isVirus()){
    continue;
}
```

**Comment by Drflash55** [comment]
@SJMakin
Would this be it?

``setTimeout(split, 0);``

**Comment by SJMakin** [comment]
Ah I didnt know bout the isVirus call - thanks

**Comment by SJMakin** [comment]
No! Its in the launcher.  Its the line: splitCooldown = 100,

**Comment by Drflash55** [comment]
@SJMakin 
Aaaaah...

Forgot about that!
XD

**Comment by henopied** [comment]
@Drflash55 it is ms

**Comment by Drflash55** [comment]
@henopied 
Thanks!
I'm adding it to the code now.

**Comment by henopied** [comment]
![image](https://cloud.githubusercontent.com/assets/13500516/10269954/9d948390-6aa9-11e5-815a-4de0afa2f894.png)
wat how did you post in the past in the future..

**Comment by Drflash55** [comment]
@henopied 
'cuse me, what?

**Comment by henopied** [comment]
@Drflash55 look carfuly at your post right after sjmakin's post

**Comment by Drflash55** [comment]
@henopied I know of what I saw, but for me it's perfectly fine.
Your screen didn't send the last one first before the first one.

**Comment by Apostolique** [comment]
Programmers man
