### ISSUE TITLE
Suggestion - Custom parameters in AposLauncher

### ISSUE THREAD

**Issue by caiosm1005** [Apostolique/Agar.io-bot#425]
Bots would be enriched if we could add per-bot **custom parameters** to AposLauncher.

For example, let's say my bot has the following `float` variables:

* Aggressiveness
* Cautiousness
* Agility

These parameters could be added to AposLauncher as a way to customize my bot's traits. Something like the image below:

![AposLauncher with parameters](https://cloud.githubusercontent.com/assets/4460538/10268292/7dd454b4-6a8a-11e5-9ee3-2f703e7adc11.png)

Since the **custom parameters** would be defined in bot.user.js, each bot would have its own set of custom parameters, or none if not used, so it would be non-breaking for current bots.

What do you think?

**Comment by Apostolique** [comment]
I want that.

**Comment by caiosm1005** [comment]
I'm making a PR with this feature.

Custom parameters are defined in the bot with the name `customParameters`. Here's an example of a bot with `speed` and `aggressiveness` parameters:

## Example

    function AposBot() {
        this.name = "AposBot " + aposBotVersion;
        this.customParameters = {
            speed:          { value: 1.0, min: 0.0, max: 1.0, type: "range", step: 0.2, label: "Speed" },
            aggressiveness: { value: 70.0, min: 0.0, max: 100.0, type: "number", step: 1.0, label: "Aggressiveness" },
        };

        this.mainLoop = function() {
            console.log( "My speed: " + this.customParameters.speed.value );
        }
    }

**Comment by Apostolique** [comment]
That looks pretty good.
