### ISSUE TITLE
Uncaught TypeError: $.ajax is not a function

### ISSUE THREAD

**Issue by caiosm1005** [Apostolique/Agar.io-bot#427]
In the latest commit, I'm getting an exception in [this line](https://github.com/Apostolique/Agar.io-bot/blob/master/launcher.user.js#L2480).

It should be `window.jQuery.ajax` instead of `$.ajax`

**Comment by henopied** [comment]
Yea he is currently working on this problem

**Comment by Apostolique** [comment]
It's fixed.
