### ISSUE TITLE
It keeps trying to go show the escape menu and the screen is gray

### ISSUE THREAD

**Issue by TSCGCobra043** [Apostolique/Agar.io-bot#429]
no matter how many times I press play the screen stays gray and then returns to the mass options

**Comment by Drflash55** [comment]
Sorry, I'm having troubles understanding this...

When you're talking about the 'escape menu', do you mean the menu that pops up when you load up Agar.io and when you press the ESC key?
I need more details on the matter to understand the real problem here.

**Comment by QuesinTTT** [comment]
I have this same problem, when you press play it just fade the screen and open settings menu agen. if i refresh the site many times i get rid of it.

**Comment by TSCGCobra043** [comment]
yes it's the menu after the ESC key and it is quite annoying. How do I get rid of it?

**Comment by Apostolique** [comment]
I'd like to see a screenshot of what you see.

**Comment by PixelMaster3D** [comment]
Probably a video since of what we're trying to see is that the screens comes back up.

**Comment by 20zinnm** [comment]
One moment, I'll get footage.

**Comment by htownclyde** [comment]
I'm also having the same problem, when I click "Play" the bot will start, but then the screen will turn grey and the menu will appear again.

**Comment by jbegoniajr** [comment]
Bandaid Fix...

Replace Line 2599: window.refreshTwitch();
With: //window.refreshTwitch();

**Comment by henopied** [comment]
So it is a problem with his twitch checker?

**Comment by Apostolique** [comment]
It's not.

**Comment by htownclyde** [comment]
I deleted everything in the script relating to twitch. Bot works now, thanks

**Comment by jbegoniajr** [comment]
@htownclyde

Glad you got it working. My record mass size with bot is 1599 without a single split on FFA.

@Apostolique

Quality work! I really appreciate it! Thank You!

**Comment by Apostolique** [comment]
No problem! What did I do though?

**Comment by htownclyde** [comment]
![screen shot 2015-10-23 at 3 28 31 pm](https://cloud.githubusercontent.com/assets/15204046/10704330/c3356e92-799b-11e5-8e85-088504da54eb.png)
This is my best run, with a few splits. Great bot!

**Comment by sdaitzman** [comment]
I still have the same error. How do I fix it?

**Comment by jbegoniajr** [comment]
Ok so I was mistaken on my previous post about twitch. Seems that has nothing to do with this issue, please disregard that post. problem not solved!

**Comment by muratlahur** [comment]
No more blue screens, no more crashes, no more stuttering, no more ads . . . .

Little Smart Dot release date announced to be 20th Dec. can't wait 
it even comes with it's own fancy subdomain lol :P 

http://agar.strlbs.com

**Comment by Drflash55** [comment]
Don't know if the problem was solved or not...
Closing just in case...
