### ISSUE TITLE
alternative multicell avoiding mechanics

### ISSUE THREAD

**Issue by henopied** [Apostolique/Agar.io-bot#434]
Your current no good angles has a flaw, it goes to the farthest cell but once it is near it that is no longer the farthest cell so it just circles around to its _death_ my alternative is create a point at every intersection of the circles and find the nearest point that isn't obstructed by another cell or going to be obstructed (found by using velocity) or is inside of another circle and if all points are obstructed try and reduce all threat circles to size+75 besides 2.6 to 4.5 (high split liklyhood range) to get out and if not even that creates an opening then it does the old behavior with the blue line that is now commented out

**Comment by henopied** [comment]
@Apostolique ?

**Comment by Apostolique** [comment]
I'll write a proper response later. Don't bother bumping your post, I read this already.

**Comment by Apostolique** [comment]
Okay, sorry for the late reply. Essentially, the idea behind the current avoiding mechanism is this:
![Evading algorithm](http://i.imgur.com/iTC77PM.png)

As you go towards the furthest guy, you are likely to find an opening.

**Comment by henopied** [comment]
![untitled drawing 4](https://cloud.githubusercontent.com/assets/13500516/10559001/5e577ca8-74ab-11e5-8cba-bae376c86cc5.png)
this is what I see happening

**Comment by Apostolique** [comment]
I thought about a possibly much better algorithm. No idea if it will work, but I'll write it down soon enough. It works perfectly in my head at least.

**Comment by muratlahur** [comment]
No more blue screens, no more crashes, no more stuttering, no more ads . . . .

Little Smart Dot release date announced to be 20th Dec. can't wait 
it even comes with it's own fancy subdomain lol :P 

http://agar.strlbs.com

**Comment by ErmiyaEskandary** [comment]
Apostolique made enemies be partly obstacles when there are too many of them around so it's easier to run around them. With the normal enemy code, you just run in the direction opposite to them. When there are too many enemies, you can't run in all directions at the same time. But if you are in the obstacle zone instead, you can run around them.
