### ISSUE TITLE
multiple cells to control 

### ISSUE THREAD

**Issue by Titaniumtown** [Apostolique/Agar.io-bot#437]
you would make is so the bot would use split parts of the players cell independent and make them feed the biggest part if that's possible thx :)

**Comment by abalabahaha** [comment]
There's a function called search. It's very helpful.

Individual cell control is not possible anymore.

**Comment by Titaniumtown** [comment]
oh ;(

**Comment by Titaniumtown** [comment]
xD

**Comment by Titaniumtown** [comment]
Apostolique can u add the feature?

**Comment by Apostolique** [comment]
Nope :(

**Comment by Drflash55** [comment]
The only way to get this back is to use an older version, but because Agar.io updates, it's most likely obsolete.
You can try to add the function back in, but it might not work as expected. Compatibility issues and such.

**Comment by Apostolique** [comment]
Older versions won't work. That feature was removed by the creator of Agar.

**Comment by Drflash55** [comment]
@Apostolique Oh, sorry.
Didn't know we were talking about an Agar.io function.
