### ISSUE TITLE
trying to approach food in the virus

### ISSUE THREAD

**Issue by jovanshelomo** [Apostolique/Agar.io-bot#443]

**Comment by jovanshelomo** [comment]
my cell is bigger than the virus but The bot is trying to eat food in the virus 
*sorry for my worst english*

**Comment by Drflash55** [comment]
So, the issue here is that the bot is trying to go after food that's inside the virus, but the cell is big enough to get spiked...
I think @Apostolique could add a function that ignores food that are placed inside of viruses, when you are at danger of getting spiked.

**Comment by Apostolique** [comment]
I meant to do that a while ago. I'll add that to my todo list.

**Comment by jovanshelomo** [comment]
Thanks @Apostolique i need it

**Comment by zakamanden** [comment]
@Apostolique  how does feed to work
