### ISSUE TITLE
Agar.io got freaking updated

### ISSUE THREAD

**Issue by DarkyLP** [Apostolique/Agar.io-bot#45]
Dear Maker of this Super Cool Hack. Hoperfully you read this fast. So i think that Agar.io just got updated and your Super Cool Hack doesn't work anymore (Image: : http://puu.sh/i7bIH/3e023f182a.png). Read this Story (if you want):  I was searching for a Hack/Bot for Agar.io then i found a Video (not this Video). and it actually worked. i posted it on another video, where you "must" like comment subscribe or something and then he sends you the hack, yeah so i wanted that the Viewers dont get ripped off. The Next time i was on agar.io, well this happend: http://puu.sh/i7bIH/3e023f182a.png.
Greetings from Switzerland (i was from Switzerland all along m8)

**Comment by SuperSplite** [comment]
yeah, this is happening witch me too

**Comment by i9w** [comment]
Same

**Comment by Apostolique** [comment]
Update to the latest version.

**Comment by DarkyLP** [comment]
Thx :)
