### ISSUE TITLE
Skype

### ISSUE THREAD

**Issue by DarkN3ss61** [Apostolique/Agar.io-bot#450]
You haven't been replying to any of my messages, why?

**Comment by Evanito** [comment]
I don't think this kind of issue goes here.

**Comment by DarkN3ss61** [comment]
@Evanito  I know, but there is no other way to get in contact with him. It will be removed as soon as he sees it

**Comment by Apostolique** [comment]
I'm not at home for the week.

**Comment by MastaCoder** [comment]
@Apostolique Might want to close this :D

**Comment by Drflash55** [comment]
This is an invalid issue...
