### ISSUE TITLE
Won't start with right mass

### ISSUE THREAD

**Issue by Danik2212** [Apostolique/Agar.io-bot#451]
The bot always start with a mass of 10 instead of my mass from facebook. When I check with esc if I really am connected it says I am but the bot always starts with a mass of 10. I tried refreshing 100 times, tried going on linux and tried changing the url to agar.io/?.

**Comment by henopied** [comment]
I belive apos needs to update his launcher to the new agario client version to fix these issues

**Comment by Apostolique** [comment]
You probably press the start button too fast.

**Comment by Danik2212** [comment]
I waited 15 minutes before pressing start, still the same result

**Comment by Apostolique** [comment]
If you are using the loader, don't use it.

**Comment by Danik2212** [comment]
Fixed the problem, thanks

**Comment by Apostolique** [comment]
Nice!
