### ISSUE TITLE
Login dialog pop back within seconds

### ISSUE THREAD

**Issue by r7lemieux** [Apostolique/Agar.io-bot#453]
I can play for a few seconds and the login window pops up again. The game is still going on with my blob. The login window covers the middle of the page. It appear to be modal as the page does not respond to my keystrokes anymore.

Thanks!

**Comment by Apostolique** [comment]
I'm writing a fix for this, but my new code is doing a lot more stuff than before. Not sure when I'll have the fix in.

**Comment by henopied** [comment]
It seems like there should be some build server of sorts that takes the agar main out and then patches it with your launcher modifications

**Comment by Apostolique** [comment]
My fix is even more insane than that.

**Comment by r7lemieux** [comment]
Thanks! I really like the app.

**Comment by riccardosimo** [comment]
Apos the best :+1: u.u

**Comment by ErmiyaEskandary** [comment]
Fixed according to Apostolique.
