### ISSUE TITLE
Not gaining any xp

### ISSUE THREAD

**Issue by Rufus66** [Apostolique/Agar.io-bot#458]
Just started using it today, xp is gained normaly when the script is disabled.
While it is running and I press esc it shows my facebook profile/level/xp.
Could it be that when you die it doesn't go back to the normal start screen?

**Comment by henopied** [comment]
get the bot and launcher separately then disable the loader then what happens?

**Comment by wahm22** [comment]
@henopied
Hi i was looking you
Can i have your skype or facebook ?

**Comment by wahm22** [comment]
@henopied
or add me 
live:Pro_Sauron

**Comment by jacob2012335** [comment]
Why were you looking for me?

**Comment by wahm22** [comment]
@jacob2012335 lol not u 

i'm talking @henopied

**Comment by Drflash55** [comment]
There are times where the Facebook application doesn't work, so just keep trying to see if it will work...

**Comment by aculaza** [comment]
im having the same issue, it gets exp when i disable the script but when its on even if i eat mass myself, i dont get xp... it shows im logged in... ive been using for about 4 days now and this problem just occured today so im confused

**Comment by ZizzyDizzyMC** [comment]
Same here no xp.  Using the bot there is no way to login either it appears.

**Comment by defaultbr** [comment]
Up, still not gaining any xp, even disabling the launcher or other

I see that when the server port ends with 03 IT DOESNT GET ANY XP

and ifs end with 1503, 1504 you won (but must disable the bot)

**Comment by Drflash55** [comment]
Hmm... Seems like a problem...

@Apostolique, can you confirm that people are not able to gain any Facebook XP when you play Agar.io using AposBot?
