### ISSUE TITLE
Can you create me a feeder bot?

### ISSUE THREAD

**Issue by AmazingGamerBoy** [Apostolique/Agar.io-bot#460]
Hey apos, can you create me a local agario feeder bots that spawn bots that make me bigger? Need as many bots as I can get at least 150. Ready to pay $150 USD = $200 AUD

**Comment by AmazingGamerBoy** [comment]
Anyone willing to help me create an agario suicide/feeder bot with over 150 bots? This needs to be a local script. It would be fine to edit another script such as pulviscriptor's. Will pay a bit of money if you want (but just a bit). Add me on skype to talk about this: Agario-Lord
My GitHub Account: AmazingGamerBoy

**Comment by Drflash55** [comment]
Welp, you can't rely on me...

I don't know even the slightest bit of JS.
I only understand how to edit certain lines in a code, with the assistance of others...

**Comment by MastaCoder** [comment]
My question is why you would pay someone >$100 for bots in a web browser game...

**Comment by davidmann4** [comment]
I made a github repo for feeder bots: https://github.com/davidmann4/agario-feeder-bot

**Comment by jhagrid77** [comment]
@davidmann4 Can that be done on Linux? or just Windows?

**Comment by davidmann4** [comment]
both check my repo

**Comment by jhagrid77** [comment]
I was just wondering if it was the same instructions, looks like it.

**Comment by Andrews54757** [comment]
Well, i created a private server code that has a ability to spawn feeder bots without a client side extention at https://github.com/AJS-development/Ogar-unlimited/tree/master/src

**Comment by ErmiyaEskandary** [comment]
https://github.com/Apostolique/AposFeedingBot
