### ISSUE TITLE
I get this screen

### ISSUE THREAD

**Issue by RishabSwift** [Apostolique/Agar.io-bot#470]
I keep getting this blue screen:

<img width="1440" alt="blue screen" src="https://cloud.githubusercontent.com/assets/15897093/11316126/1604e93a-8fcd-11e5-91e7-9952827e5ac9.png">

It keeps doing this and I don't know why. It does it on Firefox, chrome and opera all. I'm Using a mac.

**Comment by Apostolique** [comment]
It's a bug in the current version. I'm almost done fixing it, but I had other projects that needed to be worked on first.

**Comment by RishabSwift** [comment]
Oh okay, thanks. Any idea when it will be released?

**Comment by Apostolique** [comment]
Hopefully today.

**Comment by RishabSwift** [comment]
Awesome! I've been refreshing like crazy!

**Comment by Apostolique** [comment]
I'm almost done, but I still have Javascript errors.

**Comment by PixieScr** [comment]
I have this problem too and waiting for fix :)

**Comment by aryan4144** [comment]
and some Chinese on the blue screen.l

**Comment by riccardosimo** [comment]
LOL you're the best apossssssss <3

**Comment by rogerb831** [comment]
I'm running into this on the feeder bot an the pop bot also. Maybe its related to the launcher if they are all suffering from it?

**Comment by rogerb831** [comment]
I just confirmed that this problem is not happening with launcher ver 4.146

**Comment by Drflash55** [comment]
A duplicate of #452.

**Comment by Drflash55** [comment]
@Apostolique You plan on releasing it today?
Or are those JS errors holding you for longer than you expected?

**Comment by Apostolique** [comment]
Oh..... I was still stuck on my Javascript errors, but your comment just gave me a massive idea. Turns out my problem is solved. Just need to finish putting it all together.

**Comment by malickf** [comment]
I have the same problem

**Comment by muratlahur** [comment]
No more blue screens, no more crashes, no more stuttering, no more ads . . . .

Little Smart Dot release date announced to be 20th Dec. can't wait 
it even comes with it's own fancy subdomain lol :P 

http://agar.strlbs.com

**Comment by Botlike420** [comment]
Happy to found your bot but i also am running into the blue and greenscreenproblem. Also would it be possible to let the bot go after bots and smaller players?

**Comment by PFCKrutonium** [comment]
Also still running into this error. :/

**Comment by Drflash55** [comment]
Use #452 for discussions on this bug.
