### ISSUE TITLE
Dosn't work on Agar.io Sub-Pages

### ISSUE THREAD

**Issue by BitNetwork** [Apostolique/Agar.io-bot#474]
Hi there @Apostolique! A update for Agar.io was released a while ago which added links in the bottom left hand corner.
These link lead to the 4 game modes in Agar.io, but they differ from the host (www.agar.io). The links are www.agar.io/ffa/, www.agar.io/teams/, www.agar.io/experimental/, www.agar.io/party/. The greasemonkey/tampermonkey script only runs on the host page (www.agar.io). Here is a small snippet: 

    // @description Grabs latest versions of the bot scripts automatically.
    // @include     http://agar.io/ < only targets host
    // @version     1.3

But with a small modification, you can target all the pages from that domain.

    // @description Grabs latest versions of the bot scripts automatically.
    // @include     http://agar.io/* < now targets all pages from host
    // @version     1.3

**Comment by Apostolique** [comment]
Isn't it already like that?

**Comment by BitNetwork** [comment]
All except [`loader.user.js`] (https://github.com/Apostolique/Agar.io-bot/blob/master/loader.user.js#L5).

**Comment by Drflash55** [comment]
@BitNetwork No one really uses loader.user.js, IMO.
I can just easily go into my extensions dashboard and update the script easily...

By the way, the last time I used loader.user.js, my game broke, very badly.
So, I stuck with just launcher.user.js and bot.user.js
