### ISSUE TITLE
Flat out doesn't work

### ISSUE THREAD

**Issue by Sammycat1** [Apostolique/Agar.io-bot#475]
I don't know why, I have even checked to see if my extensions were working then turned off all the other extensions except for tamper-monkey, it still doesn't work. :(

**Comment by Drflash55** [comment]
Did you check to see if you have both the launcher.user.js and the bot.user.js?

If you have both of those, the bot will work as expected...
Also, make sure AdBlock is turned off, or excluded from Agar.io so that the bot can work properly...

**Comment by Drflash55** [comment]
Issue has not been active within a month, thus it's being closed.
