### ISSUE TITLE
bluescreen

### ISSUE THREAD

**Issue by lizangel19** [Apostolique/Agar.io-bot#478]
moving but bluescreen still playing

**Comment by Drflash55** [comment]
Duplicate issue of #452

**Comment by muratlahur** [comment]
No more blue screens, no more crashes, no more stuttering, no more ads . . . .

Little Smart Dot release date announced to be 20th Dec. can't wait 
it even comes with it's own fancy subdomain lol :P 

http://agar.strlbs.com
