### ISSUE TITLE
Keeps popping main menu

### ISSUE THREAD

**Issue by ghost** [Apostolique/Agar.io-bot#479]
It keeps launching as if I'm pressing escape all the time.

**Comment by sk1v3** [comment]
Make sure to install both bot.user.js and launcher.user.js.. if you have loader.user.js it will do that

**Comment by muratlahur** [comment]
No more blue screens, no more crashes, no more stuttering, no more ads . . . .

Little Smart Dot release date announced to be 20th Dec. can't wait 
it even comes with it's own fancy subdomain lol :P 

http://agar.strlbs.com

**Comment by tsteinholz** [comment]
@sk1v3 What are you saying? You need to have them both but the launcher causes the problem?

**Comment by ErmiyaEskandary** [comment]
#522
