### ISSUE TITLE
The bug or what?

### ISSUE THREAD

**Issue by Olotosik** [Apostolique/Agar.io-bot#48]
This is what i can see in game ;___;

![bez tytulu](https://cloud.githubusercontent.com/assets/12687325/7903963/35d75860-07ec-11e5-9583-27a734ea9589.png)

**Comment by x7rgaming** [comment]
same :confused:

**Comment by Piehthyte** [comment]
Yeah this was happening to me earlier. Disable the bot and play normal until it is fixed :P
Worked pretty well for me :D I think the creator of agar put anti-bot stuff in the coding :/ either that or its a bug with the bot.

**Comment by Apostolique** [comment]
Update to the latest version.
