### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by shyon-k** [Apostolique/Agar.io-bot#481]
Can you leave the bot running overnight to gain xp? Or do you have to keep refreshing the browser. When I leave it running overnight it says that the launcher script has become unresponsive.

**Comment by Apostolique** [comment]
I never got around to fixing all the latest bugs correctly.

**Comment by shyon-k** [comment]
Thanks. The bot doesn't crash overnight if you disable the launcher.

**Comment by nguyenvanduocit** [comment]
Try my bot : https://github.com/nguyenvanduocit/Agar.io-Bot It's Apos' bot, but I implement it as chrome extension, and your can use the server for feeder bot.

**Comment by shyon-k** [comment]
what's the difference in your bot. Do you have to create or join a party server?

**Comment by riccardosimo** [comment]
@Apostolique how many time we have to wait untill your definitive fix? XD

**Comment by Apostolique** [comment]
I'm done with my exams now.

**Comment by riccardosimo** [comment]
ah okok u.u XD

**Comment by muratlahur** [comment]
Little Smart Dot release date announced to be 20th Dec. can't wait

**Comment by muratlahur** [comment]
dum dum dum  .. .

**Comment by jamaalo** [comment]
ok

**Comment by ErmiyaEskandary** [comment]
Fixed according to Apostolique.
