### ISSUE TITLE
Making a custom bot.

### ISSUE THREAD

**Issue by DrTheGoat** [Apostolique/Agar.io-bot#488]
I'm trying to make a custom bot but I dont know where to put the code for my bot.

**Comment by Win-slow** [comment]
Not trying to be harsh, but the code is pretty well commented and there are only three files to go through. If you can't figure it out yourself you might want to read up on javascript programming.

**Comment by DrTheGoat** [comment]
Yeah I figured it out a while ago, I thought the script goes into the launcher...

**Comment by muratlahur** [comment]
I am pretty sure he refers to "make your own bot"  approach from apos, which I'll agree has absolutely no indications what so ever .I've made my own bot, and that included completely re-writing apos bot..
no easy way around..

ie, there is no slot for you to drop your code , and it shows up in the bot list per se

**Comment by DrTheGoat** [comment]
@muratlahur I'm sorry to tell you but you should of put your code in the user.bot.js

**Comment by muratlahur** [comment]
right . .now once again but in english this time ??

**Comment by DrTheGoat** [comment]
Yep

**Comment by N1C39UY** [comment]
You have 3 files... thats the name of one of them lol it is english
Op 21-dec.-2015 11:23 schreef "DrTheGoat" <notifications@github.com>:

**Comment by muratlahur** [comment]
no it's not ,

bot.user.js is the name fyi (an abbreviation used to say "for your information" ) 

and now that resolved, the rest still doesn't make sense , oh wait . . .
*activating gibberish decoder

ah ok , he meant put your code in the bot user script !!

ah really .. .DOOH .. why haven't I thought of that  . . .

as a matter of fact why have I bothered calling my bot "Little Smart Dot" seems to be a waste of effort around here...
