### ISSUE TITLE
Facebook login stopped working

### ISSUE THREAD

**Issue by sunny127** [Apostolique/Agar.io-bot#489]
I used the bot for several days now, and suddenly today, the facebook login is not working when the bot is on. When I turn the bot script off, everything is working fine. Can you please update the bot so it works with facebook once again?

**Comment by Auroxxe** [comment]
I'm having the same problem.. it occurred today and yesterday it was perfectly fine, i've tried everything, turning on and off the script, reinstalling it, it's not working at all!

**Comment by michal7272** [comment]
Same problem, It logs me out when the bot is on. Please help :)

**Comment by shyon-k** [comment]
Same problem, I can't log in with the scripts running. This is the bot that gains XP for me, so it sucks. I tried an agario bot extension on chrome by gamerlio, but it didn't level up. :/

**Comment by shyon-k** [comment]
@Apostolique

**Comment by SHJ234** [comment]
Hi,
Is this fixed yet or not ?

**Comment by shyon-k** [comment]
@SHJ234 No, not yet

**Comment by Drflash55** [comment]
This issue has not been active within a month. Issue is being redirected to #537.
This is now closed.
