### ISSUE TITLE
bug?

### ISSUE THREAD

**Issue by x7rgaming** [Apostolique/Agar.io-bot#49]
i just installed the bot and in youtube comments i see other people also have this problem where all we see is this:

![agarbotpic](https://cloud.githubusercontent.com/assets/8596803/7904471/371a546a-07b1-11e5-94b7-6e2625ce114c.png)

DarkN3ss said it could be from the agar update.
also the leaderbords still work. help?

**Comment by cdh10** [comment]
Any idea when it's going to be updated?

**Comment by Apostolique** [comment]
I've updated the bot, but there is currently a weird bug that breaks it even more. Trying to pin it down, but it will probably take some time.

**Comment by DarkN3ss61** [comment]
@Apostolique Go on skype and I will give you more info

**Comment by Apostolique** [comment]
Get latest version.
