### ISSUE TITLE
Combat enhancements

### ISSUE THREAD

**Issue by JBoughter** [Apostolique/Agar.io-bot#50]
Basically, my idea was this,
* Check for a possible split kill, don't do it if there are threats nearby. Check if you can still eat what you are chasing with the other half of your mass.
 * After a split kill, focus on running away and eating food until you merge.
* Check if threats can split kill you, such as see if their mass will actually hurt you (the mass of their split cells), and if so, prioritize an escape from those rather than those that will be unable to eat or able to eat in an attempt to split kill you.
 * Though, if at a close enough range, completely prioritize both.
* If below the mass of a virus, check if threats near you are above the virus' mass, and if so, hide in the virus until they are gone.

**Comment by i9w** [comment]
The way I see it, the bot is already worked to favor evading. And that's great improvement, Although I wish they would return the "threat lines" as they were better in the previous version.
