### ISSUE TITLE
its not working!!!!!!!!!!!!!!!!!!!111111111111111 fixxxxxxxxxxxxxxxx thissssss

### ISSUE THREAD

**Issue by orginal40255** [Apostolique/Agar.io-bot#506]

**Comment by Drflash55** [comment]
You didn't include enough details to describe your problem...

**Comment by MRebhan** [comment]
Can't tell if troll, or just stupid. Probably troll.

**Comment by Drflash55** [comment]
Issue has not been active within a month, thus it's being closed.
