### ISSUE TITLE
Large blob bug.

### ISSUE THREAD

**Issue by BordChinChin** [Apostolique/Agar.io-bot#507]
Hello, First of all i love using your bot. But, There is one problem: I saw this in earlier thread and you seemed to fix it, could you to it for this version too?  screenshot: https://gyazo.com/50d6f2fbdb8af850fde75cb8dfedf8f0 
If you could fix it it would be Fantastic!
Sorry for bad english, Its not my native language. :)

**Comment by Drflash55** [comment]
This issue has already been noticed...
Duplicate of #452
