### ISSUE TITLE
not working for dolphin browser

### ISSUE THREAD

**Issue by jovanshelomo** [Apostolique/Agar.io-bot#508]
dolphin show pop-up like this:
Tampermonkey detected a problem which prevents the add-on from running properly.
Please report this to support@dolphin.com if it persists. Thanks. Close

**Comment by Drflash55** [comment]
Huh...
A browser for iOS...

Not sure if @Apostolique made this useable with the Dolphin Browser...

Heck, I've never even heard of this browser before.

**Comment by jovanshelomo** [comment]
You can see in bot.jlynx.net it has an option for Android and its need dolphin browser.
