### ISSUE TITLE
Agario Main Menu refuses to go away

### ISSUE THREAD

**Issue by wertercatt** [Apostolique/Agar.io-bot#522]
The main menu for Agario refuses to go away. I click "Play" and I can see the bot for a little bit, but the menu always comes back.

**Comment by boomboompower** [comment]
@wertercatt try reloading the page.

**Comment by tsteinholz** [comment]
doesn't fix it

**Comment by boomboompower** [comment]
@wertercatt @tsteinholz That happens to me when I start the game before the bot is fully loaded, try reloading the page, waiting for a few secs (Like 10 secs) then try pressing play.

**Comment by The0nlyGamer** [comment]
Try disabling AposLuancher, worked for me.

**Comment by ErmiyaEskandary** [comment]
Fixed according to Apostolique.
