### ISSUE TITLE
so like no update ? -_-    getting real tired of waiting

### ISSUE THREAD

**Issue by pissedOffUser** [Apostolique/Agar.io-bot#533]

**Comment by Piehthyte** [comment]
You do know Apostolique isn't here to service you in paticular? Developers need time to do things and if they are busy then they are busy. Be paitent or make it yourself. Either way the issue really isn't needed so you should probably close it now.

**Comment by boomboompower** [comment]
@Piehthyte is right.
@pissedOffUser please close this issue.
