### ISSUE TITLE
suck my dick 

### ISSUE THREAD

**Issue by Danielhaltvik** [Apostolique/Agar.io-bot#534]
wtf is not work

**Comment by boomboompower** [comment]
It does work.

**Comment by pissedOffUser** [comment]
no it doesnt -_-

**Comment by Piehthyte** [comment]
For you, it doesn't. For everyone else it does! If you have an issue please file a proper issue report instead of being a temperamental child.

**Comment by pissedOffUser** [comment]
it does not work it is full of bugs and after about 100 seconds the whole screen turns blue

**Comment by boomboompower** [comment]
@pissedOffUser as this is not an issue/not in a way a issue should be reported. Please close this issue.

**Comment by Drflash55** [comment]
@pissedOffUser Yes, Apostolique is aware of the phantom bugs issue and hasn't found out a way to fix it just yet...
Because this issue is already made aware, I'll redirect this issue to the earlier issue made, and close it.
#452
