### ISSUE TITLE
New Version Detection

### ISSUE THREAD

**Issue by ZoltofLightning** [Apostolique/Agar.io-bot#54]
It has many problems with detecting enemies and the danger areas are often way too small. Every single time the bot dies, it has been due to it simply jumping head-first right into an oncoming enemy. It does not seem to be able to detect many of the larger cells.The danger areas are often way too small because the bot's cell will only run from enemies 10 times its size when it is halfway through getting eaten by it.

**Comment by Apostolique** [comment]
Will be fixed tomorrow.
