### ISSUE TITLE
i cant play agario 

### ISSUE THREAD

**Issue by ZEANER145** [Apostolique/Agar.io-bot#540]
it says my wifi is down but i can still google and stuff like that

**Comment by Drflash55** [comment]
Then, it must be a problem with your connection.
If you want further help, please add more details to explain your problem.

**Comment by coolharry2005** [comment]
mine says 403 forbidden

**Comment by Eisphoenix** [comment]
Maybe your firewall is blocking the connection, try to use a proxy/vpn.

**Comment by Drflash55** [comment]
Refer to what I said in issue 558.
https://github.com/Apostolique/Agar.io-bot/issues/558#issuecomment-200546653

**Comment by ErmiyaEskandary** [comment]
**I fixed this issue :)
Look here -  : #562**
