### ISSUE TITLE
Bot isn't working

### ISSUE THREAD

**Issue by PhoenixVortex** [Apostolique/Agar.io-bot#543]
I've tried reinstalling tampermonkey, reinstalling the scripts but whenever I go into agario and play, the bot just won't work.

**Comment by Drflash55** [comment]
Did you grab both bot.user.js, and launcher.user.js?

Those are required for AposBot to run properly.

**Comment by PhoenixVortex** [comment]
Yes I did.

On Thu, Feb 18, 2016 at 10:41 AM, Drflash55 <notifications@github.com>
wrote:

> Did you grab both bot.user.js, and launcher.user.js?
>
> Those are required for AposBot to run properly.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Apostolique/Agar.io-bot/issues/543#issuecomment-185420513>
> .
>



-- 
Epsilon Phoenix
LunarCore formerly SyrusCore DS
Co-Host
SE 24/7 LunarCore Decayed Long Term Server
Staff Member
Forum Administrator

**Comment by Drflash55** [comment]
Huh, whenever I go to play with the bot, it functions just fine, but the phantom blobs are the real problem I'm still having.

@Apostolique has been aware of this issue about 4 months prior, but either he hasn't found out a way to fix it, or he just simply stopped working on this project.

**Comment by bhawin** [comment]
yes , its not working for me as well

**Comment by PhoenixVortex** [comment]
I think its a compatibility issue.

On Fri, Feb 19, 2016 at 1:55 AM, bhawin <notifications@github.com> wrote:

> yes , its not working for me as well
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Apostolique/Agar.io-bot/issues/543#issuecomment-185707756>
> .
>



-- 
Epsilon Phoenix
LunarCore formerly SyrusCore DS
Co-Host
SE 24/7 LunarCore Decayed Long Term Server
Staff Member
Forum Administrator

**Comment by DJKOLBY** [comment]
it is a compatibility issue i got mine to work

**Comment by DJKOLBY** [comment]
[Agar.io-bot-master.zip](https://github.com/Apostolique/Agar.io-bot/files/138598/Agar.io-bot-master.zip)

**Comment by DJKOLBY** [comment]
[tmScripts (2).zip](https://github.com/Apostolique/Agar.io-bot/files/138605/tmScripts.2.zip)

**Comment by DJKOLBY** [comment]
this should work

**Comment by PhoenixVortex** [comment]
It still does not work... :(

On Sat, Feb 20, 2016 at 8:52 AM, DJKOLBY <notifications@github.com> wrote:

> this should work
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Apostolique/Agar.io-bot/issues/543#issuecomment-186376308>
> .
>



-- 
Epsilon Phoenix
LunarCore formerly SyrusCore DS
Co-Host
SE 24/7 LunarCore Decayed Long Term Server
Staff Member
Forum Administrator

**Comment by lancedikson** [comment]
yep, it's not working for me as well

**Comment by jhagrid77** [comment]
This is my problem:
1.) I go to agar.io
2.) The bot loads for a few seconds (I let it wait). OR I immediately click play.
3.) The bot disappears.

**Comment by PhoenixVortex** [comment]
@Apostolique is aware of this problem, I think he abandoned the project and
won't do any bug fixing, agar.io has been updated and the bot is rendered
incompatible with some user's systems.

On Sat, Feb 27, 2016 at 3:18 AM, jhagrid77 <notifications@github.com> wrote:

> This is my problem:
> 1.) I go to agar.io
> 2.) The bot loads for a few seconds (I let it wait). OR I immediately
> click play.
> 3.) The bot disappears.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Apostolique/Agar.io-bot/issues/543#issuecomment-189298600>
> .
>



-- 
Epsilon Phoenix
LunarCore formerly SyrusCore DS
Co-Host
SE 24/7 LunarCore Decayed Long Term Server
Staff Member
Forum Administrator

**Comment by Drflash55** [comment]
Refer to what I said in issue 558.
https://github.com/Apostolique/Agar.io-bot/issues/558#issuecomment-200546653

**Comment by ErmiyaEskandary** [comment]
**I fixed this issue :)
Look here -  : #562**
