### ISSUE TITLE
Compatibility with other sites?

### ISSUE THREAD

**Issue by andreas0607** [Apostolique/Agar.io-bot#544]
Is it possible to make the bot react with other sites such as "Csgocytosis.com"?
I tried putting it into tampermonkey and setting it to interract with the site aswell. but nothing happened.
Pls help=)

**Comment by Drflash55** [comment]
@andreas0607 @Apostolique has not made any changes on this in over 4 months...

Most likely this will not happen until the Phantom Blobs bug has been fixed.
