### ISSUE TITLE
Agar.io like games

### ISSUE THREAD

**Issue by IlikeToPlayGames** [Apostolique/Agar.io-bot#547]
I have using this for school and agar.io has been blocked. I found eat2paly.com and all i would like is a way to be able to do it on that.

**Comment by Drflash55** [comment]
This does not relate to the bot for Agar.io, as this is just a firewall issue your school has set up...

Try it at home instead, or you can request the school board administrators to unblock incoming port connections from, Agar.io, which is unlikely that will happen.

Other than that, not much else you can do, unless you used an online VPN site, which in most cases, schools have those blocked off.

**Comment by ZPERO** [comment]
If you have a smarphone, you can either play on that, or try and use it as a hotspot and connect to your hotspot. 
When I was in high school, I used an online proxy to go on blocked sites, but no javascript would work, so it was not really that useful.

**Comment by ErmiyaEskandary** [comment]
What do you mean by block ? Does it connect or does the website just not come up ?

**Comment by ErmiyaEskandary** [comment]
Refer to Drflash55's answer.
