### ISSUE TITLE
[Idea] Version Display

### ISSUE THREAD

**Issue by DarkN3ss61** [Apostolique/Agar.io-bot#55]
have the current version of the bot in the bottom right corner ("v0.2"). As well has having the bot check for updates every time it load up so you know if an update has been pushed out. This can simply be done by loading a txt file hosted on a website and checking if its current version is the same etc

I think this will have it a lot easier to know when an update is pushed out

**Comment by i9w** [comment]
We just need the zoom out feature, game is pretty unplayable

**Comment by DarkN3ss61** [comment]
Added the update check in a pull request

**Comment by DarkN3ss61** [comment]
Just need to have it show the current version now
