### ISSUE TITLE
os bots não nascem

### ISSUE THREAD

**Issue by AmorimDrain** [Apostolique/Agar.io-bot#550]

**Comment by Drflash55** [comment]
I'm not able to understand your language...

**Comment by Eisphoenix** [comment]
He says that the bots don't appear. I think he is is misunderstanding this script.

@AmorimDrain Este script nao é para fazer bots, isto so automatisa o teu jogo. :smile: 

**In English:** This script is for controll automatic your browsergame, not for spawning bots to feed you.

**Comment by Drflash55** [comment]
Now that I understand what he's asking, I can close this, as it's an invalid issue...
