### ISSUE TITLE
Agario Bot Problems

### ISSUE THREAD

**Issue by EbolaStran** [Apostolique/Agar.io-bot#551]
Hello I am sure you know about some of these problems but I have a list of them. The first problem is the main menu always keeps popping up every 2 seconds for me and it is pretty annoying that you have to keep pressing play. Another issue is the game freezing I know you think that it just may be agario but I turned off the mod and the issue stopped. Another issue is sometimes in the middle of a game the whole screens turns a random color like green. It is like a huge green blob ate me but I am still playing. Another problem is when I press play sometimes my blob does not spawn nothing is moving and it goes back to the main menu screen. So yes this mod is very very glitchy. Other than these problems the mod is great and not to be mean or anything with this paragraph but these are the issues.

**Comment by Drflash55** [comment]
Please refer to your own issue for the answer to this problem...
#549
