### ISSUE TITLE
I CANT PLAY

### ISSUE THREAD

**Issue by seawping** [Apostolique/Agar.io-bot#554]
really need help

**Comment by Drflash55** [comment]
You need to describe your problem in order for me to help you...

**Comment by Drflash55** [comment]
Refer to what I said in issue 558
https://github.com/Apostolique/Agar.io-bot/issues/558#issuecomment-200546653

**Comment by ErmiyaEskandary** [comment]
**I fixed this issue :)
Look here -  : #562**
