### ISSUE TITLE
NOT LOADING HELP!

### ISSUE THREAD

**Issue by aldengamein** [Apostolique/Agar.io-bot#559]
I NEED HELP PLEASE FIX THIS!

:( NOT WORKING ;-;

**Comment by xWistful** [comment]
I also have a problem where the screen will glitch and continently say connecting. The screen will flash and show the menu of the bot on the top left and flash back to a blank screen. please fix

**Comment by Drflash55** [comment]
Refer to what I said on issue 558.
https://github.com/Apostolique/Agar.io-bot/issues/558#issuecomment-200546653

**Comment by ErmiyaEskandary** [comment]
**I fixed this issue :)
Look here -  : #562**
