### ISSUE TITLE
Enable for https

### ISSUE THREAD

**Issue by x0x7** [Apostolique/Agar.io-bot#561]
Your include line for each of your scripts usually specifies something like:

    http://agar.io/*

By specifying the protocol you prevent people with httpseverywhere from using your bot.

I changed it to:

    http*://agar.io/*

I worked but you may consider omiting the protocol entirely.

This enabled the userscript but the script also caused issues connecting with their server.  Maybe that's something they did.  I'll make a seperate issue for that one.

**Comment by ErmiyaEskandary** [comment]
What issues ? Were the issues related with omitting the protocol or by changing it ?

**Comment by Drflash55** [comment]
@ErmiyaEskandary, you gave me 'a real run for my money'.

Notifications box was full of notices... Glad to see you're doing my job better.

**Comment by ErmiyaEskandary** [comment]
@Drflash55 :)

**Comment by ErmiyaEskandary** [comment]
> This enabled the userscript but the script also caused issues connecting with their server.

This is what happens.

**Comment by ErmiyaEskandary** [comment]
Chrome started glitching. Sorry.

**Comment by FliiFe** [comment]
Anyway, What's the matter with adsense ? What is it used for ?

**Comment by ErmiyaEskandary** [comment]
It doesn't even work now - adsense is for Google ads which Apos added in. It doesn't even work now.

**Comment by FliiFe** [comment]
@Apostolique I don't know what you think of that, but we should remove ads. It's definitely not in the open-source perpective... That's up to you

**Comment by ErmiyaEskandary** [comment]
@FliiFe Totally agree with you. I'm going to do that today. If he doesn't agree, he can always add it back in but he isn't even online so :(

**Comment by ErmiyaEskandary** [comment]
Issue fixed - will be added to the `master` branch soon. :)
