### ISSUE TITLE
It won't connect to a server

### ISSUE THREAD

**Issue by kennediellen** [Apostolique/Agar.io-bot#564]
When I turn the mod on, Agar.io will only say, "If you cannot connect to the servers, check if you cave some anti-virus or firewall blocking the connection."

**Comment by victornb** [comment]
Same here =/

**Comment by DARKESTXSWORD** [comment]
it's been doing the same for me

**Comment by DannyTeni** [comment]
Same here
Does anyone have a solution?

**Comment by victornb** [comment]
I've tested with windows and mac, with firefox and chrome. Its the same for all, if the bot is deactivated agar.io works normally.

**Comment by Mewgood** [comment]
Guess it's detected. We have to figure out how it is detected as the author abandoned the project :-)

**Comment by Drflash55** [comment]
This is already a known issue. Refer to what i said in issue #558.

**Comment by ErmiyaEskandary** [comment]
**I fixed this issue :)
Look here -  : #562**
