### ISSUE TITLE
Connection problems

### ISSUE THREAD

**Issue by shyon-k** [Apostolique/Agar.io-bot#572]
When I hit play, there is a white screen, and it just says connecting. I tried on mozilla, opera, and chrome. I can't log in either, which means no xp.

**Comment by ErmiyaEskandary** [comment]
Could you post a screenshot ?

**Comment by shyon-k** [comment]
@ErmiyaEskandary yes,

![capture](https://cloud.githubusercontent.com/assets/16218322/14590033/65d4b7ca-04b6-11e6-8b78-b4fd3a381afd.PNG)

**Comment by Drflash55** [comment]
It could either be a problem with your connection not accepting incoming port connections from Agar.io. You need to change some settings with your router, or contact your Internet Service Provider so they can unblock the incoming connections for you.

**Comment by Apostolique** [comment]
You probably need to wait a few hours. Sometimes agar starts blocking the connections.

**Comment by ErmiyaEskandary** [comment]
@shyon-k please close this issue if fixed

**Comment by shyon-k** [comment]
@Apostolique A few hours? Should I leave it running overnight? I tried at different time periods, but nothing changed.

**Comment by ErmiyaEskandary** [comment]
Refer to Drflash55's comment. I'm 100% sure it's that.

**Comment by ErmiyaEskandary** [comment]
If you get errors in your console, post them here.

**Comment by ejb1123** [comment]
```
agar.io/:449 Uncaught TypeError: Cannot read property 'send' of null
cdn.rawgit.com/Apostolique/Agar.io-bot/f06cde6260e0cefc4f629585fb2816c20d752d28/launcher.user.js?_=1461072934573:775 Uncaught TypeError: Cannot set property 'width' of undefined
```

**Comment by ErmiyaEskandary** [comment]
Are you using the loader ? I think I know what the problem is.

**Comment by FliiFe** [comment]
BTW, I can confirm this issue on chrome. (Got the same `Uncaught TypeError: Cannot set property 'width' of undefined`)

**Comment by ErmiyaEskandary** [comment]
Are you using the loader ?

**Comment by ErmiyaEskandary** [comment]
Because I'm using the separate launcher and bot file and I can verify it is working.

**Comment by ErmiyaEskandary** [comment]
@FliiFe brb gitter not working

**Comment by FliiFe** [comment]
It works on chrome, but only if you use tampermonkey. That doesn't make any sense to me

**Comment by FliiFe** [comment]
![capture du 2016-04-19 16-55-55](https://cloud.githubusercontent.com/assets/8740385/14643766/ef16194e-064f-11e6-8ffd-a7cebcdee9bf.png)

**Comment by ErmiyaEskandary** [comment]
Can you point me to what line in the code causes the problem ? Click on the link next to the error.

**Comment by FliiFe** [comment]
775

**Comment by FliiFe** [comment]
It's written (that's why I screened)

**Comment by ErmiyaEskandary** [comment]
Chrome debug error have different line numbers - that's why I asked

**Comment by ErmiyaEskandary** [comment]
I can't recreate this issue - can I have the line number ?

**Comment by ErmiyaEskandary** [comment]
What do you apart from Tampermonkey on Chrome ?

**Comment by FliiFe** [comment]
Just basic javascript script loading (jQuery)

**Comment by ErmiyaEskandary** [comment]
I think that's the issue - found that out when you were running the code from localhost

**Comment by ErmiyaEskandary** [comment]
You need to install the launcher and bot files

**Comment by ErmiyaEskandary** [comment]
@ejb1123 How are you loading the scripts ? loader ? bot and launcher ?

**Comment by FliiFe** [comment]
He is using the loader

**Comment by FliiFe** [comment]
@shyon-k How are you loading the scripts ? Using tampermonkey/greasemonkey ? If you use the loader, I recommend using the two separate files instead (`bot.user.js` and `launcher.user.js`)

**Comment by shyon-k** [comment]
@FliiFe I tried on both Firefox and Chrome, but I get the same results. Tampermonkey for Chrome, and Greasemonkey for Firefox.

**Comment by shyon-k** [comment]
@FliiFe Thank you, I tried on Both browsers but it seemed to work on only  Firefox.

**Comment by FliiFe** [comment]
@shyon-k It should work on chrome, if you use tamperMonkey (which uses `EcmaScript`)
