### ISSUE TITLE
Map Borders

### ISSUE THREAD

**Issue by muratlahur** [Apostolique/Agar.io-bot#581]
where are the map borders ??? My bot thinks it lives in a letterbox lol :P 

![screen shot 2016-04-19 at 07 48 09](https://cloud.githubusercontent.com/assets/14038239/14624284/7f32fa9e-0603-11e6-9d3e-bf51ba235d3f.png)

**Comment by muratlahur** [comment]
and because the letter box situation the wall code completely cripples the bot..Probably the reason why the wall code just got removed in an update.. but then this makes the bot a sitting duck around walls and especially corners..

this is not the way to go .. we need the ACTUAL map borders..

**Comment by ErmiyaEskandary** [comment]
We CAN'T have the actual map borders as agar.io prevents us knowing where the borders are unless we are close to them.

**Comment by muratlahur** [comment]
you can . it just takes one visit to one corner...The map is a predefined square.. all it takes is one visit to one side.. then you know where one wall is and automatically you know where all walls are..

this is what I meant in my email with the thinking bit . . .
