### ISSUE TITLE
opCodes don't work !

### ISSUE THREAD

**Issue by muratlahur** [Apostolique/Agar.io-bot#582]
When I try to run opCodes in the bot I get this !! But they used to work before !
![screen shot 2016-04-19 at 07 53 20](https://cloud.githubusercontent.com/assets/14038239/14624327/eb471cce-0603-11e6-8145-8dde017e3fad.png)

**Comment by ErmiyaEskandary** [comment]
Make a new issue.

**Comment by ErmiyaEskandary** [comment]
If you're sure it's Apos's bot problem, not yours.

**Comment by ErmiyaEskandary** [comment]
Not an error in current bot. Alternative bot issue. Closed due to being invalid.
