### ISSUE TITLE
Map Borders !!!!!!!

### ISSUE THREAD

**Issue by muratlahur** [Apostolique/Agar.io-bot#583]
The bot CRUCIALLY needs to know where it is ..
This is done by finding ANY corner and since we know the size of the square that the map is , the rest is very easy .. 

Do NOT close this issue without it being fixed like you did to the other as I find that very immature .. 

now.. to work u !

**Comment by muratlahur** [comment]
oh btw I forgot the beautiful letterbox screen shot .. 

You make people use that lame stuff as a bot , we might as well look at how it looks ..

don't be ashamed of your work and delete it again please :)

![screen shot 2016-04-19 at 07 48 09](https://cloud.githubusercontent.com/assets/14038239/14630687/714afedc-0639-11e6-92bd-ed168be2eea3.png)

**Comment by FliiFe** [comment]
Finding a corner should be sufficient, but that would be quite difficult to
implement. I will try to implement this this afternoon. However, we don't
know if miniclip changes the map size.

**Comment by muratlahur** [comment]
no, maps are fixed squares..
as soon as you find a corner from there on you know EXACTLY where you are...

Thanks for trying and I hope you get it up and running asap :)

**Comment by muratlahur** [comment]
ideally bot should not try to push wall angles until a CornerFound variable is positive..This is equivalent to disabling the wall code like Apos did, however once the corner is found wall angles can be pushed like normal

**Comment by FliiFe** [comment]
I'm not home right now, but I am pretty sure Apos did not remove the wall
code, he just disabled it.

**Comment by muratlahur** [comment]
yah, he commented out the push of angles , in effect disabling it like I've said .. I've never said he removed it .. the code is still there.. just commented out

**Comment by ErmiyaEskandary** [comment]
I'm not ashamed of my work.

**Comment by ErmiyaEskandary** [comment]
@Apostolique Please verify his info on how to fix it. If it is valid, please re unlock this conversation.
@muratlahur If you know how to fix it, make a PR - not an issue. When I close an issue, I have a valid reason

**Comment by ErmiyaEskandary** [comment]
Acknowledged here - https://github.com/Apostolique/Agar.io-bot/issues/597
