### ISSUE TITLE
####

### ISSUE THREAD

**Issue by muratlahur** [Apostolique/Agar.io-bot#591]
######

**Comment by ErmiyaEskandary** [comment]
Its advertising "boy".

**Comment by muratlahur** [comment]
nah, I'm just trying to find someone with senses to work with .. 
advertise what ?? something that I don't sell and I don't release ???

**Comment by ErmiyaEskandary** [comment]
advertising
noun
the activity or profession of producing advertisements for commercial products or **services**.

**Comment by ErmiyaEskandary** [comment]
Find someone somewhere else - we are contributing to a project here.

**Comment by muratlahur** [comment]
I know what advertising is .. where is the commercial product or service ?
either you prove that or your actions look a little bit hectic and delusional .

almost like a young , umm , boy ?

:P 

oh this is fun

**Comment by muratlahur** [comment]
and besides , to this project I've probably contributed more than you so far ;)

**Comment by muratlahur** [comment]
or probably you'll also delete my words again and make everything look ok ??

seriously ?
