### ISSUE TITLE
Live stream alert removal

### ISSUE THREAD

**Issue by FliiFe** [Apostolique/Agar.io-bot#603]
### Alert removal, discussion

It seems like some people from this commutity want the "Apostolique is live" alert removed. I'm not going to give my advice on this yet, just let people discuss on this. 

### Current arguments

| Who ? | Why should it be removed ? | Why shouldn't it be removed ? |
|-------------|------------------------------|---------------------------------|
| @muratlahur | Alert is too obtrusive |  |
| @muratlahur | Credit should be given to the whole community |  |
| @muratlahur | The way the alert is displayed and can be discarded causes accessibility issues |  |

I will update this table as new opinions come.

**Comment by ErmiyaEskandary** [comment]
Ads have been removed - which other ads ?

**Comment by ErmiyaEskandary** [comment]
It isn't an ad - it is just a alert.

**Comment by FliiFe** [comment]
@ErmiyaEskandary "twitch.tv/apostolique is online right now!"

**Comment by ErmiyaEskandary** [comment]
Does that show a box or in the console ?

**Comment by ErmiyaEskandary** [comment]
Some people might want to know when he is online - 

> I'm not going to give my advice on this yet

Same here

**Comment by FliiFe** [comment]
@ErmiyaEskandary That shows up like the "UPDATE BOT", kinda obtrusive, to be fair

**Comment by ErmiyaEskandary** [comment]
Doesn't it go away ?

**Comment by ErmiyaEskandary** [comment]
I believe it shouldn't be there - but it's Apos's opinion. Should I change it so it only shows it in the console ? It won't be obtrusive then.

**Comment by FliiFe** [comment]
@ErmiyaEskandary It won't be obtrusive, but It will be unuseful. I think we should wait ~1 week to collect advices from the community

**Comment by ErmiyaEskandary** [comment]
@FliiFe I have no problem with that. :)

**Comment by muratlahur** [comment]
I have a problem , I play with a bluetooth mouse and a projector, my keyboard is far away and I never ever touch it .. 

I guess there maybe other examples..

besides forcing people to look at your stuff (I personally find it utterly boring and irrelevant) is just not the way to go .. 

my two cents

**Comment by Drflash55** [comment]
It was used as a way to let people know that he's streaming on Twitch. It usually led you to watch the progress on the bot to see what kind of new features that he's implementing...

At least, when he USED to stream about Agar.io...

**Comment by muratlahur** [comment]
Ok I chip in to the show it in the console idea !! If some geek really want to get to apos, (or whomever) the console will be a fair enough place .. 

So not every user that downloads the bots has to get that in their face.. 

And FliiFe, you are more liberal than I thought .. 

I start to like you :)

**Comment by ErmiyaEskandary** [comment]
So he can't stream anymore about agar.io as it's copyright ?

**Comment by muratlahur** [comment]
I'd say the hell with it . but it's apos stuff .. I assume he'll have the last word..

I personally find it irritating and it is the first bit of code I've deleted from his bot

**Comment by Drflash55** [comment]
I think it's kind of useless, because he can't stream Agar.io anymore... You can get another extensions which will enable desktop notifications for when a twitch streamer you follow goes live, so this is no longer necessary.

**Comment by muratlahur** [comment]
so you can safely do what I did. delete the code entirely .. less bandwidth use , less game clutter etc.

**Comment by ErmiyaEskandary** [comment]
@Drflash55 so remove ?

**Comment by Drflash55** [comment]
@ErmiyaEskandary You can remove it, as it's entirely useless...

**Comment by ErmiyaEskandary** [comment]
@Drflash55 In progress..
