### ISSUE TITLE
Dynamic Threat Management

### ISSUE THREAD

**Issue by muratlahur** [Apostolique/Agar.io-bot#606]
`var splitDangerDistance = (allPossibleThreats0[i].size + 930) / Math.sqrt(badAngles.length + 1);
                    var normalDangerDistance = (allPossibleThreats0[i].size + 200) / Math.sqrt(badAngles.length + 0.8);`

If you change your codes into this , now the split danger distance and the normal danger distance of the enemies will be reduced if there are more of them around , so if a few of them squeeze you the bot kinda gives-in from the danger distances and gets loads of headroom 

N-Joy

**Comment by ErmiyaEskandary** [comment]
Needs testing.

**Comment by FliiFe** [comment]
@muratlahur Please see #607
