### ISSUE TITLE
Sorting Threats According to distance

### ISSUE THREAD

**Issue by muratlahur** [Apostolique/Agar.io-bot#608]
In your bot find and un-comment the code below 

`/*allPossibleThreats.sort(function(a, b){
                        return a.enemyDist-b.enemyDist;
                    })*/`

in doing so you will sort the threats according to their distance , when this is used in conjunction with the dynamic threat management , bot becomes very very slippery and almost impossible to eat ..

**Comment by FliiFe** [comment]
Please see #607.
