### ISSUE TITLE
[Idea] Server Selector & Browser

### ISSUE THREAD

**Issue by larsjuhw** [Apostolique/Agar.io-bot#61]
Hey, it would be awesome if you could add a server selector and/or a server browser because I want to play this with friends and other server selectors don't seem to be compatible with this script.

**Comment by FloThinksPi** [comment]
can confirm incompatibility with agar server browser chrome plugins

**Comment by Apostolique** [comment]
Why do you even need a server selector? You just need to press F12 while on the Agar page and enter the IP: window.connect("ws:167.114.174.68:1507")

**Comment by larsjuhw** [comment]
Oh I didn't know that

**Comment by larsjuhw** [comment]
This doesn't work on a Mac?

**Comment by Apostolique** [comment]
Just search for how to access the console for your browser it might be different I don't know.
