### ISSUE TITLE
Cannot read property 'size' of null

### ISSUE THREAD

**Issue by kakol20** [Apostolique/Agar.io-bot#612]
The bot freezes and shows `Cannot read property 'size' of null` on the console.

It unfreezes after a while.

Screenshot : http://i.imgur.com/QKgkAcz.png

**Comment by ErmiyaEskandary** [comment]
Can you tell me where you get the apos not defined error ?

**Comment by muratlahur** [comment]
yes that was a bug I've fixed in my bot .. true , you'll get that error with apos bot

**Comment by kakol20** [comment]
I'm not too sure

**Comment by ErmiyaEskandary** [comment]
Fixing right now ....

**Comment by FliiFe** [comment]
Fixed with last commit. Closing.
