### ISSUE TITLE
update

### ISSUE THREAD

**Issue by chugzyboi** [Apostolique/Agar.io-bot#619]

**Comment by Drflash55** [comment]
Invalid issue...

**Comment by rcdarich** [comment]
Main Characters



         Bobby and Logan



Chapter 1 Uh-Oh We Got Caught



Bobby and Logan are brothers that live in Boston, Massachusetts right next
to the Boston Red Sox field one night they had an idea while their mom was
at work and their dad was running on the beach. They always wanted to go to
the Boston Red Sox field so they got some rope and threw up the rope into
the Red Sox field and climbed over the wall. Nobody was there but security
that was outside the field they had a baseball bat and some baseballs to
hit and they stayed there for thirty-minutes or so and they were going to
leave but then security shows up and Logan threw baseballs at them and
knocked one out and they escaped but now the cops are for them.





     Chapter 2 We Have A Car Get Away





         They got back to there house and get inside but the cops are
breaking the door then we jump out the window and land on garbage bags
luckily we just got rid of pillows

**Comment by Drflash55** [comment]
Since this is an invalid issue, it will be treated as such...
