### ISSUE TITLE
stuck at [0,0] in top left corner

### ISSUE THREAD

**Issue by Andrew900460** [Apostolique/Agar.io-bot#62]
Me, including everyone else on the server seems to be stuck in the top left corner of the map (in google chrome) , when i open agar.io in internet explorer (which has no scripts running) the game works fine.

**Comment by dombeef** [comment]
Youre running outdated bot code, redownload the scripts and try again, it should work just fine.

**Comment by Apostolique** [comment]
If you're using Tampermonkey, you might need to delete the current version that you have installed, then install the new one. I noticed Tampermonkey doesn't always refresh the script when you try to install the new one.
