### ISSUE TITLE
invisible begin button

### ISSUE THREAD

**Issue by tonimark** [Apostolique/Agar.io-bot#627]
screen scrolled down and i can't scroll up and click begin button

**Comment by elprincefosdo2** [comment]
yes me too what i make??

![image](https://cloud.githubusercontent.com/assets/19784260/15834299/16384370-2c2b-11e6-9f13-cc5517901001.png)

**Comment by elprincefosdo2** [comment]
help me please

**Comment by DanielGuevara45** [comment]
Hey I Have The Same Problem To

**Comment by SscSPs** [comment]
This will supposedly not be fixed anytime in the foreseeable future

**Comment by Drflash55** [comment]
Refer to #616.
