### ISSUE TITLE
suggestion: select feature

### ISSUE THREAD

**Issue by Cheeseskates** [Apostolique/Agar.io-bot#63]
it is nice to see the bot walk around and do its thing, but i would also like a feature where you control the bots AI function though simple actions.

what i suggest is a select feature, where you can click (preferably right click) on any area to direct the bot to it, and will get there through all dangers inbound. once it reaches its destination, the select feature turns off, and it does its thing again. you can also rapid click, if small, inside a virus so it doesn't move out, to protect itself from big blobs.

also for the select feature, i would like for you to click (preferably right click) on a player to give chase, ignoring the pellets it comes by, to attempt to eat the player. it will also see and try to split kill the player using its prediction line, preferably when there is no threats like viruses or other bigger enemies or enemies the same size as you before splitting. to deactivate, press left click to stop chase and restore the automatic roam function. another one for left click is to click on any blob, or any area, to make the bot move away from the area, or evade the chasing big blob. it will see if it can do a split attack, and try to do zigzags or unpredictable movement to trick them (only if small) or it can split itself away from danger (preferably when your blob is big) and live on.

hope this suggestion and its features are taken into consideration, and good luck with the bot :D

**Comment by Apostolique** [comment]
I really like this idea. It would be hard to implement though so I'll have to think about it.

**Comment by Cheeseskates** [comment]
take your time my friend

**Comment by Apostolique** [comment]
If you try the beta.user.js, you can press Q and the bot will follow your mouse.
