### ISSUE TITLE
Question about someone elses bot script.

### ISSUE THREAD

**Issue by Andrew900460** [Apostolique/Agar.io-bot#65]
I was using somone elses bot script which used the same line draws taht yours used when detecting the spikey blobs and enemy blobs. Except his allowed to change the color or all the blobs showing which ones were capable of eating you and which ones you could eat. Do you know this person? I deleted the user script before thinking of what his github name was so now i can't find him.

**Comment by Apostolique** [comment]
You can probably find it if you look at the forks. https://github.com/Apostolique/Agar.io-bot/network
I don't know which one it is exactly.
