### ISSUE TITLE
Suggestion: Multiple suggestions

### ISSUE THREAD

**Issue by Andrew900460** [Apostolique/Agar.io-bot#67]
I found that forked code that I asked you about before. But It seems that his isn't up to date and it's the one that freezes me at [0,0]. I like what you did with the UI, but I would like to see some of the features that are in this fork of your script  https://github.com/dombeef/Agar.io-bot

1. Recoloring players based on their size relative to your size, If you are thinking of making a gradient if you are going to implement that. Don't. the way this guy does the coloring is pretty straight forward.

2. His script allowed for zooming out and such, but I think that someone said they patched that so it can't happen?

**Comment by Apostolique** [comment]
I only add stuff that the bot will need, or to help debugging.
