### ISSUE TITLE
An Issue

### ISSUE THREAD

**Issue by MiniAssassin78** [Apostolique/Agar.io-bot#70]
Even after the new update this happens https://www.dropbox.com/s/d70uh6ljjnusn79/Screenshot%202015-06-07%2023.16.21.png?dl=0

I don't have any other scripts installed, I am using Opera. However, I am using AdBlock Plus. Please help.

**Comment by TheKingsman11** [comment]
I've Had The SAME Exact Issue

**Comment by Apostolique** [comment]
Update Launcher.
