### ISSUE TITLE
Human issue

### ISSUE THREAD

**Issue by DarkN3ss61** [Apostolique/Agar.io-bot#73]
When human is selected, you cant turn bot on or off even though it says that is it being turned on and off in the top left, same with lines

**Comment by Apostolique** [comment]
So?

**Comment by DarkN3ss61** [comment]
Shouldn't that text be removed so it doesn't confuse people?

**Comment by Apostolique** [comment]
Not that important really.

**Comment by DarkN3ss61** [comment]
Then whats the point of having the human option if you could just turn it off yourself?

**Comment by Apostolique** [comment]
If you only have the launcher and no bots, you then have human as fallback.

**Comment by DarkN3ss61** [comment]
Ahh I understand now, so its a modular system, thats cool!
