### ISSUE TITLE
Cant choose name, server or setting before I start

### ISSUE THREAD

**Issue by DarkN3ss61** [Apostolique/Agar.io-bot#77]
After the latest update there is not longer a way to choose name, server or setting before I start. I have to press esc while playing then kill myself for my name to change, are you able to roll back to how it was before? where you could choose the settings, name etc before playing?

**Comment by Apostolique** [comment]
I prefer this current version as it's a lot easier to update.

**Comment by DarkN3ss61** [comment]
Ok, but I have a bunch of people complaining that they cant change their usernames, most of them dont realise that you cant press Esc

**Comment by Apostolique** [comment]
Pressing ESC isn't that hard.

**Comment by DarkN3ss61** [comment]
I know its not, but try telling that to the retards trying to use your bot

**Comment by Piehthyte** [comment]
People don't want to have anyone else see that they are using a bot :P They prefer to look normal to an extent so they put their names and move along.

**Comment by chris13524** [comment]
There needs to be a GitHub chat room.

Chris Smith
