### ISSUE TITLE
Better selection system

### ISSUE THREAD

**Issue by akhilcjacob** [Apostolique/Agar.io-bot#80]
I haven't look into the code too much but it seems like the selection system is a little off, choosing random dots on the screen rather than larger more acceptable closer food choices. Perhaps putting a human interruption system to choose a specific target and follow the target until some button is hit. This script is pretty amazing, and cool.

**Comment by Apostolique** [comment]
Are you saying it's picking dots badly all the time, or only when there's an enemy chasing?

**Comment by akhilcjacob** [comment]
I'm saying when there are good opportunities to go after a smaller massed enemy itd rather choose tiny dots rather than go after a more opportunistic target

**Comment by Apostolique** [comment]
You'll have to be more precise than that or I won't change anything. Or record evidence proof of that happening.
