### ISSUE TITLE
Angle coding suggestion

### ISSUE THREAD

**Issue by poilss** [Apostolique/Agar.io-bot#85]
![botangles](https://cloud.githubusercontent.com/assets/12835484/8092829/f4d05bea-0fbc-11e5-9282-eb4ec5cf3fd2.png)

    var data = [[x,α], [y,β], [z,γ]]; // as in the picture

    data.sort(function(a,b){return a[0]-b[0]});
    data.push(data[0]); // ensure the angle from z to x is handled correctly

    /* This finds the size of the free angle between blobs i and i+1. First
        compute the angle between the vector and then subtract the blob
        angle sizes (half for each). This can be negative when two blobs are
        close to each other and too fat. */
    var getFreeAngle = function(i) {
      return (data[i+1][0] - data[i][0]).mod(2*Math.PI)
                  - data[i][1] / 2 - data[i+1][1] / 2;
    }

    // find the largest free angle
    var I = 0;
    for (var i = 1; i < data.length - 1; ++i)
      if (getFreeAngle(i) > getFreeAngle(I))
        I = i;

    // this is the direction we want to go in
    var direction = (data[I][0] + data[I][1] / 2 +
                                        getFreeAngle(I) / 2).mod(2*Math.PI);

**Comment by Apostolique** [comment]
In the end, I went with a list based angle merging algorithm.
