### ISSUE TITLE
Make it compatible with the Experimental gamemode

### ISSUE THREAD

**Issue by DarkN3ss61** [Apostolique/Agar.io-bot#91]
Would you be able to get it working/optimised  the the Experimental game mode please http://www.agarioguide.com/game-mode-experimental/

**Comment by Apostolique** [comment]
I'm not sure what you want, you already can join that mode with the bot.

**Comment by DarkN3ss61** [comment]
Yet, but I was wanting it more optimised for that game mode, e.g tends to stay more around the red spikes to get bigger faster and push other players into bigger players, all that sort of thing

**Comment by Apostolique** [comment]
It sounds like you want me to write a completely new bot and then maintain both his one and the new one.

**Comment by DarkN3ss61** [comment]
His one? Im a bit confused. All im asking is can you add in a option so if the "Experimental" game mode is selected, the bot will run around until it finds a spiky red ball and then hover around that area collecting the dots it spits out

**Comment by Apostolique** [comment]
I'd rather just focus on FFA. Everything in experimental mode will just get changed anyway. If I do that, I'll just end up writing code that becomes obsolete everything the mode changes.

**Comment by DarkN3ss61** [comment]
Fair enough
