### ISSUE TITLE
Walls

### ISSUE THREAD

**Issue by langjam350** [Apostolique/Agar.io-bot#92]
I've noticed this issue for awhile but i can't make it too specific. The bot seems to die a lot more once it gets around a wall. I don't know how easy a fix will be for this but it seems to be that the bot is not recognizing that there is a wall there so one idea i had was to create a "safe zone" around the walls.

**Comment by Apostolique** [comment]
Are you sure you are running the right bot? The current version does handle walls. While I can make the wall code better, you can't say the bot doesn't handle them at all.

**Comment by langjam350** [comment]
Yeah I wasn't exactly using the newest version. Thank you and good luck
with your project!
