### ISSUE TITLE
Sloshing around

### ISSUE THREAD

**Issue by Sea-n** [Apostolique/Agar.io-bot#93]
If both sides equidistant points / players, Bot will run back and forth

如果兩邊有等距的點/玩家，Bot 會來回跑

**Comment by Candunc** [comment]
Can confirm, have seen this behavior before. The bot should make a decision or prefer one over the other.

**Comment by thecodewarrior** [comment]
Could the "weight" of the currently targeted object have a slight boost? So if there is another better option the bot will take it, but if two are almost identical the bot will stick with which ever one it picks first.
