### ISSUE TITLE
Script blocked by Agar.io

### ISSUE THREAD

**Issue by Candunc** [Apostolique/Agar.io-bot#95]
I have used the latest version of the script, however as soon as I go to agar.io I am greeted with a white screen. As soon as I disable the launcher plugin, the game returns to normal.

**Comment by AlJohri** [comment]
+1

**Comment by MichaelHaushofer** [comment]
after 2 hours i ive the same problem. ip change doenst help.

**Comment by DarkN3ss61** [comment]
Yep I can confirm that it is not working, not necessary blocked but it is not working

**Comment by AlJohri** [comment]
its a large change to the code I think. I don't see the Quad tree being used in the main_out.js explicitly and the minifier has changed all the variable names

**Comment by Apostolique** [comment]
Yeah, a lot had changed.
