### ISSUE TITLE
dont work in the new version

### ISSUE THREAD

**Issue by igor8899** [Apostolique/Agar.io-bot#98]
this version of agar.io dont let me play the mod the page stay white forever :I

**Comment by Apostolique** [comment]
Before starting an issue, update the script at least.

**Comment by igor8899** [comment]
no the mod still dont work man i already updated but dont work

**Comment by Apostolique** [comment]
Then you'll have to give me more info or I can't do anything, current version works for me and many people.

**Comment by igor8899** [comment]
ok i installed the mod normally and works normally but when the agar.io updated now he dont work i use the firefox plugin i tried to use the chrome but same thing or Opera same thing when i enter agar.io stay in a white screen and he dont load i tried to reinstall and nothing happen fix this please

**Comment by Apostolique** [comment]
Uninstall first the script first, then reinstall then.

**Comment by igor8899** [comment]
i already do this

**Comment by Apostolique** [comment]
In that case, I will need screenshots because with the information I have right now, there is nothing that I can do.

**Comment by igor8899** [comment]
here
![sem titulo](https://cloud.githubusercontent.com/assets/12837251/8145988/4832c63e-11f6-11e5-9480-f3bbb87d49ca.png)
the icon dont appears too and this is the image of the mods off
![sem titulo](https://cloud.githubusercontent.com/assets/12837251/8146001/1912b930-11f7-11e5-9f8d-600ab57d2c4b.png)

**Comment by igor8899** [comment]
with the mods on i refresh the page but the icon dont appears too

**Comment by Apostolique** [comment]
I want to see how which scripts you have installed. The version, etc.

**Comment by igor8899** [comment]
![sem titulo](https://cloud.githubusercontent.com/assets/12837251/8146006/50c0be40-11f7-11e5-9397-583bd3f3cbbf.png)

**Comment by igor8899** [comment]
![sem titulo](https://cloud.githubusercontent.com/assets/12837251/8146007/5d7d2ad8-11f7-11e5-8573-e6cc04ffa18e.png)

**Comment by Apostolique** [comment]
Can you try turning the launcher off? Then turn only AposBot off?

**Comment by igor8899** [comment]
tried this go but i cant control the bot anymore

**Comment by igor8899** [comment]
this work but i cant control the bot

**Comment by igor8899** [comment]
wait update thanks my man my game is fixed now

**Comment by Apostolique** [comment]
Nice!
